// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPToFP(	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
  input         clock,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
                reset,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
                io_in_valid,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
                io_in_bits_ren2,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  input  [1:0]  io_in_bits_typeTagOut,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  input         io_in_bits_wflags,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  input  [2:0]  io_in_bits_rm,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  input  [64:0] io_in_bits_in1,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
                io_in_bits_in2,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  output [64:0] io_out_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  output [4:0]  io_out_bits_exc,	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
  input         io_lt	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
);

  wire [32:0] _narrower_io_out;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:613:30
  wire [4:0]  _narrower_io_exceptionFlags;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:613:30
  reg         in_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg         in_pipe_b_ren2;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [1:0]  in_pipe_b_typeTagOut;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         in_pipe_b_wflags;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [2:0]  in_pipe_b_rm;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [64:0] in_pipe_b_in1;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [64:0] in_pipe_b_in2;	// src/main/scala/chisel3/util/Valid.scala:142:26
  wire        _GEN = in_pipe_b_wflags & ~in_pipe_b_ren2;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:602:{24,27}, src/main/scala/chisel3/util/Valid.scala:142:26
  wire [64:0] fsgnjMux_data =
    _GEN
      ? ((&(in_pipe_b_in1[63:61])) ? 65'hE008000000000000 : in_pipe_b_in1)
      : in_pipe_b_wflags
          ? ((&(in_pipe_b_in1[63:61])) & (&(in_pipe_b_in2[63:61]))
               ? 65'hE008000000000000
               : (&(in_pipe_b_in2[63:61])) | in_pipe_b_rm[0] != io_lt
                 & ~(&(in_pipe_b_in1[63:61]))
                   ? in_pipe_b_in1
                   : in_pipe_b_in2)
          : {in_pipe_b_rm[1]
               ? in_pipe_b_in1[64] ^ in_pipe_b_in2[64]
               : in_pipe_b_rm[0] ^ in_pipe_b_in2[64],
             in_pipe_b_in1[63:0]};	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:244:{25,56}, :576:{20,31,48,66,77}, :577:{18,45}, :581:17, :583:25, :587:27, :588:{24,41,51,54}, :590:{19,25,53}, :602:{24,42}, :605:24, :606:21, src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [64:0] io_out_pipe_b_data;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [4:0]  io_out_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
  always @(posedge clock) begin	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
    if (reset)	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      in_pipe_v <= 1'h0;	// src/main/scala/chisel3/util/Valid.scala:141:24
    else	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      in_pipe_v <= io_in_valid;	// src/main/scala/chisel3/util/Valid.scala:141:24
    if (io_in_valid) begin	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:568:14
      in_pipe_b_ren2 <= io_in_bits_ren2;	// src/main/scala/chisel3/util/Valid.scala:142:26
      in_pipe_b_typeTagOut <= io_in_bits_typeTagOut;	// src/main/scala/chisel3/util/Valid.scala:142:26
      in_pipe_b_wflags <= io_in_bits_wflags;	// src/main/scala/chisel3/util/Valid.scala:142:26
      in_pipe_b_rm <= io_in_bits_rm;	// src/main/scala/chisel3/util/Valid.scala:142:26
      in_pipe_b_in1 <= io_in_bits_in1;	// src/main/scala/chisel3/util/Valid.scala:142:26
      in_pipe_b_in2 <= io_in_bits_in2;	// src/main/scala/chisel3/util/Valid.scala:142:26
    end
    if (in_pipe_v) begin	// src/main/scala/chisel3/util/Valid.scala:141:24
      automatic logic       _GEN_0;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:597:18
      automatic logic [8:0] _mux_data_expOut_commonCase_T = fsgnjMux_data[60:52] - 9'h100;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:271:18, :275:31, :583:25, :602:42, :606:21
      _GEN_0 = in_pipe_b_typeTagOut == 2'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:597:18, src/main/scala/chisel3/util/Valid.scala:142:26
      io_out_pipe_b_data <=
        _GEN_0
          ? (_GEN
               ? {fsgnjMux_data[64:33], _narrower_io_out}
               : {fsgnjMux_data[64:33],
                  fsgnjMux_data[64],
                  fsgnjMux_data[63:61] == 3'h0 | fsgnjMux_data[63:61] > 3'h5
                    ? {fsgnjMux_data[63:61], _mux_data_expOut_commonCase_T[5:0]}
                    : _mux_data_expOut_commonCase_T,
                  fsgnjMux_data[51:29]})
          : fsgnjMux_data;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:269:17, :271:18, :272:38, :274:26, :275:{31,50}, :276:{10,19,27,38,49,69}, :583:25, :595:24, :597:{18,36}, :598:{16,22,37}, :602:{24,42}, :606:21, :612:126, :613:30, :618:{18,24,39}, src/main/scala/chisel3/util/Valid.scala:142:26
      io_out_pipe_b_exc <=
        _GEN & _GEN_0
          ? _narrower_io_exceptionFlags
          : _GEN
              ? {(&(in_pipe_b_in1[63:61])) & ~(in_pipe_b_in1[51]), 4'h0}
              : in_pipe_b_wflags
                  ? {(&(in_pipe_b_in1[63:61])) & ~(in_pipe_b_in1[51])
                       | (&(in_pipe_b_in2[63:61])) & ~(in_pipe_b_in2[51]),
                     4'h0}
                  : 5'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:244:{25,56}, :245:{34,37,39}, :567:7, :580:16, :583:25, :586:49, :589:{18,31}, :595:24, :597:18, :602:{24,42}, :607:{20,51}, :612:126, :613:30, :619:17, src/main/scala/chisel3/util/Valid.scala:142:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      `FIRRTL_BEFORE_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      automatic logic [31:0] _RANDOM[0:9];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      `ifdef INIT_RANDOM_PROLOG_	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
        `INIT_RANDOM_PROLOG_	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
        end	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
        in_pipe_v = _RANDOM[4'h0][0];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24
        in_pipe_b_ren2 = _RANDOM[4'h0][4];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        in_pipe_b_typeTagOut = _RANDOM[4'h0][11:10];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        in_pipe_b_wflags = _RANDOM[4'h0][18];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        in_pipe_b_rm = _RANDOM[4'h0][21:19];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        in_pipe_b_in1 = {_RANDOM[4'h0][31:28], _RANDOM[4'h1], _RANDOM[4'h2][28:0]};	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        in_pipe_b_in2 = {_RANDOM[4'h2][31:29], _RANDOM[4'h3], _RANDOM[4'h4][29:0]};	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:142:26
        io_out_pipe_b_data = {_RANDOM[4'h7], _RANDOM[4'h8], _RANDOM[4'h9][0]};	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:142:26
        io_out_pipe_b_exc = _RANDOM[4'h9][5:1];	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:142:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
      `FIRRTL_AFTER_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RecFNToRecFN narrower (	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:613:30
    .io_in             (in_pipe_b_in1),	// src/main/scala/chisel3/util/Valid.scala:142:26
    .io_roundingMode   (in_pipe_b_rm),	// src/main/scala/chisel3/util/Valid.scala:142:26
    .io_out            (_narrower_io_out),
    .io_exceptionFlags (_narrower_io_exceptionFlags)
  );
  assign io_out_bits_data = io_out_pipe_b_data;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:142:26
  assign io_out_bits_exc = io_out_pipe_b_exc;	// home/xyl/exp/rocket-chip/src/main/scala/tile/FPU.scala:567:7, src/main/scala/chisel3/util/Valid.scala:142:26
endmodule

