// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLXbar(	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  input         clock,	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
                reset,	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  output        auto_in_a_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_in_a_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_in_a_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_a_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_a_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_in_a_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [31:0] auto_in_a_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [7:0]  auto_in_a_bits_mask,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [63:0] auto_in_a_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_in_a_bits_corrupt,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_b_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_in_b_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_in_b_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [31:0] auto_in_b_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_in_c_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_in_c_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_in_c_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_c_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_c_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_in_c_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [31:0] auto_in_c_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [63:0] auto_in_c_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_in_d_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_in_d_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [2:0]  auto_in_d_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_in_d_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [2:0]  auto_in_d_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_in_d_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_in_d_bits_sink,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_in_d_bits_denied,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [63:0] auto_in_d_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_in_d_bits_corrupt,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_in_e_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_in_e_bits_sink,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_a_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_1_a_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [2:0]  auto_out_1_a_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_1_a_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_1_a_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_out_1_a_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [31:0] auto_out_1_a_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [7:0]  auto_out_1_a_bits_mask,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [63:0] auto_out_1_a_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_1_b_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_b_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_out_1_b_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [31:0] auto_out_1_b_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_c_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_1_c_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [2:0]  auto_out_1_c_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_1_c_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_1_c_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_out_1_c_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [31:0] auto_out_1_c_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [63:0] auto_out_1_c_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_1_d_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_d_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_out_1_d_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_out_1_d_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_out_1_d_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_out_1_d_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_1_d_bits_sink,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_d_bits_denied,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [63:0] auto_out_1_d_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_1_d_bits_corrupt,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_1_e_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_out_1_e_bits_sink,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_0_a_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_0_a_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [2:0]  auto_out_0_a_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_0_a_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_0_a_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [1:0]  auto_out_0_a_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [28:0] auto_out_0_a_bits_address,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [7:0]  auto_out_0_a_bits_mask,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output [63:0] auto_out_0_a_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  output        auto_out_0_a_bits_corrupt,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_0_d_ready,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_0_d_valid,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_out_0_d_bits_opcode,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_out_0_d_bits_param,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [2:0]  auto_out_0_d_bits_size,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [1:0]  auto_out_0_d_bits_source,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_0_d_bits_sink,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
                auto_out_0_d_bits_denied,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input  [63:0] auto_out_0_d_bits_data,	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
  input         auto_out_0_d_bits_corrupt	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18
);

  reg  [2:0] beatsLeft;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30
  wire       idle = beatsLeft == 3'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :61:28, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:230:18
  wire [1:0] readys_valid = {auto_out_1_d_valid, auto_out_0_d_valid};	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:68:51
  reg  [1:0] readys_mask;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23
  wire [1:0] _readys_filter_T_1 = readys_valid & ~readys_mask;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23, :24:{28,30}, :68:51
  wire [1:0] readys_readys =
    ~({readys_mask[1], _readys_filter_T_1[1] | readys_mask[0]}
      & ({_readys_filter_T_1[0], auto_out_1_d_valid} | _readys_filter_T_1));	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23, :24:28, :25:58, :26:{18,29,39}, home/xyl/exp/rocket-chip/src/main/scala/util/package.scala:254:43
  wire       winner_0 = readys_readys[0] & auto_out_0_d_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:26:18, :68:76, :71:69
  wire       winner_1 = readys_readys[1] & auto_out_1_d_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:26:18, :68:76, :71:69
  wire       _in_0_d_valid_T = auto_out_0_d_valid | auto_out_1_d_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:79:31
  `ifndef SYNTHESIS	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
    always @(posedge clock) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
      if (~reset & ~(~winner_0 | ~winner_1)) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:71:69, :77:{13,56,59,62}
        if (`ASSERT_VERBOSE_COND_)	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
          $fwrite(32'h80000002, "Assertion failed\n    at Arbiter.scala:77 assert((prefixOR zip winner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
        if (`STOP_COND_)	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
          xs_assert_v2(`__FILE__, `__LINE__);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:77:13
      end
      if (~reset & ~(~_in_0_d_valid_T | winner_0 | winner_1)) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:71:69, :77:13, :79:{14,15,31,36}
        if (`ASSERT_VERBOSE_COND_)	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:79:14
          $fwrite(32'h80000002, "Assertion failed\n    at Arbiter.scala:79 assert (!valids.reduce(_||_) || winner.reduce(_||_))\n");	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:79:14
        if (`STOP_COND_)	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:79:14
          xs_assert_v2(`__FILE__, `__LINE__);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:79:14
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg        state_0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
  reg        state_1;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26
  wire       muxState_0 = idle ? winner_0 : state_0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:61:28, :71:69, :88:26, :89:25
  wire       muxState_1 = idle ? winner_1 : state_1;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:61:28, :71:69, :88:26, :89:25
  wire       in_0_d_valid =
    idle ? _in_0_d_valid_T : state_0 & auto_out_0_d_valid | state_1 & auto_out_1_d_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:61:28, :79:31, :88:26, :96:24, src/main/scala/chisel3/util/Mux.scala:30:73
  always @(posedge clock) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
    if (reset) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      beatsLeft <= 3'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:230:18
      readys_mask <= 2'h3;	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/Parameters.scala:57:20, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23
      state_0 <= 1'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      state_1 <= 1'h0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:88:26, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
    end
    else begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      automatic logic latch = idle & auto_in_d_ready;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:61:28, :62:24
      if (latch) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:62:24
        automatic logic [12:0] _beatsDO_decode_T_3 = 13'h3F << auto_out_1_d_bits_size;	// home/xyl/exp/rocket-chip/src/main/scala/util/package.scala:235:71
        automatic logic [12:0] _beatsDO_decode_T = 13'h3F << auto_out_0_d_bits_size;	// home/xyl/exp/rocket-chip/src/main/scala/util/package.scala:235:71
        beatsLeft <=
          (winner_0 ? ~(_beatsDO_decode_T[5:3]) : 3'h0)
          | (winner_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_3[5:3]) : 3'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :71:69, :82:69, :84:44, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:230:18, home/xyl/exp/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}
      end
      else	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:62:24
        beatsLeft <= beatsLeft - {2'h0, auto_in_d_ready & in_0_d_valid};	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :85:52, :96:24, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:230:18, src/main/scala/chisel3/util/Decoupled.scala:51:35
      if (latch & (|readys_valid)) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:27:{18,27}, :62:24, :68:51
        automatic logic [1:0] _readys_mask_T = readys_readys & readys_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:26:18, :28:29, :68:51
        readys_mask <= _readys_mask_T | {_readys_mask_T[0], 1'h0};	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23, :28:29, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, home/xyl/exp/rocket-chip/src/main/scala/util/package.scala:245:{43,53}
      end
      if (idle) begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:61:28
        state_0 <= winner_0;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:71:69, :88:26
        state_1 <= winner_1;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:71:69, :88:26
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
    `ifdef FIRRTL_BEFORE_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      `FIRRTL_BEFORE_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      automatic logic [31:0] _RANDOM[0:0];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      `ifdef INIT_RANDOM_PROLOG_	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        `INIT_RANDOM_PROLOG_	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        beatsLeft = _RANDOM[/*Zero width*/ 1'b0][2:0];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        readys_mask = _RANDOM[/*Zero width*/ 1'b0][4:3];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:23:23, :60:30, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        state_0 = _RANDOM[/*Zero width*/ 1'b0][5];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :88:26, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
        state_1 = _RANDOM[/*Zero width*/ 1'b0][6];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:60:30, :88:26, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
      `FIRRTL_AFTER_INITIAL	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign auto_in_a_ready =
    ~(auto_in_a_bits_address[31]) & auto_out_0_a_ready | auto_in_a_bits_address[31]
    & auto_out_1_a_ready;	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_b_valid = auto_out_1_b_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_in_b_bits_param = auto_out_1_b_bits_param;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_in_b_bits_address = auto_out_1_b_bits_address;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_in_c_ready = auto_out_1_c_ready;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_in_d_valid = in_0_d_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:96:24, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_in_d_bits_opcode =
    (muxState_0 ? auto_out_0_d_bits_opcode : 3'h0)
    | (muxState_1 ? auto_out_1_d_bits_opcode : 3'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_param =
    (muxState_0 ? auto_out_0_d_bits_param : 2'h0)
    | (muxState_1 ? auto_out_1_d_bits_param : 2'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_size =
    (muxState_0 ? auto_out_0_d_bits_size : 3'h0)
    | (muxState_1 ? auto_out_1_d_bits_size : 3'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_source =
    (muxState_0 ? auto_out_0_d_bits_source : 2'h0)
    | (muxState_1 ? auto_out_1_d_bits_source : 2'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_sink =
    (muxState_0 ? {1'h0, auto_out_0_d_bits_sink} : 2'h0)
    | (muxState_1 ? auto_out_1_d_bits_sink : 2'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, :248:28, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_denied =
    muxState_0 & auto_out_0_d_bits_denied | muxState_1 & auto_out_1_d_bits_denied;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_data =
    (muxState_0 ? auto_out_0_d_bits_data : 64'h0)
    | (muxState_1 ? auto_out_1_d_bits_data : 64'h0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :230:18, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_in_d_bits_corrupt =
    muxState_0 & auto_out_0_d_bits_corrupt | muxState_1 & auto_out_1_d_bits_corrupt;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:89:25, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, src/main/scala/chisel3/util/Mux.scala:30:73
  assign auto_out_1_a_valid = auto_in_a_valid & auto_in_a_bits_address[31];	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46}, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :352:40
  assign auto_out_1_a_bits_opcode = auto_in_a_bits_opcode;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_param = auto_in_a_bits_param;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_size = auto_in_a_bits_size;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_source = auto_in_a_bits_source;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_address = auto_in_a_bits_address;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_mask = auto_in_a_bits_mask;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_a_bits_data = auto_in_a_bits_data;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_b_ready = auto_in_b_ready;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_valid = auto_in_c_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_opcode = auto_in_c_bits_opcode;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_param = auto_in_c_bits_param;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_size = auto_in_c_bits_size;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_source = auto_in_c_bits_source;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_address = auto_in_c_bits_address;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_c_bits_data = auto_in_c_bits_data;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_d_ready = auto_in_d_ready & (idle ? readys_readys[1] : state_1);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:26:18, :61:28, :68:76, :88:26, :92:24, :94:31, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_e_valid = auto_in_e_valid;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_1_e_bits_sink = auto_in_e_bits_sink;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_valid = auto_in_a_valid & ~(auto_in_a_bits_address[31]);	// home/xyl/exp/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :352:40
  assign auto_out_0_a_bits_opcode = auto_in_a_bits_opcode;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_param = auto_in_a_bits_param;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_size = auto_in_a_bits_size;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_source = auto_in_a_bits_source;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_address = auto_in_a_bits_address[28:0];	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9, :218:41
  assign auto_out_0_a_bits_mask = auto_in_a_bits_mask;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_data = auto_in_a_bits_data;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_a_bits_corrupt = auto_in_a_bits_corrupt;	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
  assign auto_out_0_d_ready = auto_in_d_ready & (idle ? readys_readys[0] : state_0);	// home/xyl/exp/rocket-chip/src/main/scala/tilelink/Arbiter.scala:26:18, :61:28, :68:76, :88:26, :92:24, :94:31, home/xyl/exp/rocket-chip/src/main/scala/tilelink/Xbar.scala:71:9
endmodule

