// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BusPerfMonitor(
  input          clock,
  input          reset,
  output         auto_in_a_ready,
  input          auto_in_a_valid,
  input  [3:0]   auto_in_a_bits_opcode,
  input  [2:0]   auto_in_a_bits_param,
  input  [2:0]   auto_in_a_bits_size,
  input  [5:0]   auto_in_a_bits_source,
  input  [47:0]  auto_in_a_bits_address,
  input  [3:0]   auto_in_a_bits_user_reqSource,
  input  [31:0]  auto_in_a_bits_mask,
  input  [255:0] auto_in_a_bits_data,
  input          auto_in_a_bits_corrupt,
  output         auto_in_c_ready,
  input          auto_in_c_valid,
  input  [2:0]   auto_in_c_bits_opcode,
  input  [2:0]   auto_in_c_bits_size,
  input  [5:0]   auto_in_c_bits_source,
  input  [47:0]  auto_in_c_bits_address,
  input  [3:0]   auto_in_c_bits_user_reqSource,
  input  [255:0] auto_in_c_bits_data,
  input          auto_in_c_bits_corrupt,
  input          auto_in_d_ready,
  output         auto_in_d_valid,
  output [3:0]   auto_in_d_bits_opcode,
  output [1:0]   auto_in_d_bits_param,
  output [2:0]   auto_in_d_bits_size,
  output [5:0]   auto_in_d_bits_source,
  output [2:0]   auto_in_d_bits_sink,
  output         auto_in_d_bits_denied,
  output [255:0] auto_in_d_bits_data,
  output         auto_in_d_bits_corrupt,
  input          auto_in_e_valid,
  input  [2:0]   auto_in_e_bits_sink,
  input          auto_out_a_ready,
  output         auto_out_a_valid,
  output [3:0]   auto_out_a_bits_opcode,
  output [2:0]   auto_out_a_bits_param,
  output [2:0]   auto_out_a_bits_size,
  output [5:0]   auto_out_a_bits_source,
  output [47:0]  auto_out_a_bits_address,
  output [3:0]   auto_out_a_bits_user_reqSource,
  output [31:0]  auto_out_a_bits_mask,
  output [255:0] auto_out_a_bits_data,
  output         auto_out_a_bits_corrupt,
  input          auto_out_c_ready,
  output         auto_out_c_valid,
  output [2:0]   auto_out_c_bits_opcode,
  output [2:0]   auto_out_c_bits_size,
  output [5:0]   auto_out_c_bits_source,
  output [47:0]  auto_out_c_bits_address,
  output [3:0]   auto_out_c_bits_user_reqSource,
  output [255:0] auto_out_c_bits_data,
  output         auto_out_c_bits_corrupt,
  output         auto_out_d_ready,
  input          auto_out_d_valid,
  input  [3:0]   auto_out_d_bits_opcode,
  input  [1:0]   auto_out_d_bits_param,
  input  [2:0]   auto_out_d_bits_size,
  input  [5:0]   auto_out_d_bits_source,
  input  [2:0]   auto_out_d_bits_sink,
  input          auto_out_d_bits_denied,
  input  [255:0] auto_out_d_bits_data,
  input          auto_out_d_bits_corrupt,
  output         auto_out_e_valid,
  output [2:0]   auto_out_e_bits_sink
);

  wire              auto_in_e_valid_probe = auto_in_e_valid;
  wire              _GEN = auto_out_a_ready & auto_in_a_valid;
  wire              _GEN_0 = auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_1 = ~(|auto_in_a_bits_opcode) & _GEN;
  wire              _GEN_2 =
    ~(|auto_in_a_bits_opcode) & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_3 = auto_in_a_bits_opcode == 4'h1;
  wire              _GEN_4 = _GEN_3 & _GEN;
  wire              _GEN_5 = _GEN_3 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_6 = auto_in_a_bits_opcode == 4'h2;
  wire              _GEN_7 = _GEN_6 & _GEN;
  wire              _GEN_8 = _GEN_6 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_9 = auto_in_a_bits_opcode == 4'h3;
  wire              _GEN_10 = _GEN_9 & _GEN;
  wire              _GEN_11 = _GEN_9 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_12 = auto_in_a_bits_opcode == 4'h4;
  wire              _GEN_13 = _GEN_12 & _GEN;
  wire              _GEN_14 = _GEN_12 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_15 = auto_in_a_bits_opcode == 4'h5;
  wire              _GEN_16 = _GEN_15 & _GEN;
  wire              _GEN_17 = _GEN_15 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_18 = auto_in_a_bits_opcode == 4'h6;
  wire              _GEN_19 = _GEN_18 & _GEN;
  wire              _GEN_20 = _GEN_18 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_21 = auto_in_a_bits_opcode == 4'h7;
  wire              _GEN_22 = _GEN_21 & _GEN;
  wire              _GEN_23 = _GEN_21 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_24 = auto_in_a_bits_opcode == 4'h8;
  wire              _GEN_25 = _GEN_24 & _GEN;
  wire              _GEN_26 = _GEN_24 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_27 = auto_in_a_bits_opcode == 4'h9;
  wire              _GEN_28 = _GEN_27 & _GEN;
  wire              _GEN_29 = _GEN_27 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _GEN_30 = auto_in_a_bits_opcode == 4'hA;
  wire              _GEN_31 = _GEN_30 & _GEN;
  wire              _GEN_32 = _GEN_30 & auto_in_a_valid & ~auto_out_a_ready;
  wire              _resolveRecord_T_probe = auto_in_d_ready & auto_out_d_valid;
  wire              _GEN_33 = auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_34 = auto_out_d_bits_opcode == 4'h0;
  wire              _GEN_35 = _GEN_34 & _resolveRecord_T_probe;
  wire              _GEN_36 = _GEN_34 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_37 = auto_out_d_bits_opcode == 4'h1;
  wire              _GEN_38 = _GEN_37 & _resolveRecord_T_probe;
  wire              _GEN_39 = _GEN_37 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_40 = auto_out_d_bits_opcode == 4'h2;
  wire              _GEN_41 = _GEN_40 & _resolveRecord_T_probe;
  wire              _GEN_42 = _GEN_40 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_43 = auto_out_d_bits_opcode == 4'h3;
  wire              _GEN_44 = _GEN_43 & _resolveRecord_T_probe;
  wire              _GEN_45 = _GEN_43 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_46 = auto_out_d_bits_opcode == 4'h4;
  wire              _GEN_47 = _GEN_46 & _resolveRecord_T_probe;
  wire              _GEN_48 = _GEN_46 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_49 = auto_out_d_bits_opcode == 4'h5;
  wire              _GEN_50 = _GEN_49 & _resolveRecord_T_probe;
  wire              _GEN_51 = _GEN_49 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_52 = auto_out_d_bits_opcode == 4'h6;
  wire              _GEN_53 = _GEN_52 & _resolveRecord_T_probe;
  wire              _GEN_54 = _GEN_52 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_55 = auto_out_d_bits_opcode == 4'h7;
  wire              _GEN_56 = _GEN_55 & _resolveRecord_T_probe;
  wire              _GEN_57 = _GEN_55 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_58 = auto_out_d_bits_opcode == 4'h8;
  wire              _GEN_59 = _GEN_58 & _resolveRecord_T_probe;
  wire              _GEN_60 = _GEN_58 & auto_out_d_valid & ~auto_in_d_ready;
  wire              _GEN_61 = auto_out_c_ready & auto_in_c_valid;
  wire              _GEN_62 = auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_63 = auto_in_c_bits_opcode == 3'h0;
  wire              _GEN_64 = _GEN_63 & _GEN_61;
  wire              _GEN_65 = _GEN_63 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_66 = auto_in_c_bits_opcode == 3'h1;
  wire              _GEN_67 = _GEN_66 & _GEN_61;
  wire              _GEN_68 = _GEN_66 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_69 = auto_in_c_bits_opcode == 3'h2;
  wire              _GEN_70 = _GEN_69 & _GEN_61;
  wire              _GEN_71 = _GEN_69 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_72 = auto_in_c_bits_opcode == 3'h3;
  wire              _GEN_73 = _GEN_72 & _GEN_61;
  wire              _GEN_74 = _GEN_72 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_75 = auto_in_c_bits_opcode == 3'h4;
  wire              _GEN_76 = _GEN_75 & _GEN_61;
  wire              _GEN_77 = _GEN_75 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_78 = auto_in_c_bits_opcode == 3'h5;
  wire              _GEN_79 = _GEN_78 & _GEN_61;
  wire              _GEN_80 = _GEN_78 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_81 = auto_in_c_bits_opcode == 3'h6;
  wire              _GEN_82 = _GEN_81 & _GEN_61;
  wire              _GEN_83 = _GEN_81 & auto_in_c_valid & ~auto_out_c_ready;
  wire              _GEN_84 = (&auto_in_c_bits_opcode) & _GEN_61;
  wire              _GEN_85 =
    (&auto_in_c_bits_opcode) & auto_in_c_valid & ~auto_out_c_ready;
  reg  [63:0]       timer;
  reg               latencyRecord_0_valid;
  reg  [63:0]       latencyRecord_0_timeStamp;
  reg  [7:0]        latencyRecord_0_reqType;
  reg               latencyRecord_1_valid;
  reg  [63:0]       latencyRecord_1_timeStamp;
  reg  [7:0]        latencyRecord_1_reqType;
  reg               latencyRecord_2_valid;
  reg  [63:0]       latencyRecord_2_timeStamp;
  reg  [7:0]        latencyRecord_2_reqType;
  reg               latencyRecord_3_valid;
  reg  [63:0]       latencyRecord_3_timeStamp;
  reg  [7:0]        latencyRecord_3_reqType;
  reg               latencyRecord_4_valid;
  reg  [63:0]       latencyRecord_4_timeStamp;
  reg  [7:0]        latencyRecord_4_reqType;
  reg               latencyRecord_5_valid;
  reg  [63:0]       latencyRecord_5_timeStamp;
  reg  [7:0]        latencyRecord_5_reqType;
  reg               latencyRecord_6_valid;
  reg  [63:0]       latencyRecord_6_timeStamp;
  reg  [7:0]        latencyRecord_6_reqType;
  reg               latencyRecord_7_valid;
  reg  [63:0]       latencyRecord_7_timeStamp;
  reg  [7:0]        latencyRecord_7_reqType;
  reg               latencyRecord_8_valid;
  reg  [63:0]       latencyRecord_8_timeStamp;
  reg  [7:0]        latencyRecord_8_reqType;
  reg               latencyRecord_9_valid;
  reg  [63:0]       latencyRecord_9_timeStamp;
  reg  [7:0]        latencyRecord_9_reqType;
  reg               latencyRecord_10_valid;
  reg  [63:0]       latencyRecord_10_timeStamp;
  reg  [7:0]        latencyRecord_10_reqType;
  reg               latencyRecord_11_valid;
  reg  [63:0]       latencyRecord_11_timeStamp;
  reg  [7:0]        latencyRecord_11_reqType;
  reg               latencyRecord_12_valid;
  reg  [63:0]       latencyRecord_12_timeStamp;
  reg  [7:0]        latencyRecord_12_reqType;
  reg               latencyRecord_13_valid;
  reg  [63:0]       latencyRecord_13_timeStamp;
  reg  [7:0]        latencyRecord_13_reqType;
  reg               latencyRecord_14_valid;
  reg  [63:0]       latencyRecord_14_timeStamp;
  reg  [7:0]        latencyRecord_14_reqType;
  reg               latencyRecord_15_valid;
  reg  [63:0]       latencyRecord_15_timeStamp;
  reg  [7:0]        latencyRecord_15_reqType;
  reg               latencyRecord_16_valid;
  reg  [63:0]       latencyRecord_16_timeStamp;
  reg  [7:0]        latencyRecord_16_reqType;
  reg               latencyRecord_17_valid;
  reg  [63:0]       latencyRecord_17_timeStamp;
  reg  [7:0]        latencyRecord_17_reqType;
  reg               latencyRecord_18_valid;
  reg  [63:0]       latencyRecord_18_timeStamp;
  reg  [7:0]        latencyRecord_18_reqType;
  reg               latencyRecord_19_valid;
  reg  [63:0]       latencyRecord_19_timeStamp;
  reg  [7:0]        latencyRecord_19_reqType;
  reg               latencyRecord_20_valid;
  reg  [63:0]       latencyRecord_20_timeStamp;
  reg  [7:0]        latencyRecord_20_reqType;
  reg               latencyRecord_21_valid;
  reg  [63:0]       latencyRecord_21_timeStamp;
  reg  [7:0]        latencyRecord_21_reqType;
  reg               latencyRecord_22_valid;
  reg  [63:0]       latencyRecord_22_timeStamp;
  reg  [7:0]        latencyRecord_22_reqType;
  reg               latencyRecord_23_valid;
  reg  [63:0]       latencyRecord_23_timeStamp;
  reg  [7:0]        latencyRecord_23_reqType;
  reg               latencyRecord_24_valid;
  reg  [63:0]       latencyRecord_24_timeStamp;
  reg  [7:0]        latencyRecord_24_reqType;
  reg               latencyRecord_25_valid;
  reg  [63:0]       latencyRecord_25_timeStamp;
  reg  [7:0]        latencyRecord_25_reqType;
  reg               latencyRecord_26_valid;
  reg  [63:0]       latencyRecord_26_timeStamp;
  reg  [7:0]        latencyRecord_26_reqType;
  reg               latencyRecord_27_valid;
  reg  [63:0]       latencyRecord_27_timeStamp;
  reg  [7:0]        latencyRecord_27_reqType;
  reg               latencyRecord_28_valid;
  reg  [63:0]       latencyRecord_28_timeStamp;
  reg  [7:0]        latencyRecord_28_reqType;
  reg               latencyRecord_29_valid;
  reg  [63:0]       latencyRecord_29_timeStamp;
  reg  [7:0]        latencyRecord_29_reqType;
  reg               latencyRecord_30_valid;
  reg  [63:0]       latencyRecord_30_timeStamp;
  reg  [7:0]        latencyRecord_30_reqType;
  reg               latencyRecord_31_valid;
  reg  [63:0]       latencyRecord_31_timeStamp;
  reg  [7:0]        latencyRecord_31_reqType;
  reg               latencyRecord_32_valid;
  reg  [63:0]       latencyRecord_32_timeStamp;
  reg  [7:0]        latencyRecord_32_reqType;
  reg               latencyRecord_33_valid;
  reg  [63:0]       latencyRecord_33_timeStamp;
  reg  [7:0]        latencyRecord_33_reqType;
  reg               latencyRecord_34_valid;
  reg  [63:0]       latencyRecord_34_timeStamp;
  reg  [7:0]        latencyRecord_34_reqType;
  reg               latencyRecord_35_valid;
  reg  [63:0]       latencyRecord_35_timeStamp;
  reg  [7:0]        latencyRecord_35_reqType;
  reg               latencyRecord_36_valid;
  reg  [63:0]       latencyRecord_36_timeStamp;
  reg  [7:0]        latencyRecord_36_reqType;
  reg               latencyRecord_37_valid;
  reg  [63:0]       latencyRecord_37_timeStamp;
  reg  [7:0]        latencyRecord_37_reqType;
  reg               latencyRecord_38_valid;
  reg  [63:0]       latencyRecord_38_timeStamp;
  reg  [7:0]        latencyRecord_38_reqType;
  reg               latencyRecord_39_valid;
  reg  [63:0]       latencyRecord_39_timeStamp;
  reg  [7:0]        latencyRecord_39_reqType;
  reg               latencyRecord_40_valid;
  reg  [63:0]       latencyRecord_40_timeStamp;
  reg  [7:0]        latencyRecord_40_reqType;
  reg               latencyRecord_41_valid;
  reg  [63:0]       latencyRecord_41_timeStamp;
  reg  [7:0]        latencyRecord_41_reqType;
  reg               latencyRecord_42_valid;
  reg  [63:0]       latencyRecord_42_timeStamp;
  reg  [7:0]        latencyRecord_42_reqType;
  reg               latencyRecord_43_valid;
  reg  [63:0]       latencyRecord_43_timeStamp;
  reg  [7:0]        latencyRecord_43_reqType;
  reg               latencyRecord_44_valid;
  reg  [63:0]       latencyRecord_44_timeStamp;
  reg  [7:0]        latencyRecord_44_reqType;
  reg               latencyRecord_45_valid;
  reg  [63:0]       latencyRecord_45_timeStamp;
  reg  [7:0]        latencyRecord_45_reqType;
  reg               latencyRecord_46_valid;
  reg  [63:0]       latencyRecord_46_timeStamp;
  reg  [7:0]        latencyRecord_46_reqType;
  reg               latencyRecord_47_valid;
  reg  [63:0]       latencyRecord_47_timeStamp;
  reg  [7:0]        latencyRecord_47_reqType;
  reg               latencyRecord_48_valid;
  reg  [63:0]       latencyRecord_48_timeStamp;
  reg  [7:0]        latencyRecord_48_reqType;
  reg               latencyRecord_49_valid;
  reg  [63:0]       latencyRecord_49_timeStamp;
  reg  [7:0]        latencyRecord_49_reqType;
  reg               latencyRecord_50_valid;
  reg  [63:0]       latencyRecord_50_timeStamp;
  reg  [7:0]        latencyRecord_50_reqType;
  reg               latencyRecord_51_valid;
  reg  [63:0]       latencyRecord_51_timeStamp;
  reg  [7:0]        latencyRecord_51_reqType;
  reg               latencyRecord_52_valid;
  reg  [63:0]       latencyRecord_52_timeStamp;
  reg  [7:0]        latencyRecord_52_reqType;
  reg               latencyRecord_53_valid;
  reg  [63:0]       latencyRecord_53_timeStamp;
  reg  [7:0]        latencyRecord_53_reqType;
  reg               latencyRecord_54_valid;
  reg  [63:0]       latencyRecord_54_timeStamp;
  reg  [7:0]        latencyRecord_54_reqType;
  reg               latencyRecord_55_valid;
  reg  [63:0]       latencyRecord_55_timeStamp;
  reg  [7:0]        latencyRecord_55_reqType;
  reg               latencyRecord_56_valid;
  reg  [63:0]       latencyRecord_56_timeStamp;
  reg  [7:0]        latencyRecord_56_reqType;
  reg               latencyRecord_57_valid;
  reg  [63:0]       latencyRecord_57_timeStamp;
  reg  [7:0]        latencyRecord_57_reqType;
  reg               latencyRecord_58_valid;
  reg  [63:0]       latencyRecord_58_timeStamp;
  reg  [7:0]        latencyRecord_58_reqType;
  reg               latencyRecord_59_valid;
  reg  [63:0]       latencyRecord_59_timeStamp;
  reg  [7:0]        latencyRecord_59_reqType;
  reg               latencyRecord_60_valid;
  reg  [63:0]       latencyRecord_60_timeStamp;
  reg  [7:0]        latencyRecord_60_reqType;
  reg               latencyRecord_61_valid;
  reg  [63:0]       latencyRecord_61_timeStamp;
  reg  [7:0]        latencyRecord_61_reqType;
  reg               latencyRecord_62_valid;
  reg  [63:0]       latencyRecord_62_timeStamp;
  reg  [7:0]        latencyRecord_62_reqType;
  reg               latencyRecord_63_valid;
  reg  [63:0]       latencyRecord_63_timeStamp;
  reg  [7:0]        latencyRecord_63_reqType;
  wire              _GEN_86 =
    _GEN & auto_in_a_bits_opcode != 4'h5 & (|auto_in_a_bits_opcode)
    & auto_in_a_bits_opcode != 4'h1;
  reg               first_r_counter;
  wire              resolveRecord_probe =
    _resolveRecord_T_probe & ~first_r_counter & auto_out_d_bits_opcode != 4'h6
    & (|auto_out_d_bits_opcode);
  wire [63:0][63:0] _GEN_87 =
    {{latencyRecord_63_timeStamp},
     {latencyRecord_62_timeStamp},
     {latencyRecord_61_timeStamp},
     {latencyRecord_60_timeStamp},
     {latencyRecord_59_timeStamp},
     {latencyRecord_58_timeStamp},
     {latencyRecord_57_timeStamp},
     {latencyRecord_56_timeStamp},
     {latencyRecord_55_timeStamp},
     {latencyRecord_54_timeStamp},
     {latencyRecord_53_timeStamp},
     {latencyRecord_52_timeStamp},
     {latencyRecord_51_timeStamp},
     {latencyRecord_50_timeStamp},
     {latencyRecord_49_timeStamp},
     {latencyRecord_48_timeStamp},
     {latencyRecord_47_timeStamp},
     {latencyRecord_46_timeStamp},
     {latencyRecord_45_timeStamp},
     {latencyRecord_44_timeStamp},
     {latencyRecord_43_timeStamp},
     {latencyRecord_42_timeStamp},
     {latencyRecord_41_timeStamp},
     {latencyRecord_40_timeStamp},
     {latencyRecord_39_timeStamp},
     {latencyRecord_38_timeStamp},
     {latencyRecord_37_timeStamp},
     {latencyRecord_36_timeStamp},
     {latencyRecord_35_timeStamp},
     {latencyRecord_34_timeStamp},
     {latencyRecord_33_timeStamp},
     {latencyRecord_32_timeStamp},
     {latencyRecord_31_timeStamp},
     {latencyRecord_30_timeStamp},
     {latencyRecord_29_timeStamp},
     {latencyRecord_28_timeStamp},
     {latencyRecord_27_timeStamp},
     {latencyRecord_26_timeStamp},
     {latencyRecord_25_timeStamp},
     {latencyRecord_24_timeStamp},
     {latencyRecord_23_timeStamp},
     {latencyRecord_22_timeStamp},
     {latencyRecord_21_timeStamp},
     {latencyRecord_20_timeStamp},
     {latencyRecord_19_timeStamp},
     {latencyRecord_18_timeStamp},
     {latencyRecord_17_timeStamp},
     {latencyRecord_16_timeStamp},
     {latencyRecord_15_timeStamp},
     {latencyRecord_14_timeStamp},
     {latencyRecord_13_timeStamp},
     {latencyRecord_12_timeStamp},
     {latencyRecord_11_timeStamp},
     {latencyRecord_10_timeStamp},
     {latencyRecord_9_timeStamp},
     {latencyRecord_8_timeStamp},
     {latencyRecord_7_timeStamp},
     {latencyRecord_6_timeStamp},
     {latencyRecord_5_timeStamp},
     {latencyRecord_4_timeStamp},
     {latencyRecord_3_timeStamp},
     {latencyRecord_2_timeStamp},
     {latencyRecord_1_timeStamp},
     {latencyRecord_0_timeStamp}};
  `ifndef SYNTHESIS
    wire [63:0] _GEN_88 =
      {{latencyRecord_63_valid},
       {latencyRecord_62_valid},
       {latencyRecord_61_valid},
       {latencyRecord_60_valid},
       {latencyRecord_59_valid},
       {latencyRecord_58_valid},
       {latencyRecord_57_valid},
       {latencyRecord_56_valid},
       {latencyRecord_55_valid},
       {latencyRecord_54_valid},
       {latencyRecord_53_valid},
       {latencyRecord_52_valid},
       {latencyRecord_51_valid},
       {latencyRecord_50_valid},
       {latencyRecord_49_valid},
       {latencyRecord_48_valid},
       {latencyRecord_47_valid},
       {latencyRecord_46_valid},
       {latencyRecord_45_valid},
       {latencyRecord_44_valid},
       {latencyRecord_43_valid},
       {latencyRecord_42_valid},
       {latencyRecord_41_valid},
       {latencyRecord_40_valid},
       {latencyRecord_39_valid},
       {latencyRecord_38_valid},
       {latencyRecord_37_valid},
       {latencyRecord_36_valid},
       {latencyRecord_35_valid},
       {latencyRecord_34_valid},
       {latencyRecord_33_valid},
       {latencyRecord_32_valid},
       {latencyRecord_31_valid},
       {latencyRecord_30_valid},
       {latencyRecord_29_valid},
       {latencyRecord_28_valid},
       {latencyRecord_27_valid},
       {latencyRecord_26_valid},
       {latencyRecord_25_valid},
       {latencyRecord_24_valid},
       {latencyRecord_23_valid},
       {latencyRecord_22_valid},
       {latencyRecord_21_valid},
       {latencyRecord_20_valid},
       {latencyRecord_19_valid},
       {latencyRecord_18_valid},
       {latencyRecord_17_valid},
       {latencyRecord_16_valid},
       {latencyRecord_15_valid},
       {latencyRecord_14_valid},
       {latencyRecord_13_valid},
       {latencyRecord_12_valid},
       {latencyRecord_11_valid},
       {latencyRecord_10_valid},
       {latencyRecord_9_valid},
       {latencyRecord_8_valid},
       {latencyRecord_7_valid},
       {latencyRecord_6_valid},
       {latencyRecord_5_valid},
       {latencyRecord_4_valid},
       {latencyRecord_3_valid},
       {latencyRecord_2_valid},
       {latencyRecord_1_valid},
       {latencyRecord_0_valid}};
    always @(posedge clock) begin
      if (_GEN_86 & ~reset & _GEN_88[auto_in_a_bits_source]) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed\n    at BusPerfMonitor.scala:132 assert(latencyRecord(channelA.bits.source).valid === false.B)\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (resolveRecord_probe & ~reset & ~_GEN_88[auto_out_d_bits_source]) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed\n    at BusPerfMonitor.scala:145 assert(latencyRecord(channelD.bits.source).valid === true.B)\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [63:0]       _latency_T = 64'(timer - _GEN_87[auto_out_d_bits_source]);
  wire [63:0]       _GEN_89 = resolveRecord_probe ? _latency_T : 64'h0;
  wire [63:0][7:0]  _GEN_90 =
    {{latencyRecord_63_reqType},
     {latencyRecord_62_reqType},
     {latencyRecord_61_reqType},
     {latencyRecord_60_reqType},
     {latencyRecord_59_reqType},
     {latencyRecord_58_reqType},
     {latencyRecord_57_reqType},
     {latencyRecord_56_reqType},
     {latencyRecord_55_reqType},
     {latencyRecord_54_reqType},
     {latencyRecord_53_reqType},
     {latencyRecord_52_reqType},
     {latencyRecord_51_reqType},
     {latencyRecord_50_reqType},
     {latencyRecord_49_reqType},
     {latencyRecord_48_reqType},
     {latencyRecord_47_reqType},
     {latencyRecord_46_reqType},
     {latencyRecord_45_reqType},
     {latencyRecord_44_reqType},
     {latencyRecord_43_reqType},
     {latencyRecord_42_reqType},
     {latencyRecord_41_reqType},
     {latencyRecord_40_reqType},
     {latencyRecord_39_reqType},
     {latencyRecord_38_reqType},
     {latencyRecord_37_reqType},
     {latencyRecord_36_reqType},
     {latencyRecord_35_reqType},
     {latencyRecord_34_reqType},
     {latencyRecord_33_reqType},
     {latencyRecord_32_reqType},
     {latencyRecord_31_reqType},
     {latencyRecord_30_reqType},
     {latencyRecord_29_reqType},
     {latencyRecord_28_reqType},
     {latencyRecord_27_reqType},
     {latencyRecord_26_reqType},
     {latencyRecord_25_reqType},
     {latencyRecord_24_reqType},
     {latencyRecord_23_reqType},
     {latencyRecord_22_reqType},
     {latencyRecord_21_reqType},
     {latencyRecord_20_reqType},
     {latencyRecord_19_reqType},
     {latencyRecord_18_reqType},
     {latencyRecord_17_reqType},
     {latencyRecord_16_reqType},
     {latencyRecord_15_reqType},
     {latencyRecord_14_reqType},
     {latencyRecord_13_reqType},
     {latencyRecord_12_reqType},
     {latencyRecord_11_reqType},
     {latencyRecord_10_reqType},
     {latencyRecord_9_reqType},
     {latencyRecord_8_reqType},
     {latencyRecord_7_reqType},
     {latencyRecord_6_reqType},
     {latencyRecord_5_reqType},
     {latencyRecord_4_reqType},
     {latencyRecord_3_reqType},
     {latencyRecord_2_reqType},
     {latencyRecord_1_reqType},
     {latencyRecord_0_reqType}};
  wire              _GEN_91 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h0;
  wire [63:0]       _GEN_92 = _GEN_91 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_93 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h1;
  wire [63:0]       _GEN_94 = _GEN_93 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_95 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h2;
  wire [63:0]       _GEN_96 = _GEN_95 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_97 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h3;
  wire [63:0]       _GEN_98 = _GEN_97 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_99 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h4;
  wire [63:0]       _GEN_100 = _GEN_99 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_101 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h5;
  wire [63:0]       _GEN_102 = _GEN_101 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_103 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h6;
  wire [63:0]       _GEN_104 = _GEN_103 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_105 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h7;
  wire [63:0]       _GEN_106 = _GEN_105 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_107 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h8;
  wire [63:0]       _GEN_108 = _GEN_107 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_109 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'h9;
  wire [63:0]       _GEN_110 = _GEN_109 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_111 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hA;
  wire [63:0]       _GEN_112 = _GEN_111 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_113 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hB;
  wire [63:0]       _GEN_114 = _GEN_113 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_115 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hC;
  wire [63:0]       _GEN_116 = _GEN_115 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_117 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hD;
  wire [63:0]       _GEN_118 = _GEN_117 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_119 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hE;
  wire [63:0]       _GEN_120 = _GEN_119 & resolveRecord_probe ? _latency_T : 64'h0;
  wire              _GEN_121 =
    resolveRecord_probe & _GEN_90[auto_out_d_bits_source] == 8'hF;
  wire [63:0]       _GEN_122 = _GEN_121 & resolveRecord_probe ? _latency_T : 64'h0;
  wire [12:0]       _first_r_beats1_decode_T = 13'h3F << auto_out_d_bits_size;
  wire              _GEN_123 = _GEN_86 & auto_in_a_bits_source == 6'h0;
  wire              _GEN_124 = _GEN_86 & auto_in_a_bits_source == 6'h1;
  wire              _GEN_125 = _GEN_86 & auto_in_a_bits_source == 6'h2;
  wire              _GEN_126 = _GEN_86 & auto_in_a_bits_source == 6'h3;
  wire              _GEN_127 = _GEN_86 & auto_in_a_bits_source == 6'h4;
  wire              _GEN_128 = _GEN_86 & auto_in_a_bits_source == 6'h5;
  wire              _GEN_129 = _GEN_86 & auto_in_a_bits_source == 6'h6;
  wire              _GEN_130 = _GEN_86 & auto_in_a_bits_source == 6'h7;
  wire              _GEN_131 = _GEN_86 & auto_in_a_bits_source == 6'h8;
  wire              _GEN_132 = _GEN_86 & auto_in_a_bits_source == 6'h9;
  wire              _GEN_133 = _GEN_86 & auto_in_a_bits_source == 6'hA;
  wire              _GEN_134 = _GEN_86 & auto_in_a_bits_source == 6'hB;
  wire              _GEN_135 = _GEN_86 & auto_in_a_bits_source == 6'hC;
  wire              _GEN_136 = _GEN_86 & auto_in_a_bits_source == 6'hD;
  wire              _GEN_137 = _GEN_86 & auto_in_a_bits_source == 6'hE;
  wire              _GEN_138 = _GEN_86 & auto_in_a_bits_source == 6'hF;
  wire              _GEN_139 = _GEN_86 & auto_in_a_bits_source == 6'h10;
  wire              _GEN_140 = _GEN_86 & auto_in_a_bits_source == 6'h11;
  wire              _GEN_141 = _GEN_86 & auto_in_a_bits_source == 6'h12;
  wire              _GEN_142 = _GEN_86 & auto_in_a_bits_source == 6'h13;
  wire              _GEN_143 = _GEN_86 & auto_in_a_bits_source == 6'h14;
  wire              _GEN_144 = _GEN_86 & auto_in_a_bits_source == 6'h15;
  wire              _GEN_145 = _GEN_86 & auto_in_a_bits_source == 6'h16;
  wire              _GEN_146 = _GEN_86 & auto_in_a_bits_source == 6'h17;
  wire              _GEN_147 = _GEN_86 & auto_in_a_bits_source == 6'h18;
  wire              _GEN_148 = _GEN_86 & auto_in_a_bits_source == 6'h19;
  wire              _GEN_149 = _GEN_86 & auto_in_a_bits_source == 6'h1A;
  wire              _GEN_150 = _GEN_86 & auto_in_a_bits_source == 6'h1B;
  wire              _GEN_151 = _GEN_86 & auto_in_a_bits_source == 6'h1C;
  wire              _GEN_152 = _GEN_86 & auto_in_a_bits_source == 6'h1D;
  wire              _GEN_153 = _GEN_86 & auto_in_a_bits_source == 6'h1E;
  wire              _GEN_154 = _GEN_86 & auto_in_a_bits_source == 6'h1F;
  wire              _GEN_155 = _GEN_86 & auto_in_a_bits_source == 6'h20;
  wire              _GEN_156 = _GEN_86 & auto_in_a_bits_source == 6'h21;
  wire              _GEN_157 = _GEN_86 & auto_in_a_bits_source == 6'h22;
  wire              _GEN_158 = _GEN_86 & auto_in_a_bits_source == 6'h23;
  wire              _GEN_159 = _GEN_86 & auto_in_a_bits_source == 6'h24;
  wire              _GEN_160 = _GEN_86 & auto_in_a_bits_source == 6'h25;
  wire              _GEN_161 = _GEN_86 & auto_in_a_bits_source == 6'h26;
  wire              _GEN_162 = _GEN_86 & auto_in_a_bits_source == 6'h27;
  wire              _GEN_163 = _GEN_86 & auto_in_a_bits_source == 6'h28;
  wire              _GEN_164 = _GEN_86 & auto_in_a_bits_source == 6'h29;
  wire              _GEN_165 = _GEN_86 & auto_in_a_bits_source == 6'h2A;
  wire              _GEN_166 = _GEN_86 & auto_in_a_bits_source == 6'h2B;
  wire              _GEN_167 = _GEN_86 & auto_in_a_bits_source == 6'h2C;
  wire              _GEN_168 = _GEN_86 & auto_in_a_bits_source == 6'h2D;
  wire              _GEN_169 = _GEN_86 & auto_in_a_bits_source == 6'h2E;
  wire              _GEN_170 = _GEN_86 & auto_in_a_bits_source == 6'h2F;
  wire              _GEN_171 = _GEN_86 & auto_in_a_bits_source == 6'h30;
  wire              _GEN_172 = _GEN_86 & auto_in_a_bits_source == 6'h31;
  wire              _GEN_173 = _GEN_86 & auto_in_a_bits_source == 6'h32;
  wire              _GEN_174 = _GEN_86 & auto_in_a_bits_source == 6'h33;
  wire              _GEN_175 = _GEN_86 & auto_in_a_bits_source == 6'h34;
  wire              _GEN_176 = _GEN_86 & auto_in_a_bits_source == 6'h35;
  wire              _GEN_177 = _GEN_86 & auto_in_a_bits_source == 6'h36;
  wire              _GEN_178 = _GEN_86 & auto_in_a_bits_source == 6'h37;
  wire              _GEN_179 = _GEN_86 & auto_in_a_bits_source == 6'h38;
  wire              _GEN_180 = _GEN_86 & auto_in_a_bits_source == 6'h39;
  wire              _GEN_181 = _GEN_86 & auto_in_a_bits_source == 6'h3A;
  wire              _GEN_182 = _GEN_86 & auto_in_a_bits_source == 6'h3B;
  wire              _GEN_183 = _GEN_86 & auto_in_a_bits_source == 6'h3C;
  wire              _GEN_184 = _GEN_86 & auto_in_a_bits_source == 6'h3D;
  wire              _GEN_185 = _GEN_86 & auto_in_a_bits_source == 6'h3E;
  wire              _GEN_186 = _GEN_86 & (&auto_in_a_bits_source);
  wire [7:0]        _GEN_187 = {4'h0, auto_in_a_bits_user_reqSource};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      timer <= 64'h0;
      latencyRecord_0_valid <= 1'h0;
      latencyRecord_0_timeStamp <= 64'h0;
      latencyRecord_0_reqType <= 8'h0;
      latencyRecord_1_valid <= 1'h0;
      latencyRecord_1_timeStamp <= 64'h0;
      latencyRecord_1_reqType <= 8'h0;
      latencyRecord_2_valid <= 1'h0;
      latencyRecord_2_timeStamp <= 64'h0;
      latencyRecord_2_reqType <= 8'h0;
      latencyRecord_3_valid <= 1'h0;
      latencyRecord_3_timeStamp <= 64'h0;
      latencyRecord_3_reqType <= 8'h0;
      latencyRecord_4_valid <= 1'h0;
      latencyRecord_4_timeStamp <= 64'h0;
      latencyRecord_4_reqType <= 8'h0;
      latencyRecord_5_valid <= 1'h0;
      latencyRecord_5_timeStamp <= 64'h0;
      latencyRecord_5_reqType <= 8'h0;
      latencyRecord_6_valid <= 1'h0;
      latencyRecord_6_timeStamp <= 64'h0;
      latencyRecord_6_reqType <= 8'h0;
      latencyRecord_7_valid <= 1'h0;
      latencyRecord_7_timeStamp <= 64'h0;
      latencyRecord_7_reqType <= 8'h0;
      latencyRecord_8_valid <= 1'h0;
      latencyRecord_8_timeStamp <= 64'h0;
      latencyRecord_8_reqType <= 8'h0;
      latencyRecord_9_valid <= 1'h0;
      latencyRecord_9_timeStamp <= 64'h0;
      latencyRecord_9_reqType <= 8'h0;
      latencyRecord_10_valid <= 1'h0;
      latencyRecord_10_timeStamp <= 64'h0;
      latencyRecord_10_reqType <= 8'h0;
      latencyRecord_11_valid <= 1'h0;
      latencyRecord_11_timeStamp <= 64'h0;
      latencyRecord_11_reqType <= 8'h0;
      latencyRecord_12_valid <= 1'h0;
      latencyRecord_12_timeStamp <= 64'h0;
      latencyRecord_12_reqType <= 8'h0;
      latencyRecord_13_valid <= 1'h0;
      latencyRecord_13_timeStamp <= 64'h0;
      latencyRecord_13_reqType <= 8'h0;
      latencyRecord_14_valid <= 1'h0;
      latencyRecord_14_timeStamp <= 64'h0;
      latencyRecord_14_reqType <= 8'h0;
      latencyRecord_15_valid <= 1'h0;
      latencyRecord_15_timeStamp <= 64'h0;
      latencyRecord_15_reqType <= 8'h0;
      latencyRecord_16_valid <= 1'h0;
      latencyRecord_16_timeStamp <= 64'h0;
      latencyRecord_16_reqType <= 8'h0;
      latencyRecord_17_valid <= 1'h0;
      latencyRecord_17_timeStamp <= 64'h0;
      latencyRecord_17_reqType <= 8'h0;
      latencyRecord_18_valid <= 1'h0;
      latencyRecord_18_timeStamp <= 64'h0;
      latencyRecord_18_reqType <= 8'h0;
      latencyRecord_19_valid <= 1'h0;
      latencyRecord_19_timeStamp <= 64'h0;
      latencyRecord_19_reqType <= 8'h0;
      latencyRecord_20_valid <= 1'h0;
      latencyRecord_20_timeStamp <= 64'h0;
      latencyRecord_20_reqType <= 8'h0;
      latencyRecord_21_valid <= 1'h0;
      latencyRecord_21_timeStamp <= 64'h0;
      latencyRecord_21_reqType <= 8'h0;
      latencyRecord_22_valid <= 1'h0;
      latencyRecord_22_timeStamp <= 64'h0;
      latencyRecord_22_reqType <= 8'h0;
      latencyRecord_23_valid <= 1'h0;
      latencyRecord_23_timeStamp <= 64'h0;
      latencyRecord_23_reqType <= 8'h0;
      latencyRecord_24_valid <= 1'h0;
      latencyRecord_24_timeStamp <= 64'h0;
      latencyRecord_24_reqType <= 8'h0;
      latencyRecord_25_valid <= 1'h0;
      latencyRecord_25_timeStamp <= 64'h0;
      latencyRecord_25_reqType <= 8'h0;
      latencyRecord_26_valid <= 1'h0;
      latencyRecord_26_timeStamp <= 64'h0;
      latencyRecord_26_reqType <= 8'h0;
      latencyRecord_27_valid <= 1'h0;
      latencyRecord_27_timeStamp <= 64'h0;
      latencyRecord_27_reqType <= 8'h0;
      latencyRecord_28_valid <= 1'h0;
      latencyRecord_28_timeStamp <= 64'h0;
      latencyRecord_28_reqType <= 8'h0;
      latencyRecord_29_valid <= 1'h0;
      latencyRecord_29_timeStamp <= 64'h0;
      latencyRecord_29_reqType <= 8'h0;
      latencyRecord_30_valid <= 1'h0;
      latencyRecord_30_timeStamp <= 64'h0;
      latencyRecord_30_reqType <= 8'h0;
      latencyRecord_31_valid <= 1'h0;
      latencyRecord_31_timeStamp <= 64'h0;
      latencyRecord_31_reqType <= 8'h0;
      latencyRecord_32_valid <= 1'h0;
      latencyRecord_32_timeStamp <= 64'h0;
      latencyRecord_32_reqType <= 8'h0;
      latencyRecord_33_valid <= 1'h0;
      latencyRecord_33_timeStamp <= 64'h0;
      latencyRecord_33_reqType <= 8'h0;
      latencyRecord_34_valid <= 1'h0;
      latencyRecord_34_timeStamp <= 64'h0;
      latencyRecord_34_reqType <= 8'h0;
      latencyRecord_35_valid <= 1'h0;
      latencyRecord_35_timeStamp <= 64'h0;
      latencyRecord_35_reqType <= 8'h0;
      latencyRecord_36_valid <= 1'h0;
      latencyRecord_36_timeStamp <= 64'h0;
      latencyRecord_36_reqType <= 8'h0;
      latencyRecord_37_valid <= 1'h0;
      latencyRecord_37_timeStamp <= 64'h0;
      latencyRecord_37_reqType <= 8'h0;
      latencyRecord_38_valid <= 1'h0;
      latencyRecord_38_timeStamp <= 64'h0;
      latencyRecord_38_reqType <= 8'h0;
      latencyRecord_39_valid <= 1'h0;
      latencyRecord_39_timeStamp <= 64'h0;
      latencyRecord_39_reqType <= 8'h0;
      latencyRecord_40_valid <= 1'h0;
      latencyRecord_40_timeStamp <= 64'h0;
      latencyRecord_40_reqType <= 8'h0;
      latencyRecord_41_valid <= 1'h0;
      latencyRecord_41_timeStamp <= 64'h0;
      latencyRecord_41_reqType <= 8'h0;
      latencyRecord_42_valid <= 1'h0;
      latencyRecord_42_timeStamp <= 64'h0;
      latencyRecord_42_reqType <= 8'h0;
      latencyRecord_43_valid <= 1'h0;
      latencyRecord_43_timeStamp <= 64'h0;
      latencyRecord_43_reqType <= 8'h0;
      latencyRecord_44_valid <= 1'h0;
      latencyRecord_44_timeStamp <= 64'h0;
      latencyRecord_44_reqType <= 8'h0;
      latencyRecord_45_valid <= 1'h0;
      latencyRecord_45_timeStamp <= 64'h0;
      latencyRecord_45_reqType <= 8'h0;
      latencyRecord_46_valid <= 1'h0;
      latencyRecord_46_timeStamp <= 64'h0;
      latencyRecord_46_reqType <= 8'h0;
      latencyRecord_47_valid <= 1'h0;
      latencyRecord_47_timeStamp <= 64'h0;
      latencyRecord_47_reqType <= 8'h0;
      latencyRecord_48_valid <= 1'h0;
      latencyRecord_48_timeStamp <= 64'h0;
      latencyRecord_48_reqType <= 8'h0;
      latencyRecord_49_valid <= 1'h0;
      latencyRecord_49_timeStamp <= 64'h0;
      latencyRecord_49_reqType <= 8'h0;
      latencyRecord_50_valid <= 1'h0;
      latencyRecord_50_timeStamp <= 64'h0;
      latencyRecord_50_reqType <= 8'h0;
      latencyRecord_51_valid <= 1'h0;
      latencyRecord_51_timeStamp <= 64'h0;
      latencyRecord_51_reqType <= 8'h0;
      latencyRecord_52_valid <= 1'h0;
      latencyRecord_52_timeStamp <= 64'h0;
      latencyRecord_52_reqType <= 8'h0;
      latencyRecord_53_valid <= 1'h0;
      latencyRecord_53_timeStamp <= 64'h0;
      latencyRecord_53_reqType <= 8'h0;
      latencyRecord_54_valid <= 1'h0;
      latencyRecord_54_timeStamp <= 64'h0;
      latencyRecord_54_reqType <= 8'h0;
      latencyRecord_55_valid <= 1'h0;
      latencyRecord_55_timeStamp <= 64'h0;
      latencyRecord_55_reqType <= 8'h0;
      latencyRecord_56_valid <= 1'h0;
      latencyRecord_56_timeStamp <= 64'h0;
      latencyRecord_56_reqType <= 8'h0;
      latencyRecord_57_valid <= 1'h0;
      latencyRecord_57_timeStamp <= 64'h0;
      latencyRecord_57_reqType <= 8'h0;
      latencyRecord_58_valid <= 1'h0;
      latencyRecord_58_timeStamp <= 64'h0;
      latencyRecord_58_reqType <= 8'h0;
      latencyRecord_59_valid <= 1'h0;
      latencyRecord_59_timeStamp <= 64'h0;
      latencyRecord_59_reqType <= 8'h0;
      latencyRecord_60_valid <= 1'h0;
      latencyRecord_60_timeStamp <= 64'h0;
      latencyRecord_60_reqType <= 8'h0;
      latencyRecord_61_valid <= 1'h0;
      latencyRecord_61_timeStamp <= 64'h0;
      latencyRecord_61_reqType <= 8'h0;
      latencyRecord_62_valid <= 1'h0;
      latencyRecord_62_timeStamp <= 64'h0;
      latencyRecord_62_reqType <= 8'h0;
      latencyRecord_63_valid <= 1'h0;
      latencyRecord_63_timeStamp <= 64'h0;
      latencyRecord_63_reqType <= 8'h0;
      first_r_counter <= 1'h0;
    end
    else begin
      timer <= 64'(timer + 64'h1);
      latencyRecord_0_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h0)
        & (_GEN_123 | latencyRecord_0_valid);
      if (_GEN_123) begin
        latencyRecord_0_timeStamp <= timer;
        latencyRecord_0_reqType <= _GEN_187;
      end
      latencyRecord_1_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1)
        & (_GEN_124 | latencyRecord_1_valid);
      if (_GEN_124) begin
        latencyRecord_1_timeStamp <= timer;
        latencyRecord_1_reqType <= _GEN_187;
      end
      latencyRecord_2_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2)
        & (_GEN_125 | latencyRecord_2_valid);
      if (_GEN_125) begin
        latencyRecord_2_timeStamp <= timer;
        latencyRecord_2_reqType <= _GEN_187;
      end
      latencyRecord_3_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3)
        & (_GEN_126 | latencyRecord_3_valid);
      if (_GEN_126) begin
        latencyRecord_3_timeStamp <= timer;
        latencyRecord_3_reqType <= _GEN_187;
      end
      latencyRecord_4_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h4)
        & (_GEN_127 | latencyRecord_4_valid);
      if (_GEN_127) begin
        latencyRecord_4_timeStamp <= timer;
        latencyRecord_4_reqType <= _GEN_187;
      end
      latencyRecord_5_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h5)
        & (_GEN_128 | latencyRecord_5_valid);
      if (_GEN_128) begin
        latencyRecord_5_timeStamp <= timer;
        latencyRecord_5_reqType <= _GEN_187;
      end
      latencyRecord_6_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h6)
        & (_GEN_129 | latencyRecord_6_valid);
      if (_GEN_129) begin
        latencyRecord_6_timeStamp <= timer;
        latencyRecord_6_reqType <= _GEN_187;
      end
      latencyRecord_7_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h7)
        & (_GEN_130 | latencyRecord_7_valid);
      if (_GEN_130) begin
        latencyRecord_7_timeStamp <= timer;
        latencyRecord_7_reqType <= _GEN_187;
      end
      latencyRecord_8_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h8)
        & (_GEN_131 | latencyRecord_8_valid);
      if (_GEN_131) begin
        latencyRecord_8_timeStamp <= timer;
        latencyRecord_8_reqType <= _GEN_187;
      end
      latencyRecord_9_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h9)
        & (_GEN_132 | latencyRecord_9_valid);
      if (_GEN_132) begin
        latencyRecord_9_timeStamp <= timer;
        latencyRecord_9_reqType <= _GEN_187;
      end
      latencyRecord_10_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hA)
        & (_GEN_133 | latencyRecord_10_valid);
      if (_GEN_133) begin
        latencyRecord_10_timeStamp <= timer;
        latencyRecord_10_reqType <= _GEN_187;
      end
      latencyRecord_11_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hB)
        & (_GEN_134 | latencyRecord_11_valid);
      if (_GEN_134) begin
        latencyRecord_11_timeStamp <= timer;
        latencyRecord_11_reqType <= _GEN_187;
      end
      latencyRecord_12_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hC)
        & (_GEN_135 | latencyRecord_12_valid);
      if (_GEN_135) begin
        latencyRecord_12_timeStamp <= timer;
        latencyRecord_12_reqType <= _GEN_187;
      end
      latencyRecord_13_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hD)
        & (_GEN_136 | latencyRecord_13_valid);
      if (_GEN_136) begin
        latencyRecord_13_timeStamp <= timer;
        latencyRecord_13_reqType <= _GEN_187;
      end
      latencyRecord_14_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hE)
        & (_GEN_137 | latencyRecord_14_valid);
      if (_GEN_137) begin
        latencyRecord_14_timeStamp <= timer;
        latencyRecord_14_reqType <= _GEN_187;
      end
      latencyRecord_15_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'hF)
        & (_GEN_138 | latencyRecord_15_valid);
      if (_GEN_138) begin
        latencyRecord_15_timeStamp <= timer;
        latencyRecord_15_reqType <= _GEN_187;
      end
      latencyRecord_16_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h10)
        & (_GEN_139 | latencyRecord_16_valid);
      if (_GEN_139) begin
        latencyRecord_16_timeStamp <= timer;
        latencyRecord_16_reqType <= _GEN_187;
      end
      latencyRecord_17_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h11)
        & (_GEN_140 | latencyRecord_17_valid);
      if (_GEN_140) begin
        latencyRecord_17_timeStamp <= timer;
        latencyRecord_17_reqType <= _GEN_187;
      end
      latencyRecord_18_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h12)
        & (_GEN_141 | latencyRecord_18_valid);
      if (_GEN_141) begin
        latencyRecord_18_timeStamp <= timer;
        latencyRecord_18_reqType <= _GEN_187;
      end
      latencyRecord_19_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h13)
        & (_GEN_142 | latencyRecord_19_valid);
      if (_GEN_142) begin
        latencyRecord_19_timeStamp <= timer;
        latencyRecord_19_reqType <= _GEN_187;
      end
      latencyRecord_20_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h14)
        & (_GEN_143 | latencyRecord_20_valid);
      if (_GEN_143) begin
        latencyRecord_20_timeStamp <= timer;
        latencyRecord_20_reqType <= _GEN_187;
      end
      latencyRecord_21_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h15)
        & (_GEN_144 | latencyRecord_21_valid);
      if (_GEN_144) begin
        latencyRecord_21_timeStamp <= timer;
        latencyRecord_21_reqType <= _GEN_187;
      end
      latencyRecord_22_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h16)
        & (_GEN_145 | latencyRecord_22_valid);
      if (_GEN_145) begin
        latencyRecord_22_timeStamp <= timer;
        latencyRecord_22_reqType <= _GEN_187;
      end
      latencyRecord_23_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h17)
        & (_GEN_146 | latencyRecord_23_valid);
      if (_GEN_146) begin
        latencyRecord_23_timeStamp <= timer;
        latencyRecord_23_reqType <= _GEN_187;
      end
      latencyRecord_24_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h18)
        & (_GEN_147 | latencyRecord_24_valid);
      if (_GEN_147) begin
        latencyRecord_24_timeStamp <= timer;
        latencyRecord_24_reqType <= _GEN_187;
      end
      latencyRecord_25_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h19)
        & (_GEN_148 | latencyRecord_25_valid);
      if (_GEN_148) begin
        latencyRecord_25_timeStamp <= timer;
        latencyRecord_25_reqType <= _GEN_187;
      end
      latencyRecord_26_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1A)
        & (_GEN_149 | latencyRecord_26_valid);
      if (_GEN_149) begin
        latencyRecord_26_timeStamp <= timer;
        latencyRecord_26_reqType <= _GEN_187;
      end
      latencyRecord_27_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1B)
        & (_GEN_150 | latencyRecord_27_valid);
      if (_GEN_150) begin
        latencyRecord_27_timeStamp <= timer;
        latencyRecord_27_reqType <= _GEN_187;
      end
      latencyRecord_28_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1C)
        & (_GEN_151 | latencyRecord_28_valid);
      if (_GEN_151) begin
        latencyRecord_28_timeStamp <= timer;
        latencyRecord_28_reqType <= _GEN_187;
      end
      latencyRecord_29_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1D)
        & (_GEN_152 | latencyRecord_29_valid);
      if (_GEN_152) begin
        latencyRecord_29_timeStamp <= timer;
        latencyRecord_29_reqType <= _GEN_187;
      end
      latencyRecord_30_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1E)
        & (_GEN_153 | latencyRecord_30_valid);
      if (_GEN_153) begin
        latencyRecord_30_timeStamp <= timer;
        latencyRecord_30_reqType <= _GEN_187;
      end
      latencyRecord_31_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h1F)
        & (_GEN_154 | latencyRecord_31_valid);
      if (_GEN_154) begin
        latencyRecord_31_timeStamp <= timer;
        latencyRecord_31_reqType <= _GEN_187;
      end
      latencyRecord_32_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h20)
        & (_GEN_155 | latencyRecord_32_valid);
      if (_GEN_155) begin
        latencyRecord_32_timeStamp <= timer;
        latencyRecord_32_reqType <= _GEN_187;
      end
      latencyRecord_33_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h21)
        & (_GEN_156 | latencyRecord_33_valid);
      if (_GEN_156) begin
        latencyRecord_33_timeStamp <= timer;
        latencyRecord_33_reqType <= _GEN_187;
      end
      latencyRecord_34_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h22)
        & (_GEN_157 | latencyRecord_34_valid);
      if (_GEN_157) begin
        latencyRecord_34_timeStamp <= timer;
        latencyRecord_34_reqType <= _GEN_187;
      end
      latencyRecord_35_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h23)
        & (_GEN_158 | latencyRecord_35_valid);
      if (_GEN_158) begin
        latencyRecord_35_timeStamp <= timer;
        latencyRecord_35_reqType <= _GEN_187;
      end
      latencyRecord_36_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h24)
        & (_GEN_159 | latencyRecord_36_valid);
      if (_GEN_159) begin
        latencyRecord_36_timeStamp <= timer;
        latencyRecord_36_reqType <= _GEN_187;
      end
      latencyRecord_37_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h25)
        & (_GEN_160 | latencyRecord_37_valid);
      if (_GEN_160) begin
        latencyRecord_37_timeStamp <= timer;
        latencyRecord_37_reqType <= _GEN_187;
      end
      latencyRecord_38_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h26)
        & (_GEN_161 | latencyRecord_38_valid);
      if (_GEN_161) begin
        latencyRecord_38_timeStamp <= timer;
        latencyRecord_38_reqType <= _GEN_187;
      end
      latencyRecord_39_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h27)
        & (_GEN_162 | latencyRecord_39_valid);
      if (_GEN_162) begin
        latencyRecord_39_timeStamp <= timer;
        latencyRecord_39_reqType <= _GEN_187;
      end
      latencyRecord_40_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h28)
        & (_GEN_163 | latencyRecord_40_valid);
      if (_GEN_163) begin
        latencyRecord_40_timeStamp <= timer;
        latencyRecord_40_reqType <= _GEN_187;
      end
      latencyRecord_41_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h29)
        & (_GEN_164 | latencyRecord_41_valid);
      if (_GEN_164) begin
        latencyRecord_41_timeStamp <= timer;
        latencyRecord_41_reqType <= _GEN_187;
      end
      latencyRecord_42_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2A)
        & (_GEN_165 | latencyRecord_42_valid);
      if (_GEN_165) begin
        latencyRecord_42_timeStamp <= timer;
        latencyRecord_42_reqType <= _GEN_187;
      end
      latencyRecord_43_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2B)
        & (_GEN_166 | latencyRecord_43_valid);
      if (_GEN_166) begin
        latencyRecord_43_timeStamp <= timer;
        latencyRecord_43_reqType <= _GEN_187;
      end
      latencyRecord_44_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2C)
        & (_GEN_167 | latencyRecord_44_valid);
      if (_GEN_167) begin
        latencyRecord_44_timeStamp <= timer;
        latencyRecord_44_reqType <= _GEN_187;
      end
      latencyRecord_45_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2D)
        & (_GEN_168 | latencyRecord_45_valid);
      if (_GEN_168) begin
        latencyRecord_45_timeStamp <= timer;
        latencyRecord_45_reqType <= _GEN_187;
      end
      latencyRecord_46_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2E)
        & (_GEN_169 | latencyRecord_46_valid);
      if (_GEN_169) begin
        latencyRecord_46_timeStamp <= timer;
        latencyRecord_46_reqType <= _GEN_187;
      end
      latencyRecord_47_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h2F)
        & (_GEN_170 | latencyRecord_47_valid);
      if (_GEN_170) begin
        latencyRecord_47_timeStamp <= timer;
        latencyRecord_47_reqType <= _GEN_187;
      end
      latencyRecord_48_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h30)
        & (_GEN_171 | latencyRecord_48_valid);
      if (_GEN_171) begin
        latencyRecord_48_timeStamp <= timer;
        latencyRecord_48_reqType <= _GEN_187;
      end
      latencyRecord_49_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h31)
        & (_GEN_172 | latencyRecord_49_valid);
      if (_GEN_172) begin
        latencyRecord_49_timeStamp <= timer;
        latencyRecord_49_reqType <= _GEN_187;
      end
      latencyRecord_50_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h32)
        & (_GEN_173 | latencyRecord_50_valid);
      if (_GEN_173) begin
        latencyRecord_50_timeStamp <= timer;
        latencyRecord_50_reqType <= _GEN_187;
      end
      latencyRecord_51_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h33)
        & (_GEN_174 | latencyRecord_51_valid);
      if (_GEN_174) begin
        latencyRecord_51_timeStamp <= timer;
        latencyRecord_51_reqType <= _GEN_187;
      end
      latencyRecord_52_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h34)
        & (_GEN_175 | latencyRecord_52_valid);
      if (_GEN_175) begin
        latencyRecord_52_timeStamp <= timer;
        latencyRecord_52_reqType <= _GEN_187;
      end
      latencyRecord_53_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h35)
        & (_GEN_176 | latencyRecord_53_valid);
      if (_GEN_176) begin
        latencyRecord_53_timeStamp <= timer;
        latencyRecord_53_reqType <= _GEN_187;
      end
      latencyRecord_54_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h36)
        & (_GEN_177 | latencyRecord_54_valid);
      if (_GEN_177) begin
        latencyRecord_54_timeStamp <= timer;
        latencyRecord_54_reqType <= _GEN_187;
      end
      latencyRecord_55_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h37)
        & (_GEN_178 | latencyRecord_55_valid);
      if (_GEN_178) begin
        latencyRecord_55_timeStamp <= timer;
        latencyRecord_55_reqType <= _GEN_187;
      end
      latencyRecord_56_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h38)
        & (_GEN_179 | latencyRecord_56_valid);
      if (_GEN_179) begin
        latencyRecord_56_timeStamp <= timer;
        latencyRecord_56_reqType <= _GEN_187;
      end
      latencyRecord_57_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h39)
        & (_GEN_180 | latencyRecord_57_valid);
      if (_GEN_180) begin
        latencyRecord_57_timeStamp <= timer;
        latencyRecord_57_reqType <= _GEN_187;
      end
      latencyRecord_58_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3A)
        & (_GEN_181 | latencyRecord_58_valid);
      if (_GEN_181) begin
        latencyRecord_58_timeStamp <= timer;
        latencyRecord_58_reqType <= _GEN_187;
      end
      latencyRecord_59_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3B)
        & (_GEN_182 | latencyRecord_59_valid);
      if (_GEN_182) begin
        latencyRecord_59_timeStamp <= timer;
        latencyRecord_59_reqType <= _GEN_187;
      end
      latencyRecord_60_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3C)
        & (_GEN_183 | latencyRecord_60_valid);
      if (_GEN_183) begin
        latencyRecord_60_timeStamp <= timer;
        latencyRecord_60_reqType <= _GEN_187;
      end
      latencyRecord_61_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3D)
        & (_GEN_184 | latencyRecord_61_valid);
      if (_GEN_184) begin
        latencyRecord_61_timeStamp <= timer;
        latencyRecord_61_reqType <= _GEN_187;
      end
      latencyRecord_62_valid <=
        ~(resolveRecord_probe & auto_out_d_bits_source == 6'h3E)
        & (_GEN_185 | latencyRecord_62_valid);
      if (_GEN_185) begin
        latencyRecord_62_timeStamp <= timer;
        latencyRecord_62_reqType <= _GEN_187;
      end
      latencyRecord_63_valid <=
        ~(resolveRecord_probe & (&auto_out_d_bits_source))
        & (_GEN_186 | latencyRecord_63_valid);
      if (_GEN_186) begin
        latencyRecord_63_timeStamp <= timer;
        latencyRecord_63_reqType <= _GEN_187;
      end
      if (_resolveRecord_T_probe) begin
        if (first_r_counter)
          first_r_counter <= 1'(first_r_counter - 1'h1);
        else
          first_r_counter <= auto_out_d_bits_opcode[0] & ~(_first_r_beats1_decode_T[5]);
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:156];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [7:0] i = 8'h0; i < 8'h9D; i += 8'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        timer = {_RANDOM[8'h0], _RANDOM[8'h1]};
        latencyRecord_0_valid = _RANDOM[8'h2][0];
        latencyRecord_0_timeStamp =
          {_RANDOM[8'h2][31:1], _RANDOM[8'h3], _RANDOM[8'h4][0]};
        latencyRecord_0_reqType = _RANDOM[8'h4][8:1];
        latencyRecord_1_valid = _RANDOM[8'h4][9];
        latencyRecord_1_timeStamp =
          {_RANDOM[8'h4][31:10], _RANDOM[8'h5], _RANDOM[8'h6][9:0]};
        latencyRecord_1_reqType = _RANDOM[8'h6][17:10];
        latencyRecord_2_valid = _RANDOM[8'h6][18];
        latencyRecord_2_timeStamp =
          {_RANDOM[8'h6][31:19], _RANDOM[8'h7], _RANDOM[8'h8][18:0]};
        latencyRecord_2_reqType = _RANDOM[8'h8][26:19];
        latencyRecord_3_valid = _RANDOM[8'h8][27];
        latencyRecord_3_timeStamp =
          {_RANDOM[8'h8][31:28], _RANDOM[8'h9], _RANDOM[8'hA][27:0]};
        latencyRecord_3_reqType = {_RANDOM[8'hA][31:28], _RANDOM[8'hB][3:0]};
        latencyRecord_4_valid = _RANDOM[8'hB][4];
        latencyRecord_4_timeStamp =
          {_RANDOM[8'hB][31:5], _RANDOM[8'hC], _RANDOM[8'hD][4:0]};
        latencyRecord_4_reqType = _RANDOM[8'hD][12:5];
        latencyRecord_5_valid = _RANDOM[8'hD][13];
        latencyRecord_5_timeStamp =
          {_RANDOM[8'hD][31:14], _RANDOM[8'hE], _RANDOM[8'hF][13:0]};
        latencyRecord_5_reqType = _RANDOM[8'hF][21:14];
        latencyRecord_6_valid = _RANDOM[8'hF][22];
        latencyRecord_6_timeStamp =
          {_RANDOM[8'hF][31:23], _RANDOM[8'h10], _RANDOM[8'h11][22:0]};
        latencyRecord_6_reqType = _RANDOM[8'h11][30:23];
        latencyRecord_7_valid = _RANDOM[8'h11][31];
        latencyRecord_7_timeStamp = {_RANDOM[8'h12], _RANDOM[8'h13]};
        latencyRecord_7_reqType = _RANDOM[8'h14][7:0];
        latencyRecord_8_valid = _RANDOM[8'h14][8];
        latencyRecord_8_timeStamp =
          {_RANDOM[8'h14][31:9], _RANDOM[8'h15], _RANDOM[8'h16][8:0]};
        latencyRecord_8_reqType = _RANDOM[8'h16][16:9];
        latencyRecord_9_valid = _RANDOM[8'h16][17];
        latencyRecord_9_timeStamp =
          {_RANDOM[8'h16][31:18], _RANDOM[8'h17], _RANDOM[8'h18][17:0]};
        latencyRecord_9_reqType = _RANDOM[8'h18][25:18];
        latencyRecord_10_valid = _RANDOM[8'h18][26];
        latencyRecord_10_timeStamp =
          {_RANDOM[8'h18][31:27], _RANDOM[8'h19], _RANDOM[8'h1A][26:0]};
        latencyRecord_10_reqType = {_RANDOM[8'h1A][31:27], _RANDOM[8'h1B][2:0]};
        latencyRecord_11_valid = _RANDOM[8'h1B][3];
        latencyRecord_11_timeStamp =
          {_RANDOM[8'h1B][31:4], _RANDOM[8'h1C], _RANDOM[8'h1D][3:0]};
        latencyRecord_11_reqType = _RANDOM[8'h1D][11:4];
        latencyRecord_12_valid = _RANDOM[8'h1D][12];
        latencyRecord_12_timeStamp =
          {_RANDOM[8'h1D][31:13], _RANDOM[8'h1E], _RANDOM[8'h1F][12:0]};
        latencyRecord_12_reqType = _RANDOM[8'h1F][20:13];
        latencyRecord_13_valid = _RANDOM[8'h1F][21];
        latencyRecord_13_timeStamp =
          {_RANDOM[8'h1F][31:22], _RANDOM[8'h20], _RANDOM[8'h21][21:0]};
        latencyRecord_13_reqType = _RANDOM[8'h21][29:22];
        latencyRecord_14_valid = _RANDOM[8'h21][30];
        latencyRecord_14_timeStamp =
          {_RANDOM[8'h21][31], _RANDOM[8'h22], _RANDOM[8'h23][30:0]};
        latencyRecord_14_reqType = {_RANDOM[8'h23][31], _RANDOM[8'h24][6:0]};
        latencyRecord_15_valid = _RANDOM[8'h24][7];
        latencyRecord_15_timeStamp =
          {_RANDOM[8'h24][31:8], _RANDOM[8'h25], _RANDOM[8'h26][7:0]};
        latencyRecord_15_reqType = _RANDOM[8'h26][15:8];
        latencyRecord_16_valid = _RANDOM[8'h26][16];
        latencyRecord_16_timeStamp =
          {_RANDOM[8'h26][31:17], _RANDOM[8'h27], _RANDOM[8'h28][16:0]};
        latencyRecord_16_reqType = _RANDOM[8'h28][24:17];
        latencyRecord_17_valid = _RANDOM[8'h28][25];
        latencyRecord_17_timeStamp =
          {_RANDOM[8'h28][31:26], _RANDOM[8'h29], _RANDOM[8'h2A][25:0]};
        latencyRecord_17_reqType = {_RANDOM[8'h2A][31:26], _RANDOM[8'h2B][1:0]};
        latencyRecord_18_valid = _RANDOM[8'h2B][2];
        latencyRecord_18_timeStamp =
          {_RANDOM[8'h2B][31:3], _RANDOM[8'h2C], _RANDOM[8'h2D][2:0]};
        latencyRecord_18_reqType = _RANDOM[8'h2D][10:3];
        latencyRecord_19_valid = _RANDOM[8'h2D][11];
        latencyRecord_19_timeStamp =
          {_RANDOM[8'h2D][31:12], _RANDOM[8'h2E], _RANDOM[8'h2F][11:0]};
        latencyRecord_19_reqType = _RANDOM[8'h2F][19:12];
        latencyRecord_20_valid = _RANDOM[8'h2F][20];
        latencyRecord_20_timeStamp =
          {_RANDOM[8'h2F][31:21], _RANDOM[8'h30], _RANDOM[8'h31][20:0]};
        latencyRecord_20_reqType = _RANDOM[8'h31][28:21];
        latencyRecord_21_valid = _RANDOM[8'h31][29];
        latencyRecord_21_timeStamp =
          {_RANDOM[8'h31][31:30], _RANDOM[8'h32], _RANDOM[8'h33][29:0]};
        latencyRecord_21_reqType = {_RANDOM[8'h33][31:30], _RANDOM[8'h34][5:0]};
        latencyRecord_22_valid = _RANDOM[8'h34][6];
        latencyRecord_22_timeStamp =
          {_RANDOM[8'h34][31:7], _RANDOM[8'h35], _RANDOM[8'h36][6:0]};
        latencyRecord_22_reqType = _RANDOM[8'h36][14:7];
        latencyRecord_23_valid = _RANDOM[8'h36][15];
        latencyRecord_23_timeStamp =
          {_RANDOM[8'h36][31:16], _RANDOM[8'h37], _RANDOM[8'h38][15:0]};
        latencyRecord_23_reqType = _RANDOM[8'h38][23:16];
        latencyRecord_24_valid = _RANDOM[8'h38][24];
        latencyRecord_24_timeStamp =
          {_RANDOM[8'h38][31:25], _RANDOM[8'h39], _RANDOM[8'h3A][24:0]};
        latencyRecord_24_reqType = {_RANDOM[8'h3A][31:25], _RANDOM[8'h3B][0]};
        latencyRecord_25_valid = _RANDOM[8'h3B][1];
        latencyRecord_25_timeStamp =
          {_RANDOM[8'h3B][31:2], _RANDOM[8'h3C], _RANDOM[8'h3D][1:0]};
        latencyRecord_25_reqType = _RANDOM[8'h3D][9:2];
        latencyRecord_26_valid = _RANDOM[8'h3D][10];
        latencyRecord_26_timeStamp =
          {_RANDOM[8'h3D][31:11], _RANDOM[8'h3E], _RANDOM[8'h3F][10:0]};
        latencyRecord_26_reqType = _RANDOM[8'h3F][18:11];
        latencyRecord_27_valid = _RANDOM[8'h3F][19];
        latencyRecord_27_timeStamp =
          {_RANDOM[8'h3F][31:20], _RANDOM[8'h40], _RANDOM[8'h41][19:0]};
        latencyRecord_27_reqType = _RANDOM[8'h41][27:20];
        latencyRecord_28_valid = _RANDOM[8'h41][28];
        latencyRecord_28_timeStamp =
          {_RANDOM[8'h41][31:29], _RANDOM[8'h42], _RANDOM[8'h43][28:0]};
        latencyRecord_28_reqType = {_RANDOM[8'h43][31:29], _RANDOM[8'h44][4:0]};
        latencyRecord_29_valid = _RANDOM[8'h44][5];
        latencyRecord_29_timeStamp =
          {_RANDOM[8'h44][31:6], _RANDOM[8'h45], _RANDOM[8'h46][5:0]};
        latencyRecord_29_reqType = _RANDOM[8'h46][13:6];
        latencyRecord_30_valid = _RANDOM[8'h46][14];
        latencyRecord_30_timeStamp =
          {_RANDOM[8'h46][31:15], _RANDOM[8'h47], _RANDOM[8'h48][14:0]};
        latencyRecord_30_reqType = _RANDOM[8'h48][22:15];
        latencyRecord_31_valid = _RANDOM[8'h48][23];
        latencyRecord_31_timeStamp =
          {_RANDOM[8'h48][31:24], _RANDOM[8'h49], _RANDOM[8'h4A][23:0]};
        latencyRecord_31_reqType = _RANDOM[8'h4A][31:24];
        latencyRecord_32_valid = _RANDOM[8'h4B][0];
        latencyRecord_32_timeStamp =
          {_RANDOM[8'h4B][31:1], _RANDOM[8'h4C], _RANDOM[8'h4D][0]};
        latencyRecord_32_reqType = _RANDOM[8'h4D][8:1];
        latencyRecord_33_valid = _RANDOM[8'h4D][9];
        latencyRecord_33_timeStamp =
          {_RANDOM[8'h4D][31:10], _RANDOM[8'h4E], _RANDOM[8'h4F][9:0]};
        latencyRecord_33_reqType = _RANDOM[8'h4F][17:10];
        latencyRecord_34_valid = _RANDOM[8'h4F][18];
        latencyRecord_34_timeStamp =
          {_RANDOM[8'h4F][31:19], _RANDOM[8'h50], _RANDOM[8'h51][18:0]};
        latencyRecord_34_reqType = _RANDOM[8'h51][26:19];
        latencyRecord_35_valid = _RANDOM[8'h51][27];
        latencyRecord_35_timeStamp =
          {_RANDOM[8'h51][31:28], _RANDOM[8'h52], _RANDOM[8'h53][27:0]};
        latencyRecord_35_reqType = {_RANDOM[8'h53][31:28], _RANDOM[8'h54][3:0]};
        latencyRecord_36_valid = _RANDOM[8'h54][4];
        latencyRecord_36_timeStamp =
          {_RANDOM[8'h54][31:5], _RANDOM[8'h55], _RANDOM[8'h56][4:0]};
        latencyRecord_36_reqType = _RANDOM[8'h56][12:5];
        latencyRecord_37_valid = _RANDOM[8'h56][13];
        latencyRecord_37_timeStamp =
          {_RANDOM[8'h56][31:14], _RANDOM[8'h57], _RANDOM[8'h58][13:0]};
        latencyRecord_37_reqType = _RANDOM[8'h58][21:14];
        latencyRecord_38_valid = _RANDOM[8'h58][22];
        latencyRecord_38_timeStamp =
          {_RANDOM[8'h58][31:23], _RANDOM[8'h59], _RANDOM[8'h5A][22:0]};
        latencyRecord_38_reqType = _RANDOM[8'h5A][30:23];
        latencyRecord_39_valid = _RANDOM[8'h5A][31];
        latencyRecord_39_timeStamp = {_RANDOM[8'h5B], _RANDOM[8'h5C]};
        latencyRecord_39_reqType = _RANDOM[8'h5D][7:0];
        latencyRecord_40_valid = _RANDOM[8'h5D][8];
        latencyRecord_40_timeStamp =
          {_RANDOM[8'h5D][31:9], _RANDOM[8'h5E], _RANDOM[8'h5F][8:0]};
        latencyRecord_40_reqType = _RANDOM[8'h5F][16:9];
        latencyRecord_41_valid = _RANDOM[8'h5F][17];
        latencyRecord_41_timeStamp =
          {_RANDOM[8'h5F][31:18], _RANDOM[8'h60], _RANDOM[8'h61][17:0]};
        latencyRecord_41_reqType = _RANDOM[8'h61][25:18];
        latencyRecord_42_valid = _RANDOM[8'h61][26];
        latencyRecord_42_timeStamp =
          {_RANDOM[8'h61][31:27], _RANDOM[8'h62], _RANDOM[8'h63][26:0]};
        latencyRecord_42_reqType = {_RANDOM[8'h63][31:27], _RANDOM[8'h64][2:0]};
        latencyRecord_43_valid = _RANDOM[8'h64][3];
        latencyRecord_43_timeStamp =
          {_RANDOM[8'h64][31:4], _RANDOM[8'h65], _RANDOM[8'h66][3:0]};
        latencyRecord_43_reqType = _RANDOM[8'h66][11:4];
        latencyRecord_44_valid = _RANDOM[8'h66][12];
        latencyRecord_44_timeStamp =
          {_RANDOM[8'h66][31:13], _RANDOM[8'h67], _RANDOM[8'h68][12:0]};
        latencyRecord_44_reqType = _RANDOM[8'h68][20:13];
        latencyRecord_45_valid = _RANDOM[8'h68][21];
        latencyRecord_45_timeStamp =
          {_RANDOM[8'h68][31:22], _RANDOM[8'h69], _RANDOM[8'h6A][21:0]};
        latencyRecord_45_reqType = _RANDOM[8'h6A][29:22];
        latencyRecord_46_valid = _RANDOM[8'h6A][30];
        latencyRecord_46_timeStamp =
          {_RANDOM[8'h6A][31], _RANDOM[8'h6B], _RANDOM[8'h6C][30:0]};
        latencyRecord_46_reqType = {_RANDOM[8'h6C][31], _RANDOM[8'h6D][6:0]};
        latencyRecord_47_valid = _RANDOM[8'h6D][7];
        latencyRecord_47_timeStamp =
          {_RANDOM[8'h6D][31:8], _RANDOM[8'h6E], _RANDOM[8'h6F][7:0]};
        latencyRecord_47_reqType = _RANDOM[8'h6F][15:8];
        latencyRecord_48_valid = _RANDOM[8'h6F][16];
        latencyRecord_48_timeStamp =
          {_RANDOM[8'h6F][31:17], _RANDOM[8'h70], _RANDOM[8'h71][16:0]};
        latencyRecord_48_reqType = _RANDOM[8'h71][24:17];
        latencyRecord_49_valid = _RANDOM[8'h71][25];
        latencyRecord_49_timeStamp =
          {_RANDOM[8'h71][31:26], _RANDOM[8'h72], _RANDOM[8'h73][25:0]};
        latencyRecord_49_reqType = {_RANDOM[8'h73][31:26], _RANDOM[8'h74][1:0]};
        latencyRecord_50_valid = _RANDOM[8'h74][2];
        latencyRecord_50_timeStamp =
          {_RANDOM[8'h74][31:3], _RANDOM[8'h75], _RANDOM[8'h76][2:0]};
        latencyRecord_50_reqType = _RANDOM[8'h76][10:3];
        latencyRecord_51_valid = _RANDOM[8'h76][11];
        latencyRecord_51_timeStamp =
          {_RANDOM[8'h76][31:12], _RANDOM[8'h77], _RANDOM[8'h78][11:0]};
        latencyRecord_51_reqType = _RANDOM[8'h78][19:12];
        latencyRecord_52_valid = _RANDOM[8'h78][20];
        latencyRecord_52_timeStamp =
          {_RANDOM[8'h78][31:21], _RANDOM[8'h79], _RANDOM[8'h7A][20:0]};
        latencyRecord_52_reqType = _RANDOM[8'h7A][28:21];
        latencyRecord_53_valid = _RANDOM[8'h7A][29];
        latencyRecord_53_timeStamp =
          {_RANDOM[8'h7A][31:30], _RANDOM[8'h7B], _RANDOM[8'h7C][29:0]};
        latencyRecord_53_reqType = {_RANDOM[8'h7C][31:30], _RANDOM[8'h7D][5:0]};
        latencyRecord_54_valid = _RANDOM[8'h7D][6];
        latencyRecord_54_timeStamp =
          {_RANDOM[8'h7D][31:7], _RANDOM[8'h7E], _RANDOM[8'h7F][6:0]};
        latencyRecord_54_reqType = _RANDOM[8'h7F][14:7];
        latencyRecord_55_valid = _RANDOM[8'h7F][15];
        latencyRecord_55_timeStamp =
          {_RANDOM[8'h7F][31:16], _RANDOM[8'h80], _RANDOM[8'h81][15:0]};
        latencyRecord_55_reqType = _RANDOM[8'h81][23:16];
        latencyRecord_56_valid = _RANDOM[8'h81][24];
        latencyRecord_56_timeStamp =
          {_RANDOM[8'h81][31:25], _RANDOM[8'h82], _RANDOM[8'h83][24:0]};
        latencyRecord_56_reqType = {_RANDOM[8'h83][31:25], _RANDOM[8'h84][0]};
        latencyRecord_57_valid = _RANDOM[8'h84][1];
        latencyRecord_57_timeStamp =
          {_RANDOM[8'h84][31:2], _RANDOM[8'h85], _RANDOM[8'h86][1:0]};
        latencyRecord_57_reqType = _RANDOM[8'h86][9:2];
        latencyRecord_58_valid = _RANDOM[8'h86][10];
        latencyRecord_58_timeStamp =
          {_RANDOM[8'h86][31:11], _RANDOM[8'h87], _RANDOM[8'h88][10:0]};
        latencyRecord_58_reqType = _RANDOM[8'h88][18:11];
        latencyRecord_59_valid = _RANDOM[8'h88][19];
        latencyRecord_59_timeStamp =
          {_RANDOM[8'h88][31:20], _RANDOM[8'h89], _RANDOM[8'h8A][19:0]};
        latencyRecord_59_reqType = _RANDOM[8'h8A][27:20];
        latencyRecord_60_valid = _RANDOM[8'h8A][28];
        latencyRecord_60_timeStamp =
          {_RANDOM[8'h8A][31:29], _RANDOM[8'h8B], _RANDOM[8'h8C][28:0]};
        latencyRecord_60_reqType = {_RANDOM[8'h8C][31:29], _RANDOM[8'h8D][4:0]};
        latencyRecord_61_valid = _RANDOM[8'h8D][5];
        latencyRecord_61_timeStamp =
          {_RANDOM[8'h8D][31:6], _RANDOM[8'h8E], _RANDOM[8'h8F][5:0]};
        latencyRecord_61_reqType = _RANDOM[8'h8F][13:6];
        latencyRecord_62_valid = _RANDOM[8'h8F][14];
        latencyRecord_62_timeStamp =
          {_RANDOM[8'h8F][31:15], _RANDOM[8'h90], _RANDOM[8'h91][14:0]};
        latencyRecord_62_reqType = _RANDOM[8'h91][22:15];
        latencyRecord_63_valid = _RANDOM[8'h91][23];
        latencyRecord_63_timeStamp =
          {_RANDOM[8'h91][31:24], _RANDOM[8'h92], _RANDOM[8'h93][23:0]};
        latencyRecord_63_reqType = _RANDOM[8'h93][31:24];
        first_r_counter = _RANDOM[8'h9C][0];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        timer = 64'h0;
        latencyRecord_0_valid = 1'h0;
        latencyRecord_0_timeStamp = 64'h0;
        latencyRecord_0_reqType = 8'h0;
        latencyRecord_1_valid = 1'h0;
        latencyRecord_1_timeStamp = 64'h0;
        latencyRecord_1_reqType = 8'h0;
        latencyRecord_2_valid = 1'h0;
        latencyRecord_2_timeStamp = 64'h0;
        latencyRecord_2_reqType = 8'h0;
        latencyRecord_3_valid = 1'h0;
        latencyRecord_3_timeStamp = 64'h0;
        latencyRecord_3_reqType = 8'h0;
        latencyRecord_4_valid = 1'h0;
        latencyRecord_4_timeStamp = 64'h0;
        latencyRecord_4_reqType = 8'h0;
        latencyRecord_5_valid = 1'h0;
        latencyRecord_5_timeStamp = 64'h0;
        latencyRecord_5_reqType = 8'h0;
        latencyRecord_6_valid = 1'h0;
        latencyRecord_6_timeStamp = 64'h0;
        latencyRecord_6_reqType = 8'h0;
        latencyRecord_7_valid = 1'h0;
        latencyRecord_7_timeStamp = 64'h0;
        latencyRecord_7_reqType = 8'h0;
        latencyRecord_8_valid = 1'h0;
        latencyRecord_8_timeStamp = 64'h0;
        latencyRecord_8_reqType = 8'h0;
        latencyRecord_9_valid = 1'h0;
        latencyRecord_9_timeStamp = 64'h0;
        latencyRecord_9_reqType = 8'h0;
        latencyRecord_10_valid = 1'h0;
        latencyRecord_10_timeStamp = 64'h0;
        latencyRecord_10_reqType = 8'h0;
        latencyRecord_11_valid = 1'h0;
        latencyRecord_11_timeStamp = 64'h0;
        latencyRecord_11_reqType = 8'h0;
        latencyRecord_12_valid = 1'h0;
        latencyRecord_12_timeStamp = 64'h0;
        latencyRecord_12_reqType = 8'h0;
        latencyRecord_13_valid = 1'h0;
        latencyRecord_13_timeStamp = 64'h0;
        latencyRecord_13_reqType = 8'h0;
        latencyRecord_14_valid = 1'h0;
        latencyRecord_14_timeStamp = 64'h0;
        latencyRecord_14_reqType = 8'h0;
        latencyRecord_15_valid = 1'h0;
        latencyRecord_15_timeStamp = 64'h0;
        latencyRecord_15_reqType = 8'h0;
        latencyRecord_16_valid = 1'h0;
        latencyRecord_16_timeStamp = 64'h0;
        latencyRecord_16_reqType = 8'h0;
        latencyRecord_17_valid = 1'h0;
        latencyRecord_17_timeStamp = 64'h0;
        latencyRecord_17_reqType = 8'h0;
        latencyRecord_18_valid = 1'h0;
        latencyRecord_18_timeStamp = 64'h0;
        latencyRecord_18_reqType = 8'h0;
        latencyRecord_19_valid = 1'h0;
        latencyRecord_19_timeStamp = 64'h0;
        latencyRecord_19_reqType = 8'h0;
        latencyRecord_20_valid = 1'h0;
        latencyRecord_20_timeStamp = 64'h0;
        latencyRecord_20_reqType = 8'h0;
        latencyRecord_21_valid = 1'h0;
        latencyRecord_21_timeStamp = 64'h0;
        latencyRecord_21_reqType = 8'h0;
        latencyRecord_22_valid = 1'h0;
        latencyRecord_22_timeStamp = 64'h0;
        latencyRecord_22_reqType = 8'h0;
        latencyRecord_23_valid = 1'h0;
        latencyRecord_23_timeStamp = 64'h0;
        latencyRecord_23_reqType = 8'h0;
        latencyRecord_24_valid = 1'h0;
        latencyRecord_24_timeStamp = 64'h0;
        latencyRecord_24_reqType = 8'h0;
        latencyRecord_25_valid = 1'h0;
        latencyRecord_25_timeStamp = 64'h0;
        latencyRecord_25_reqType = 8'h0;
        latencyRecord_26_valid = 1'h0;
        latencyRecord_26_timeStamp = 64'h0;
        latencyRecord_26_reqType = 8'h0;
        latencyRecord_27_valid = 1'h0;
        latencyRecord_27_timeStamp = 64'h0;
        latencyRecord_27_reqType = 8'h0;
        latencyRecord_28_valid = 1'h0;
        latencyRecord_28_timeStamp = 64'h0;
        latencyRecord_28_reqType = 8'h0;
        latencyRecord_29_valid = 1'h0;
        latencyRecord_29_timeStamp = 64'h0;
        latencyRecord_29_reqType = 8'h0;
        latencyRecord_30_valid = 1'h0;
        latencyRecord_30_timeStamp = 64'h0;
        latencyRecord_30_reqType = 8'h0;
        latencyRecord_31_valid = 1'h0;
        latencyRecord_31_timeStamp = 64'h0;
        latencyRecord_31_reqType = 8'h0;
        latencyRecord_32_valid = 1'h0;
        latencyRecord_32_timeStamp = 64'h0;
        latencyRecord_32_reqType = 8'h0;
        latencyRecord_33_valid = 1'h0;
        latencyRecord_33_timeStamp = 64'h0;
        latencyRecord_33_reqType = 8'h0;
        latencyRecord_34_valid = 1'h0;
        latencyRecord_34_timeStamp = 64'h0;
        latencyRecord_34_reqType = 8'h0;
        latencyRecord_35_valid = 1'h0;
        latencyRecord_35_timeStamp = 64'h0;
        latencyRecord_35_reqType = 8'h0;
        latencyRecord_36_valid = 1'h0;
        latencyRecord_36_timeStamp = 64'h0;
        latencyRecord_36_reqType = 8'h0;
        latencyRecord_37_valid = 1'h0;
        latencyRecord_37_timeStamp = 64'h0;
        latencyRecord_37_reqType = 8'h0;
        latencyRecord_38_valid = 1'h0;
        latencyRecord_38_timeStamp = 64'h0;
        latencyRecord_38_reqType = 8'h0;
        latencyRecord_39_valid = 1'h0;
        latencyRecord_39_timeStamp = 64'h0;
        latencyRecord_39_reqType = 8'h0;
        latencyRecord_40_valid = 1'h0;
        latencyRecord_40_timeStamp = 64'h0;
        latencyRecord_40_reqType = 8'h0;
        latencyRecord_41_valid = 1'h0;
        latencyRecord_41_timeStamp = 64'h0;
        latencyRecord_41_reqType = 8'h0;
        latencyRecord_42_valid = 1'h0;
        latencyRecord_42_timeStamp = 64'h0;
        latencyRecord_42_reqType = 8'h0;
        latencyRecord_43_valid = 1'h0;
        latencyRecord_43_timeStamp = 64'h0;
        latencyRecord_43_reqType = 8'h0;
        latencyRecord_44_valid = 1'h0;
        latencyRecord_44_timeStamp = 64'h0;
        latencyRecord_44_reqType = 8'h0;
        latencyRecord_45_valid = 1'h0;
        latencyRecord_45_timeStamp = 64'h0;
        latencyRecord_45_reqType = 8'h0;
        latencyRecord_46_valid = 1'h0;
        latencyRecord_46_timeStamp = 64'h0;
        latencyRecord_46_reqType = 8'h0;
        latencyRecord_47_valid = 1'h0;
        latencyRecord_47_timeStamp = 64'h0;
        latencyRecord_47_reqType = 8'h0;
        latencyRecord_48_valid = 1'h0;
        latencyRecord_48_timeStamp = 64'h0;
        latencyRecord_48_reqType = 8'h0;
        latencyRecord_49_valid = 1'h0;
        latencyRecord_49_timeStamp = 64'h0;
        latencyRecord_49_reqType = 8'h0;
        latencyRecord_50_valid = 1'h0;
        latencyRecord_50_timeStamp = 64'h0;
        latencyRecord_50_reqType = 8'h0;
        latencyRecord_51_valid = 1'h0;
        latencyRecord_51_timeStamp = 64'h0;
        latencyRecord_51_reqType = 8'h0;
        latencyRecord_52_valid = 1'h0;
        latencyRecord_52_timeStamp = 64'h0;
        latencyRecord_52_reqType = 8'h0;
        latencyRecord_53_valid = 1'h0;
        latencyRecord_53_timeStamp = 64'h0;
        latencyRecord_53_reqType = 8'h0;
        latencyRecord_54_valid = 1'h0;
        latencyRecord_54_timeStamp = 64'h0;
        latencyRecord_54_reqType = 8'h0;
        latencyRecord_55_valid = 1'h0;
        latencyRecord_55_timeStamp = 64'h0;
        latencyRecord_55_reqType = 8'h0;
        latencyRecord_56_valid = 1'h0;
        latencyRecord_56_timeStamp = 64'h0;
        latencyRecord_56_reqType = 8'h0;
        latencyRecord_57_valid = 1'h0;
        latencyRecord_57_timeStamp = 64'h0;
        latencyRecord_57_reqType = 8'h0;
        latencyRecord_58_valid = 1'h0;
        latencyRecord_58_timeStamp = 64'h0;
        latencyRecord_58_reqType = 8'h0;
        latencyRecord_59_valid = 1'h0;
        latencyRecord_59_timeStamp = 64'h0;
        latencyRecord_59_reqType = 8'h0;
        latencyRecord_60_valid = 1'h0;
        latencyRecord_60_timeStamp = 64'h0;
        latencyRecord_60_reqType = 8'h0;
        latencyRecord_61_valid = 1'h0;
        latencyRecord_61_timeStamp = 64'h0;
        latencyRecord_61_reqType = 8'h0;
        latencyRecord_62_valid = 1'h0;
        latencyRecord_62_timeStamp = 64'h0;
        latencyRecord_62_reqType = 8'h0;
        latencyRecord_63_valid = 1'h0;
        latencyRecord_63_timeStamp = 64'h0;
        latencyRecord_63_reqType = 8'h0;
        first_r_counter = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign auto_in_a_ready = auto_out_a_ready;
  assign auto_in_c_ready = auto_out_c_ready;
  assign auto_in_d_valid = auto_out_d_valid;
  assign auto_in_d_bits_opcode = auto_out_d_bits_opcode;
  assign auto_in_d_bits_param = auto_out_d_bits_param;
  assign auto_in_d_bits_size = auto_out_d_bits_size;
  assign auto_in_d_bits_source = auto_out_d_bits_source;
  assign auto_in_d_bits_sink = auto_out_d_bits_sink;
  assign auto_in_d_bits_denied = auto_out_d_bits_denied;
  assign auto_in_d_bits_data = auto_out_d_bits_data;
  assign auto_in_d_bits_corrupt = auto_out_d_bits_corrupt;
  assign auto_out_a_valid = auto_in_a_valid;
  assign auto_out_a_bits_opcode = auto_in_a_bits_opcode;
  assign auto_out_a_bits_param = auto_in_a_bits_param;
  assign auto_out_a_bits_size = auto_in_a_bits_size;
  assign auto_out_a_bits_source = auto_in_a_bits_source;
  assign auto_out_a_bits_address = auto_in_a_bits_address;
  assign auto_out_a_bits_user_reqSource = auto_in_a_bits_user_reqSource;
  assign auto_out_a_bits_mask = auto_in_a_bits_mask;
  assign auto_out_a_bits_data = auto_in_a_bits_data;
  assign auto_out_a_bits_corrupt = auto_in_a_bits_corrupt;
  assign auto_out_c_valid = auto_in_c_valid;
  assign auto_out_c_bits_opcode = auto_in_c_bits_opcode;
  assign auto_out_c_bits_size = auto_in_c_bits_size;
  assign auto_out_c_bits_source = auto_in_c_bits_source;
  assign auto_out_c_bits_address = auto_in_c_bits_address;
  assign auto_out_c_bits_user_reqSource = auto_in_c_bits_user_reqSource;
  assign auto_out_c_bits_data = auto_in_c_bits_data;
  assign auto_out_c_bits_corrupt = auto_in_c_bits_corrupt;
  assign auto_out_d_ready = auto_in_d_ready;
  assign auto_out_e_valid = auto_in_e_valid;
  assign auto_out_e_bits_sink = auto_in_e_bits_sink;
endmodule

