// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module NewPipelineConnectPipe_33(
  input          clock,
  input          reset,
  output         io_in_ready,
  input          io_in_valid,
  input  [63:0]  io_in_bits_vaddr,
  input  [49:0]  io_in_bits_basevaddr,
  input  [15:0]  io_in_bits_mask,
  input  [3:0]   io_in_bits_reg_offset,
  input  [2:0]   io_in_bits_alignedType,
  input          io_in_bits_vecActive,
  input  [31:0]  io_in_bits_uop_instr,
  input  [49:0]  io_in_bits_uop_pc,
  input  [9:0]   io_in_bits_uop_foldpc,
  input          io_in_bits_uop_exceptionVec_4,
  input          io_in_bits_uop_exceptionVec_6,
  input          io_in_bits_uop_exceptionVec_7,
  input          io_in_bits_uop_exceptionVec_15,
  input          io_in_bits_uop_exceptionVec_23,
  input          io_in_bits_uop_isFetchMalAddr,
  input          io_in_bits_uop_hasException,
  input          io_in_bits_uop_preDecodeInfo_valid,
  input          io_in_bits_uop_preDecodeInfo_isRVC,
  input  [1:0]   io_in_bits_uop_preDecodeInfo_brType,
  input          io_in_bits_uop_preDecodeInfo_isCall,
  input          io_in_bits_uop_preDecodeInfo_isRet,
  input          io_in_bits_uop_pred_taken,
  input          io_in_bits_uop_crossPageIPFFix,
  input          io_in_bits_uop_ftqPtr_flag,
  input  [5:0]   io_in_bits_uop_ftqPtr_value,
  input  [3:0]   io_in_bits_uop_ftqOffset,
  input  [3:0]   io_in_bits_uop_srcType_0,
  input  [3:0]   io_in_bits_uop_srcType_1,
  input  [3:0]   io_in_bits_uop_srcType_2,
  input  [3:0]   io_in_bits_uop_srcType_3,
  input  [3:0]   io_in_bits_uop_srcType_4,
  input  [5:0]   io_in_bits_uop_ldest,
  input  [34:0]  io_in_bits_uop_fuType,
  input  [8:0]   io_in_bits_uop_fuOpType,
  input          io_in_bits_uop_rfWen,
  input          io_in_bits_uop_fpWen,
  input          io_in_bits_uop_vecWen,
  input          io_in_bits_uop_v0Wen,
  input          io_in_bits_uop_vlWen,
  input          io_in_bits_uop_isXSTrap,
  input          io_in_bits_uop_waitForward,
  input          io_in_bits_uop_blockBackward,
  input          io_in_bits_uop_canRobCompress,
  input  [3:0]   io_in_bits_uop_selImm,
  input  [1:0]   io_in_bits_uop_fpu_typeTagOut,
  input          io_in_bits_uop_fpu_wflags,
  input  [1:0]   io_in_bits_uop_fpu_typ,
  input  [1:0]   io_in_bits_uop_fpu_fmt,
  input  [2:0]   io_in_bits_uop_fpu_rm,
  input          io_in_bits_uop_vpu_vill,
  input          io_in_bits_uop_vpu_vma,
  input          io_in_bits_uop_vpu_vta,
  input  [1:0]   io_in_bits_uop_vpu_vsew,
  input  [2:0]   io_in_bits_uop_vpu_vlmul,
  input          io_in_bits_uop_vpu_specVill,
  input          io_in_bits_uop_vpu_specVma,
  input          io_in_bits_uop_vpu_specVta,
  input  [1:0]   io_in_bits_uop_vpu_specVsew,
  input  [2:0]   io_in_bits_uop_vpu_specVlmul,
  input          io_in_bits_uop_vpu_vm,
  input  [7:0]   io_in_bits_uop_vpu_vstart,
  input  [2:0]   io_in_bits_uop_vpu_frm,
  input          io_in_bits_uop_vpu_fpu_isFpToVecInst,
  input          io_in_bits_uop_vpu_fpu_isFP32Instr,
  input          io_in_bits_uop_vpu_fpu_isFP64Instr,
  input          io_in_bits_uop_vpu_fpu_isReduction,
  input          io_in_bits_uop_vpu_fpu_isFoldTo1_2,
  input          io_in_bits_uop_vpu_fpu_isFoldTo1_4,
  input          io_in_bits_uop_vpu_fpu_isFoldTo1_8,
  input  [1:0]   io_in_bits_uop_vpu_vxrm,
  input  [6:0]   io_in_bits_uop_vpu_vuopIdx,
  input          io_in_bits_uop_vpu_lastUop,
  input  [127:0] io_in_bits_uop_vpu_vmask,
  input  [7:0]   io_in_bits_uop_vpu_vl,
  input  [2:0]   io_in_bits_uop_vpu_nf,
  input  [1:0]   io_in_bits_uop_vpu_veew,
  input          io_in_bits_uop_vpu_isReverse,
  input          io_in_bits_uop_vpu_isExt,
  input          io_in_bits_uop_vpu_isNarrow,
  input          io_in_bits_uop_vpu_isDstMask,
  input          io_in_bits_uop_vpu_isOpMask,
  input          io_in_bits_uop_vpu_isMove,
  input          io_in_bits_uop_vpu_isDependOldVd,
  input          io_in_bits_uop_vpu_isWritePartVd,
  input          io_in_bits_uop_vpu_isVleff,
  input          io_in_bits_uop_vlsInstr,
  input          io_in_bits_uop_wfflags,
  input          io_in_bits_uop_isMove,
  input          io_in_bits_uop_isDropAmocasSta,
  input  [6:0]   io_in_bits_uop_uopIdx,
  input          io_in_bits_uop_isVset,
  input          io_in_bits_uop_firstUop,
  input          io_in_bits_uop_lastUop,
  input  [6:0]   io_in_bits_uop_numUops,
  input  [6:0]   io_in_bits_uop_numWB,
  input  [2:0]   io_in_bits_uop_commitType,
  input          io_in_bits_uop_srcState_0,
  input          io_in_bits_uop_srcState_1,
  input          io_in_bits_uop_srcState_2,
  input          io_in_bits_uop_srcState_3,
  input          io_in_bits_uop_srcState_4,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_0_0,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_0_1,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_0_2,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_1_0,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_1_1,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_1_2,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_2_0,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_2_1,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_2_2,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_3_0,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_3_1,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_3_2,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_4_0,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_4_1,
  input  [1:0]   io_in_bits_uop_srcLoadDependency_4_2,
  input  [7:0]   io_in_bits_uop_psrc_0,
  input  [7:0]   io_in_bits_uop_psrc_1,
  input  [7:0]   io_in_bits_uop_psrc_2,
  input  [7:0]   io_in_bits_uop_psrc_3,
  input  [7:0]   io_in_bits_uop_psrc_4,
  input  [7:0]   io_in_bits_uop_pdest,
  input          io_in_bits_uop_useRegCache_0,
  input          io_in_bits_uop_useRegCache_1,
  input  [4:0]   io_in_bits_uop_regCacheIdx_0,
  input  [4:0]   io_in_bits_uop_regCacheIdx_1,
  input          io_in_bits_uop_robIdx_flag,
  input  [7:0]   io_in_bits_uop_robIdx_value,
  input  [2:0]   io_in_bits_uop_instrSize,
  input          io_in_bits_uop_dirtyFs,
  input          io_in_bits_uop_dirtyVs,
  input  [3:0]   io_in_bits_uop_traceBlockInPipe_itype,
  input  [3:0]   io_in_bits_uop_traceBlockInPipe_iretire,
  input          io_in_bits_uop_traceBlockInPipe_ilastsize,
  input          io_in_bits_uop_eliminatedMove,
  input          io_in_bits_uop_snapshot,
  input          io_in_bits_uop_debugInfo_eliminatedMove,
  input  [63:0]  io_in_bits_uop_debugInfo_renameTime,
  input  [63:0]  io_in_bits_uop_debugInfo_dispatchTime,
  input  [63:0]  io_in_bits_uop_debugInfo_enqRsTime,
  input  [63:0]  io_in_bits_uop_debugInfo_selectTime,
  input  [63:0]  io_in_bits_uop_debugInfo_issueTime,
  input  [63:0]  io_in_bits_uop_debugInfo_writebackTime,
  input  [63:0]  io_in_bits_uop_debugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_bits_uop_debugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_bits_uop_debugInfo_tlbRespTime,
  input          io_in_bits_uop_storeSetHit,
  input          io_in_bits_uop_waitForRobIdx_flag,
  input  [7:0]   io_in_bits_uop_waitForRobIdx_value,
  input          io_in_bits_uop_loadWaitBit,
  input          io_in_bits_uop_loadWaitStrict,
  input  [4:0]   io_in_bits_uop_ssid,
  input          io_in_bits_uop_lqIdx_flag,
  input  [6:0]   io_in_bits_uop_lqIdx_value,
  input          io_in_bits_uop_sqIdx_flag,
  input  [5:0]   io_in_bits_uop_sqIdx_value,
  input          io_in_bits_uop_singleStep,
  input          io_in_bits_uop_replayInst,
  input  [34:0]  io_in_bits_uop_debug_fuType,
  input  [4:0]   io_in_bits_uop_numLsElem,
  input  [3:0]   io_in_bits_mBIndex,
  input  [7:0]   io_in_bits_elemIdx,
  input  [7:0]   io_in_bits_elemIdxInsideVd,
  input          io_out_ready,
  output         io_out_valid,
  output [63:0]  io_out_bits_vaddr,
  output [49:0]  io_out_bits_basevaddr,
  output [15:0]  io_out_bits_mask,
  output [3:0]   io_out_bits_reg_offset,
  output [2:0]   io_out_bits_alignedType,
  output         io_out_bits_vecActive,
  output [31:0]  io_out_bits_uop_instr,
  output [49:0]  io_out_bits_uop_pc,
  output [9:0]   io_out_bits_uop_foldpc,
  output         io_out_bits_uop_exceptionVec_4,
  output         io_out_bits_uop_exceptionVec_6,
  output         io_out_bits_uop_exceptionVec_7,
  output         io_out_bits_uop_exceptionVec_15,
  output         io_out_bits_uop_exceptionVec_23,
  output         io_out_bits_uop_isFetchMalAddr,
  output         io_out_bits_uop_hasException,
  output         io_out_bits_uop_preDecodeInfo_valid,
  output         io_out_bits_uop_preDecodeInfo_isRVC,
  output [1:0]   io_out_bits_uop_preDecodeInfo_brType,
  output         io_out_bits_uop_preDecodeInfo_isCall,
  output         io_out_bits_uop_preDecodeInfo_isRet,
  output         io_out_bits_uop_pred_taken,
  output         io_out_bits_uop_crossPageIPFFix,
  output         io_out_bits_uop_ftqPtr_flag,
  output [5:0]   io_out_bits_uop_ftqPtr_value,
  output [3:0]   io_out_bits_uop_ftqOffset,
  output [3:0]   io_out_bits_uop_srcType_0,
  output [3:0]   io_out_bits_uop_srcType_1,
  output [3:0]   io_out_bits_uop_srcType_2,
  output [3:0]   io_out_bits_uop_srcType_3,
  output [3:0]   io_out_bits_uop_srcType_4,
  output [5:0]   io_out_bits_uop_ldest,
  output [34:0]  io_out_bits_uop_fuType,
  output [8:0]   io_out_bits_uop_fuOpType,
  output         io_out_bits_uop_rfWen,
  output         io_out_bits_uop_fpWen,
  output         io_out_bits_uop_vecWen,
  output         io_out_bits_uop_v0Wen,
  output         io_out_bits_uop_vlWen,
  output         io_out_bits_uop_isXSTrap,
  output         io_out_bits_uop_waitForward,
  output         io_out_bits_uop_blockBackward,
  output         io_out_bits_uop_canRobCompress,
  output [3:0]   io_out_bits_uop_selImm,
  output [1:0]   io_out_bits_uop_fpu_typeTagOut,
  output         io_out_bits_uop_fpu_wflags,
  output [1:0]   io_out_bits_uop_fpu_typ,
  output [1:0]   io_out_bits_uop_fpu_fmt,
  output [2:0]   io_out_bits_uop_fpu_rm,
  output         io_out_bits_uop_vpu_vill,
  output         io_out_bits_uop_vpu_vma,
  output         io_out_bits_uop_vpu_vta,
  output [1:0]   io_out_bits_uop_vpu_vsew,
  output [2:0]   io_out_bits_uop_vpu_vlmul,
  output         io_out_bits_uop_vpu_specVill,
  output         io_out_bits_uop_vpu_specVma,
  output         io_out_bits_uop_vpu_specVta,
  output [1:0]   io_out_bits_uop_vpu_specVsew,
  output [2:0]   io_out_bits_uop_vpu_specVlmul,
  output         io_out_bits_uop_vpu_vm,
  output [7:0]   io_out_bits_uop_vpu_vstart,
  output [2:0]   io_out_bits_uop_vpu_frm,
  output         io_out_bits_uop_vpu_fpu_isFpToVecInst,
  output         io_out_bits_uop_vpu_fpu_isFP32Instr,
  output         io_out_bits_uop_vpu_fpu_isFP64Instr,
  output         io_out_bits_uop_vpu_fpu_isReduction,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_2,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_4,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_8,
  output [1:0]   io_out_bits_uop_vpu_vxrm,
  output [6:0]   io_out_bits_uop_vpu_vuopIdx,
  output         io_out_bits_uop_vpu_lastUop,
  output [127:0] io_out_bits_uop_vpu_vmask,
  output [7:0]   io_out_bits_uop_vpu_vl,
  output [2:0]   io_out_bits_uop_vpu_nf,
  output [1:0]   io_out_bits_uop_vpu_veew,
  output         io_out_bits_uop_vpu_isReverse,
  output         io_out_bits_uop_vpu_isExt,
  output         io_out_bits_uop_vpu_isNarrow,
  output         io_out_bits_uop_vpu_isDstMask,
  output         io_out_bits_uop_vpu_isOpMask,
  output         io_out_bits_uop_vpu_isMove,
  output         io_out_bits_uop_vpu_isDependOldVd,
  output         io_out_bits_uop_vpu_isWritePartVd,
  output         io_out_bits_uop_vpu_isVleff,
  output         io_out_bits_uop_vlsInstr,
  output         io_out_bits_uop_wfflags,
  output         io_out_bits_uop_isMove,
  output         io_out_bits_uop_isDropAmocasSta,
  output [6:0]   io_out_bits_uop_uopIdx,
  output         io_out_bits_uop_isVset,
  output         io_out_bits_uop_firstUop,
  output         io_out_bits_uop_lastUop,
  output [6:0]   io_out_bits_uop_numUops,
  output [6:0]   io_out_bits_uop_numWB,
  output [2:0]   io_out_bits_uop_commitType,
  output         io_out_bits_uop_srcState_0,
  output         io_out_bits_uop_srcState_1,
  output         io_out_bits_uop_srcState_2,
  output         io_out_bits_uop_srcState_3,
  output         io_out_bits_uop_srcState_4,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_4_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_4_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_4_2,
  output [7:0]   io_out_bits_uop_psrc_0,
  output [7:0]   io_out_bits_uop_psrc_1,
  output [7:0]   io_out_bits_uop_psrc_2,
  output [7:0]   io_out_bits_uop_psrc_3,
  output [7:0]   io_out_bits_uop_psrc_4,
  output [7:0]   io_out_bits_uop_pdest,
  output         io_out_bits_uop_useRegCache_0,
  output         io_out_bits_uop_useRegCache_1,
  output [4:0]   io_out_bits_uop_regCacheIdx_0,
  output [4:0]   io_out_bits_uop_regCacheIdx_1,
  output         io_out_bits_uop_robIdx_flag,
  output [7:0]   io_out_bits_uop_robIdx_value,
  output [2:0]   io_out_bits_uop_instrSize,
  output         io_out_bits_uop_dirtyFs,
  output         io_out_bits_uop_dirtyVs,
  output [3:0]   io_out_bits_uop_traceBlockInPipe_itype,
  output [3:0]   io_out_bits_uop_traceBlockInPipe_iretire,
  output         io_out_bits_uop_traceBlockInPipe_ilastsize,
  output         io_out_bits_uop_eliminatedMove,
  output         io_out_bits_uop_snapshot,
  output         io_out_bits_uop_debugInfo_eliminatedMove,
  output [63:0]  io_out_bits_uop_debugInfo_renameTime,
  output [63:0]  io_out_bits_uop_debugInfo_dispatchTime,
  output [63:0]  io_out_bits_uop_debugInfo_enqRsTime,
  output [63:0]  io_out_bits_uop_debugInfo_selectTime,
  output [63:0]  io_out_bits_uop_debugInfo_issueTime,
  output [63:0]  io_out_bits_uop_debugInfo_writebackTime,
  output [63:0]  io_out_bits_uop_debugInfo_runahead_checkpoint_id,
  output [63:0]  io_out_bits_uop_debugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_uop_debugInfo_tlbRespTime,
  output         io_out_bits_uop_storeSetHit,
  output         io_out_bits_uop_waitForRobIdx_flag,
  output [7:0]   io_out_bits_uop_waitForRobIdx_value,
  output         io_out_bits_uop_loadWaitBit,
  output         io_out_bits_uop_loadWaitStrict,
  output [4:0]   io_out_bits_uop_ssid,
  output         io_out_bits_uop_lqIdx_flag,
  output [6:0]   io_out_bits_uop_lqIdx_value,
  output         io_out_bits_uop_sqIdx_flag,
  output [5:0]   io_out_bits_uop_sqIdx_value,
  output         io_out_bits_uop_singleStep,
  output         io_out_bits_uop_replayInst,
  output [34:0]  io_out_bits_uop_debug_fuType,
  output [4:0]   io_out_bits_uop_numLsElem,
  output [3:0]   io_out_bits_mBIndex,
  output [7:0]   io_out_bits_elemIdx,
  output [7:0]   io_out_bits_elemIdxInsideVd,
  input          io_rightOutFire,
  input          io_isFlush
);

  reg          valid;
  wire         io_in_ready_0 = io_out_ready | ~valid;
  wire         _data_T = io_in_ready_0 & io_in_valid;
  reg  [63:0]  data_vaddr;
  reg  [49:0]  data_basevaddr;
  reg  [15:0]  data_mask;
  reg  [3:0]   data_reg_offset;
  reg  [2:0]   data_alignedType;
  reg          data_vecActive;
  reg  [31:0]  data_uop_instr;
  reg  [49:0]  data_uop_pc;
  reg  [9:0]   data_uop_foldpc;
  reg          data_uop_exceptionVec_4;
  reg          data_uop_exceptionVec_6;
  reg          data_uop_exceptionVec_7;
  reg          data_uop_exceptionVec_15;
  reg          data_uop_exceptionVec_23;
  reg          data_uop_isFetchMalAddr;
  reg          data_uop_hasException;
  reg          data_uop_preDecodeInfo_valid;
  reg          data_uop_preDecodeInfo_isRVC;
  reg  [1:0]   data_uop_preDecodeInfo_brType;
  reg          data_uop_preDecodeInfo_isCall;
  reg          data_uop_preDecodeInfo_isRet;
  reg          data_uop_pred_taken;
  reg          data_uop_crossPageIPFFix;
  reg          data_uop_ftqPtr_flag;
  reg  [5:0]   data_uop_ftqPtr_value;
  reg  [3:0]   data_uop_ftqOffset;
  reg  [3:0]   data_uop_srcType_0;
  reg  [3:0]   data_uop_srcType_1;
  reg  [3:0]   data_uop_srcType_2;
  reg  [3:0]   data_uop_srcType_3;
  reg  [3:0]   data_uop_srcType_4;
  reg  [5:0]   data_uop_ldest;
  reg  [34:0]  data_uop_fuType;
  reg  [8:0]   data_uop_fuOpType;
  reg          data_uop_rfWen;
  reg          data_uop_fpWen;
  reg          data_uop_vecWen;
  reg          data_uop_v0Wen;
  reg          data_uop_vlWen;
  reg          data_uop_isXSTrap;
  reg          data_uop_waitForward;
  reg          data_uop_blockBackward;
  reg          data_uop_canRobCompress;
  reg  [3:0]   data_uop_selImm;
  reg  [1:0]   data_uop_fpu_typeTagOut;
  reg          data_uop_fpu_wflags;
  reg  [1:0]   data_uop_fpu_typ;
  reg  [1:0]   data_uop_fpu_fmt;
  reg  [2:0]   data_uop_fpu_rm;
  reg          data_uop_vpu_vill;
  reg          data_uop_vpu_vma;
  reg          data_uop_vpu_vta;
  reg  [1:0]   data_uop_vpu_vsew;
  reg  [2:0]   data_uop_vpu_vlmul;
  reg          data_uop_vpu_specVill;
  reg          data_uop_vpu_specVma;
  reg          data_uop_vpu_specVta;
  reg  [1:0]   data_uop_vpu_specVsew;
  reg  [2:0]   data_uop_vpu_specVlmul;
  reg          data_uop_vpu_vm;
  reg  [7:0]   data_uop_vpu_vstart;
  reg  [2:0]   data_uop_vpu_frm;
  reg          data_uop_vpu_fpu_isFpToVecInst;
  reg          data_uop_vpu_fpu_isFP32Instr;
  reg          data_uop_vpu_fpu_isFP64Instr;
  reg          data_uop_vpu_fpu_isReduction;
  reg          data_uop_vpu_fpu_isFoldTo1_2;
  reg          data_uop_vpu_fpu_isFoldTo1_4;
  reg          data_uop_vpu_fpu_isFoldTo1_8;
  reg  [1:0]   data_uop_vpu_vxrm;
  reg  [6:0]   data_uop_vpu_vuopIdx;
  reg          data_uop_vpu_lastUop;
  reg  [127:0] data_uop_vpu_vmask;
  reg  [7:0]   data_uop_vpu_vl;
  reg  [2:0]   data_uop_vpu_nf;
  reg  [1:0]   data_uop_vpu_veew;
  reg          data_uop_vpu_isReverse;
  reg          data_uop_vpu_isExt;
  reg          data_uop_vpu_isNarrow;
  reg          data_uop_vpu_isDstMask;
  reg          data_uop_vpu_isOpMask;
  reg          data_uop_vpu_isMove;
  reg          data_uop_vpu_isDependOldVd;
  reg          data_uop_vpu_isWritePartVd;
  reg          data_uop_vpu_isVleff;
  reg          data_uop_vlsInstr;
  reg          data_uop_wfflags;
  reg          data_uop_isMove;
  reg          data_uop_isDropAmocasSta;
  reg  [6:0]   data_uop_uopIdx;
  reg          data_uop_isVset;
  reg          data_uop_firstUop;
  reg          data_uop_lastUop;
  reg  [6:0]   data_uop_numUops;
  reg  [6:0]   data_uop_numWB;
  reg  [2:0]   data_uop_commitType;
  reg          data_uop_srcState_0;
  reg          data_uop_srcState_1;
  reg          data_uop_srcState_2;
  reg          data_uop_srcState_3;
  reg          data_uop_srcState_4;
  reg  [1:0]   data_uop_srcLoadDependency_0_0;
  reg  [1:0]   data_uop_srcLoadDependency_0_1;
  reg  [1:0]   data_uop_srcLoadDependency_0_2;
  reg  [1:0]   data_uop_srcLoadDependency_1_0;
  reg  [1:0]   data_uop_srcLoadDependency_1_1;
  reg  [1:0]   data_uop_srcLoadDependency_1_2;
  reg  [1:0]   data_uop_srcLoadDependency_2_0;
  reg  [1:0]   data_uop_srcLoadDependency_2_1;
  reg  [1:0]   data_uop_srcLoadDependency_2_2;
  reg  [1:0]   data_uop_srcLoadDependency_3_0;
  reg  [1:0]   data_uop_srcLoadDependency_3_1;
  reg  [1:0]   data_uop_srcLoadDependency_3_2;
  reg  [1:0]   data_uop_srcLoadDependency_4_0;
  reg  [1:0]   data_uop_srcLoadDependency_4_1;
  reg  [1:0]   data_uop_srcLoadDependency_4_2;
  reg  [7:0]   data_uop_psrc_0;
  reg  [7:0]   data_uop_psrc_1;
  reg  [7:0]   data_uop_psrc_2;
  reg  [7:0]   data_uop_psrc_3;
  reg  [7:0]   data_uop_psrc_4;
  reg  [7:0]   data_uop_pdest;
  reg          data_uop_useRegCache_0;
  reg          data_uop_useRegCache_1;
  reg  [4:0]   data_uop_regCacheIdx_0;
  reg  [4:0]   data_uop_regCacheIdx_1;
  reg          data_uop_robIdx_flag;
  reg  [7:0]   data_uop_robIdx_value;
  reg  [2:0]   data_uop_instrSize;
  reg          data_uop_dirtyFs;
  reg          data_uop_dirtyVs;
  reg  [3:0]   data_uop_traceBlockInPipe_itype;
  reg  [3:0]   data_uop_traceBlockInPipe_iretire;
  reg          data_uop_traceBlockInPipe_ilastsize;
  reg          data_uop_eliminatedMove;
  reg          data_uop_snapshot;
  reg          data_uop_debugInfo_eliminatedMove;
  reg  [63:0]  data_uop_debugInfo_renameTime;
  reg  [63:0]  data_uop_debugInfo_dispatchTime;
  reg  [63:0]  data_uop_debugInfo_enqRsTime;
  reg  [63:0]  data_uop_debugInfo_selectTime;
  reg  [63:0]  data_uop_debugInfo_issueTime;
  reg  [63:0]  data_uop_debugInfo_writebackTime;
  reg  [63:0]  data_uop_debugInfo_runahead_checkpoint_id;
  reg  [63:0]  data_uop_debugInfo_tlbFirstReqTime;
  reg  [63:0]  data_uop_debugInfo_tlbRespTime;
  reg          data_uop_storeSetHit;
  reg          data_uop_waitForRobIdx_flag;
  reg  [7:0]   data_uop_waitForRobIdx_value;
  reg          data_uop_loadWaitBit;
  reg          data_uop_loadWaitStrict;
  reg  [4:0]   data_uop_ssid;
  reg          data_uop_lqIdx_flag;
  reg  [6:0]   data_uop_lqIdx_value;
  reg          data_uop_sqIdx_flag;
  reg  [5:0]   data_uop_sqIdx_value;
  reg          data_uop_singleStep;
  reg          data_uop_replayInst;
  reg  [34:0]  data_uop_debug_fuType;
  reg  [4:0]   data_uop_numLsElem;
  reg  [3:0]   data_mBIndex;
  reg  [7:0]   data_elemIdx;
  reg  [7:0]   data_elemIdxInsideVd;
  always @(posedge clock or posedge reset) begin
    if (reset)
      valid <= 1'h0;
    else
      valid <= ~io_isFlush & (_data_T | ~io_rightOutFire & valid);
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (_data_T) begin
      data_vaddr <= io_in_bits_vaddr;
      data_basevaddr <= io_in_bits_basevaddr;
      data_mask <= io_in_bits_mask;
      data_reg_offset <= io_in_bits_reg_offset;
      data_alignedType <= io_in_bits_alignedType;
      data_vecActive <= io_in_bits_vecActive;
      data_uop_instr <= io_in_bits_uop_instr;
      data_uop_pc <= io_in_bits_uop_pc;
      data_uop_foldpc <= io_in_bits_uop_foldpc;
      data_uop_exceptionVec_4 <= io_in_bits_uop_exceptionVec_4;
      data_uop_exceptionVec_6 <= io_in_bits_uop_exceptionVec_6;
      data_uop_exceptionVec_7 <= io_in_bits_uop_exceptionVec_7;
      data_uop_exceptionVec_15 <= io_in_bits_uop_exceptionVec_15;
      data_uop_exceptionVec_23 <= io_in_bits_uop_exceptionVec_23;
      data_uop_isFetchMalAddr <= io_in_bits_uop_isFetchMalAddr;
      data_uop_hasException <= io_in_bits_uop_hasException;
      data_uop_preDecodeInfo_valid <= io_in_bits_uop_preDecodeInfo_valid;
      data_uop_preDecodeInfo_isRVC <= io_in_bits_uop_preDecodeInfo_isRVC;
      data_uop_preDecodeInfo_brType <= io_in_bits_uop_preDecodeInfo_brType;
      data_uop_preDecodeInfo_isCall <= io_in_bits_uop_preDecodeInfo_isCall;
      data_uop_preDecodeInfo_isRet <= io_in_bits_uop_preDecodeInfo_isRet;
      data_uop_pred_taken <= io_in_bits_uop_pred_taken;
      data_uop_crossPageIPFFix <= io_in_bits_uop_crossPageIPFFix;
      data_uop_ftqPtr_flag <= io_in_bits_uop_ftqPtr_flag;
      data_uop_ftqPtr_value <= io_in_bits_uop_ftqPtr_value;
      data_uop_ftqOffset <= io_in_bits_uop_ftqOffset;
      data_uop_srcType_0 <= io_in_bits_uop_srcType_0;
      data_uop_srcType_1 <= io_in_bits_uop_srcType_1;
      data_uop_srcType_2 <= io_in_bits_uop_srcType_2;
      data_uop_srcType_3 <= io_in_bits_uop_srcType_3;
      data_uop_srcType_4 <= io_in_bits_uop_srcType_4;
      data_uop_ldest <= io_in_bits_uop_ldest;
      data_uop_fuType <= io_in_bits_uop_fuType;
      data_uop_fuOpType <= io_in_bits_uop_fuOpType;
      data_uop_rfWen <= io_in_bits_uop_rfWen;
      data_uop_fpWen <= io_in_bits_uop_fpWen;
      data_uop_vecWen <= io_in_bits_uop_vecWen;
      data_uop_v0Wen <= io_in_bits_uop_v0Wen;
      data_uop_vlWen <= io_in_bits_uop_vlWen;
      data_uop_isXSTrap <= io_in_bits_uop_isXSTrap;
      data_uop_waitForward <= io_in_bits_uop_waitForward;
      data_uop_blockBackward <= io_in_bits_uop_blockBackward;
      data_uop_canRobCompress <= io_in_bits_uop_canRobCompress;
      data_uop_selImm <= io_in_bits_uop_selImm;
      data_uop_fpu_typeTagOut <= io_in_bits_uop_fpu_typeTagOut;
      data_uop_fpu_wflags <= io_in_bits_uop_fpu_wflags;
      data_uop_fpu_typ <= io_in_bits_uop_fpu_typ;
      data_uop_fpu_fmt <= io_in_bits_uop_fpu_fmt;
      data_uop_fpu_rm <= io_in_bits_uop_fpu_rm;
      data_uop_vpu_vill <= io_in_bits_uop_vpu_vill;
      data_uop_vpu_vma <= io_in_bits_uop_vpu_vma;
      data_uop_vpu_vta <= io_in_bits_uop_vpu_vta;
      data_uop_vpu_vsew <= io_in_bits_uop_vpu_vsew;
      data_uop_vpu_vlmul <= io_in_bits_uop_vpu_vlmul;
      data_uop_vpu_specVill <= io_in_bits_uop_vpu_specVill;
      data_uop_vpu_specVma <= io_in_bits_uop_vpu_specVma;
      data_uop_vpu_specVta <= io_in_bits_uop_vpu_specVta;
      data_uop_vpu_specVsew <= io_in_bits_uop_vpu_specVsew;
      data_uop_vpu_specVlmul <= io_in_bits_uop_vpu_specVlmul;
      data_uop_vpu_vm <= io_in_bits_uop_vpu_vm;
      data_uop_vpu_vstart <= io_in_bits_uop_vpu_vstart;
      data_uop_vpu_frm <= io_in_bits_uop_vpu_frm;
      data_uop_vpu_fpu_isFpToVecInst <= io_in_bits_uop_vpu_fpu_isFpToVecInst;
      data_uop_vpu_fpu_isFP32Instr <= io_in_bits_uop_vpu_fpu_isFP32Instr;
      data_uop_vpu_fpu_isFP64Instr <= io_in_bits_uop_vpu_fpu_isFP64Instr;
      data_uop_vpu_fpu_isReduction <= io_in_bits_uop_vpu_fpu_isReduction;
      data_uop_vpu_fpu_isFoldTo1_2 <= io_in_bits_uop_vpu_fpu_isFoldTo1_2;
      data_uop_vpu_fpu_isFoldTo1_4 <= io_in_bits_uop_vpu_fpu_isFoldTo1_4;
      data_uop_vpu_fpu_isFoldTo1_8 <= io_in_bits_uop_vpu_fpu_isFoldTo1_8;
      data_uop_vpu_vxrm <= io_in_bits_uop_vpu_vxrm;
      data_uop_vpu_vuopIdx <= io_in_bits_uop_vpu_vuopIdx;
      data_uop_vpu_lastUop <= io_in_bits_uop_vpu_lastUop;
      data_uop_vpu_vmask <= io_in_bits_uop_vpu_vmask;
      data_uop_vpu_vl <= io_in_bits_uop_vpu_vl;
      data_uop_vpu_nf <= io_in_bits_uop_vpu_nf;
      data_uop_vpu_veew <= io_in_bits_uop_vpu_veew;
      data_uop_vpu_isReverse <= io_in_bits_uop_vpu_isReverse;
      data_uop_vpu_isExt <= io_in_bits_uop_vpu_isExt;
      data_uop_vpu_isNarrow <= io_in_bits_uop_vpu_isNarrow;
      data_uop_vpu_isDstMask <= io_in_bits_uop_vpu_isDstMask;
      data_uop_vpu_isOpMask <= io_in_bits_uop_vpu_isOpMask;
      data_uop_vpu_isMove <= io_in_bits_uop_vpu_isMove;
      data_uop_vpu_isDependOldVd <= io_in_bits_uop_vpu_isDependOldVd;
      data_uop_vpu_isWritePartVd <= io_in_bits_uop_vpu_isWritePartVd;
      data_uop_vpu_isVleff <= io_in_bits_uop_vpu_isVleff;
      data_uop_vlsInstr <= io_in_bits_uop_vlsInstr;
      data_uop_wfflags <= io_in_bits_uop_wfflags;
      data_uop_isMove <= io_in_bits_uop_isMove;
      data_uop_isDropAmocasSta <= io_in_bits_uop_isDropAmocasSta;
      data_uop_uopIdx <= io_in_bits_uop_uopIdx;
      data_uop_isVset <= io_in_bits_uop_isVset;
      data_uop_firstUop <= io_in_bits_uop_firstUop;
      data_uop_lastUop <= io_in_bits_uop_lastUop;
      data_uop_numUops <= io_in_bits_uop_numUops;
      data_uop_numWB <= io_in_bits_uop_numWB;
      data_uop_commitType <= io_in_bits_uop_commitType;
      data_uop_srcState_0 <= io_in_bits_uop_srcState_0;
      data_uop_srcState_1 <= io_in_bits_uop_srcState_1;
      data_uop_srcState_2 <= io_in_bits_uop_srcState_2;
      data_uop_srcState_3 <= io_in_bits_uop_srcState_3;
      data_uop_srcState_4 <= io_in_bits_uop_srcState_4;
      data_uop_srcLoadDependency_0_0 <= io_in_bits_uop_srcLoadDependency_0_0;
      data_uop_srcLoadDependency_0_1 <= io_in_bits_uop_srcLoadDependency_0_1;
      data_uop_srcLoadDependency_0_2 <= io_in_bits_uop_srcLoadDependency_0_2;
      data_uop_srcLoadDependency_1_0 <= io_in_bits_uop_srcLoadDependency_1_0;
      data_uop_srcLoadDependency_1_1 <= io_in_bits_uop_srcLoadDependency_1_1;
      data_uop_srcLoadDependency_1_2 <= io_in_bits_uop_srcLoadDependency_1_2;
      data_uop_srcLoadDependency_2_0 <= io_in_bits_uop_srcLoadDependency_2_0;
      data_uop_srcLoadDependency_2_1 <= io_in_bits_uop_srcLoadDependency_2_1;
      data_uop_srcLoadDependency_2_2 <= io_in_bits_uop_srcLoadDependency_2_2;
      data_uop_srcLoadDependency_3_0 <= io_in_bits_uop_srcLoadDependency_3_0;
      data_uop_srcLoadDependency_3_1 <= io_in_bits_uop_srcLoadDependency_3_1;
      data_uop_srcLoadDependency_3_2 <= io_in_bits_uop_srcLoadDependency_3_2;
      data_uop_srcLoadDependency_4_0 <= io_in_bits_uop_srcLoadDependency_4_0;
      data_uop_srcLoadDependency_4_1 <= io_in_bits_uop_srcLoadDependency_4_1;
      data_uop_srcLoadDependency_4_2 <= io_in_bits_uop_srcLoadDependency_4_2;
      data_uop_psrc_0 <= io_in_bits_uop_psrc_0;
      data_uop_psrc_1 <= io_in_bits_uop_psrc_1;
      data_uop_psrc_2 <= io_in_bits_uop_psrc_2;
      data_uop_psrc_3 <= io_in_bits_uop_psrc_3;
      data_uop_psrc_4 <= io_in_bits_uop_psrc_4;
      data_uop_pdest <= io_in_bits_uop_pdest;
      data_uop_useRegCache_0 <= io_in_bits_uop_useRegCache_0;
      data_uop_useRegCache_1 <= io_in_bits_uop_useRegCache_1;
      data_uop_regCacheIdx_0 <= io_in_bits_uop_regCacheIdx_0;
      data_uop_regCacheIdx_1 <= io_in_bits_uop_regCacheIdx_1;
      data_uop_robIdx_flag <= io_in_bits_uop_robIdx_flag;
      data_uop_robIdx_value <= io_in_bits_uop_robIdx_value;
      data_uop_instrSize <= io_in_bits_uop_instrSize;
      data_uop_dirtyFs <= io_in_bits_uop_dirtyFs;
      data_uop_dirtyVs <= io_in_bits_uop_dirtyVs;
      data_uop_traceBlockInPipe_itype <= io_in_bits_uop_traceBlockInPipe_itype;
      data_uop_traceBlockInPipe_iretire <= io_in_bits_uop_traceBlockInPipe_iretire;
      data_uop_traceBlockInPipe_ilastsize <= io_in_bits_uop_traceBlockInPipe_ilastsize;
      data_uop_eliminatedMove <= io_in_bits_uop_eliminatedMove;
      data_uop_snapshot <= io_in_bits_uop_snapshot;
      data_uop_debugInfo_eliminatedMove <= io_in_bits_uop_debugInfo_eliminatedMove;
      data_uop_debugInfo_renameTime <= io_in_bits_uop_debugInfo_renameTime;
      data_uop_debugInfo_dispatchTime <= io_in_bits_uop_debugInfo_dispatchTime;
      data_uop_debugInfo_enqRsTime <= io_in_bits_uop_debugInfo_enqRsTime;
      data_uop_debugInfo_selectTime <= io_in_bits_uop_debugInfo_selectTime;
      data_uop_debugInfo_issueTime <= io_in_bits_uop_debugInfo_issueTime;
      data_uop_debugInfo_writebackTime <= io_in_bits_uop_debugInfo_writebackTime;
      data_uop_debugInfo_runahead_checkpoint_id <=
        io_in_bits_uop_debugInfo_runahead_checkpoint_id;
      data_uop_debugInfo_tlbFirstReqTime <= io_in_bits_uop_debugInfo_tlbFirstReqTime;
      data_uop_debugInfo_tlbRespTime <= io_in_bits_uop_debugInfo_tlbRespTime;
      data_uop_storeSetHit <= io_in_bits_uop_storeSetHit;
      data_uop_waitForRobIdx_flag <= io_in_bits_uop_waitForRobIdx_flag;
      data_uop_waitForRobIdx_value <= io_in_bits_uop_waitForRobIdx_value;
      data_uop_loadWaitBit <= io_in_bits_uop_loadWaitBit;
      data_uop_loadWaitStrict <= io_in_bits_uop_loadWaitStrict;
      data_uop_ssid <= io_in_bits_uop_ssid;
      data_uop_lqIdx_flag <= io_in_bits_uop_lqIdx_flag;
      data_uop_lqIdx_value <= io_in_bits_uop_lqIdx_value;
      data_uop_sqIdx_flag <= io_in_bits_uop_sqIdx_flag;
      data_uop_sqIdx_value <= io_in_bits_uop_sqIdx_value;
      data_uop_singleStep <= io_in_bits_uop_singleStep;
      data_uop_replayInst <= io_in_bits_uop_replayInst;
      data_uop_debug_fuType <= io_in_bits_uop_debug_fuType;
      data_uop_numLsElem <= io_in_bits_uop_numLsElem;
      data_mBIndex <= io_in_bits_mBIndex;
      data_elemIdx <= io_in_bits_elemIdx;
      data_elemIdxInsideVd <= io_in_bits_elemIdxInsideVd;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:44];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h2D; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid = _RANDOM[6'h0][0];
        data_vaddr = {_RANDOM[6'h0][31:1], _RANDOM[6'h1], _RANDOM[6'h2][0]};
        data_basevaddr = {_RANDOM[6'h2][31:1], _RANDOM[6'h3][18:0]};
        data_mask = {_RANDOM[6'h3][31:19], _RANDOM[6'h4][2:0]};
        data_reg_offset = _RANDOM[6'h4][8:5];
        data_alignedType = _RANDOM[6'h4][11:9];
        data_vecActive = _RANDOM[6'h4][12];
        data_uop_instr = {_RANDOM[6'h4][31:15], _RANDOM[6'h5][14:0]};
        data_uop_pc = {_RANDOM[6'h5][31:15], _RANDOM[6'h6], _RANDOM[6'h7][0]};
        data_uop_foldpc = _RANDOM[6'h7][10:1];
        data_uop_exceptionVec_4 = _RANDOM[6'h7][15];
        data_uop_exceptionVec_6 = _RANDOM[6'h7][17];
        data_uop_exceptionVec_7 = _RANDOM[6'h7][18];
        data_uop_exceptionVec_15 = _RANDOM[6'h7][26];
        data_uop_exceptionVec_23 = _RANDOM[6'h8][2];
        data_uop_isFetchMalAddr = _RANDOM[6'h8][3];
        data_uop_hasException = _RANDOM[6'h8][4];
        data_uop_preDecodeInfo_valid = _RANDOM[6'h8][9];
        data_uop_preDecodeInfo_isRVC = _RANDOM[6'h8][10];
        data_uop_preDecodeInfo_brType = _RANDOM[6'h8][12:11];
        data_uop_preDecodeInfo_isCall = _RANDOM[6'h8][13];
        data_uop_preDecodeInfo_isRet = _RANDOM[6'h8][14];
        data_uop_pred_taken = _RANDOM[6'h8][15];
        data_uop_crossPageIPFFix = _RANDOM[6'h8][16];
        data_uop_ftqPtr_flag = _RANDOM[6'h8][17];
        data_uop_ftqPtr_value = _RANDOM[6'h8][23:18];
        data_uop_ftqOffset = _RANDOM[6'h8][27:24];
        data_uop_srcType_0 = _RANDOM[6'h8][31:28];
        data_uop_srcType_1 = _RANDOM[6'h9][3:0];
        data_uop_srcType_2 = _RANDOM[6'h9][7:4];
        data_uop_srcType_3 = _RANDOM[6'h9][11:8];
        data_uop_srcType_4 = _RANDOM[6'h9][15:12];
        data_uop_ldest = _RANDOM[6'h9][21:16];
        data_uop_fuType = {_RANDOM[6'h9][31:22], _RANDOM[6'hA][24:0]};
        data_uop_fuOpType = {_RANDOM[6'hA][31:25], _RANDOM[6'hB][1:0]};
        data_uop_rfWen = _RANDOM[6'hB][2];
        data_uop_fpWen = _RANDOM[6'hB][3];
        data_uop_vecWen = _RANDOM[6'hB][4];
        data_uop_v0Wen = _RANDOM[6'hB][5];
        data_uop_vlWen = _RANDOM[6'hB][6];
        data_uop_isXSTrap = _RANDOM[6'hB][7];
        data_uop_waitForward = _RANDOM[6'hB][8];
        data_uop_blockBackward = _RANDOM[6'hB][9];
        data_uop_canRobCompress = _RANDOM[6'hB][11];
        data_uop_selImm = _RANDOM[6'hB][15:12];
        data_uop_fpu_typeTagOut = _RANDOM[6'hC][17:16];
        data_uop_fpu_wflags = _RANDOM[6'hC][18];
        data_uop_fpu_typ = _RANDOM[6'hC][20:19];
        data_uop_fpu_fmt = _RANDOM[6'hC][22:21];
        data_uop_fpu_rm = _RANDOM[6'hC][25:23];
        data_uop_vpu_vill = _RANDOM[6'hC][26];
        data_uop_vpu_vma = _RANDOM[6'hC][27];
        data_uop_vpu_vta = _RANDOM[6'hC][28];
        data_uop_vpu_vsew = _RANDOM[6'hC][30:29];
        data_uop_vpu_vlmul = {_RANDOM[6'hC][31], _RANDOM[6'hD][1:0]};
        data_uop_vpu_specVill = _RANDOM[6'hD][2];
        data_uop_vpu_specVma = _RANDOM[6'hD][3];
        data_uop_vpu_specVta = _RANDOM[6'hD][4];
        data_uop_vpu_specVsew = _RANDOM[6'hD][6:5];
        data_uop_vpu_specVlmul = _RANDOM[6'hD][9:7];
        data_uop_vpu_vm = _RANDOM[6'hD][10];
        data_uop_vpu_vstart = _RANDOM[6'hD][18:11];
        data_uop_vpu_frm = _RANDOM[6'hD][21:19];
        data_uop_vpu_fpu_isFpToVecInst = _RANDOM[6'hD][22];
        data_uop_vpu_fpu_isFP32Instr = _RANDOM[6'hD][23];
        data_uop_vpu_fpu_isFP64Instr = _RANDOM[6'hD][24];
        data_uop_vpu_fpu_isReduction = _RANDOM[6'hD][25];
        data_uop_vpu_fpu_isFoldTo1_2 = _RANDOM[6'hD][26];
        data_uop_vpu_fpu_isFoldTo1_4 = _RANDOM[6'hD][27];
        data_uop_vpu_fpu_isFoldTo1_8 = _RANDOM[6'hD][28];
        data_uop_vpu_vxrm = _RANDOM[6'hD][30:29];
        data_uop_vpu_vuopIdx = {_RANDOM[6'hD][31], _RANDOM[6'hE][5:0]};
        data_uop_vpu_lastUop = _RANDOM[6'hE][6];
        data_uop_vpu_vmask =
          {_RANDOM[6'hE][31:7],
           _RANDOM[6'hF],
           _RANDOM[6'h10],
           _RANDOM[6'h11],
           _RANDOM[6'h12][6:0]};
        data_uop_vpu_vl = _RANDOM[6'h12][14:7];
        data_uop_vpu_nf = _RANDOM[6'h12][17:15];
        data_uop_vpu_veew = _RANDOM[6'h12][19:18];
        data_uop_vpu_isReverse = _RANDOM[6'h12][20];
        data_uop_vpu_isExt = _RANDOM[6'h12][21];
        data_uop_vpu_isNarrow = _RANDOM[6'h12][22];
        data_uop_vpu_isDstMask = _RANDOM[6'h12][23];
        data_uop_vpu_isOpMask = _RANDOM[6'h12][24];
        data_uop_vpu_isMove = _RANDOM[6'h12][25];
        data_uop_vpu_isDependOldVd = _RANDOM[6'h12][26];
        data_uop_vpu_isWritePartVd = _RANDOM[6'h12][27];
        data_uop_vpu_isVleff = _RANDOM[6'h12][28];
        data_uop_vlsInstr = _RANDOM[6'h12][29];
        data_uop_wfflags = _RANDOM[6'h12][30];
        data_uop_isMove = _RANDOM[6'h12][31];
        data_uop_isDropAmocasSta = _RANDOM[6'h13][0];
        data_uop_uopIdx = _RANDOM[6'h13][7:1];
        data_uop_isVset = _RANDOM[6'h13][8];
        data_uop_firstUop = _RANDOM[6'h13][9];
        data_uop_lastUop = _RANDOM[6'h13][10];
        data_uop_numUops = _RANDOM[6'h13][17:11];
        data_uop_numWB = _RANDOM[6'h13][24:18];
        data_uop_commitType = _RANDOM[6'h13][27:25];
        data_uop_srcState_0 = _RANDOM[6'h13][28];
        data_uop_srcState_1 = _RANDOM[6'h13][29];
        data_uop_srcState_2 = _RANDOM[6'h13][30];
        data_uop_srcState_3 = _RANDOM[6'h13][31];
        data_uop_srcState_4 = _RANDOM[6'h14][0];
        data_uop_srcLoadDependency_0_0 = _RANDOM[6'h14][2:1];
        data_uop_srcLoadDependency_0_1 = _RANDOM[6'h14][4:3];
        data_uop_srcLoadDependency_0_2 = _RANDOM[6'h14][6:5];
        data_uop_srcLoadDependency_1_0 = _RANDOM[6'h14][8:7];
        data_uop_srcLoadDependency_1_1 = _RANDOM[6'h14][10:9];
        data_uop_srcLoadDependency_1_2 = _RANDOM[6'h14][12:11];
        data_uop_srcLoadDependency_2_0 = _RANDOM[6'h14][14:13];
        data_uop_srcLoadDependency_2_1 = _RANDOM[6'h14][16:15];
        data_uop_srcLoadDependency_2_2 = _RANDOM[6'h14][18:17];
        data_uop_srcLoadDependency_3_0 = _RANDOM[6'h14][20:19];
        data_uop_srcLoadDependency_3_1 = _RANDOM[6'h14][22:21];
        data_uop_srcLoadDependency_3_2 = _RANDOM[6'h14][24:23];
        data_uop_srcLoadDependency_4_0 = _RANDOM[6'h14][26:25];
        data_uop_srcLoadDependency_4_1 = _RANDOM[6'h14][28:27];
        data_uop_srcLoadDependency_4_2 = _RANDOM[6'h14][30:29];
        data_uop_psrc_0 = {_RANDOM[6'h14][31], _RANDOM[6'h15][6:0]};
        data_uop_psrc_1 = _RANDOM[6'h15][14:7];
        data_uop_psrc_2 = _RANDOM[6'h15][22:15];
        data_uop_psrc_3 = _RANDOM[6'h15][30:23];
        data_uop_psrc_4 = {_RANDOM[6'h15][31], _RANDOM[6'h16][6:0]};
        data_uop_pdest = _RANDOM[6'h16][14:7];
        data_uop_useRegCache_0 = _RANDOM[6'h16][15];
        data_uop_useRegCache_1 = _RANDOM[6'h16][16];
        data_uop_regCacheIdx_0 = _RANDOM[6'h16][21:17];
        data_uop_regCacheIdx_1 = _RANDOM[6'h16][26:22];
        data_uop_robIdx_flag = _RANDOM[6'h16][27];
        data_uop_robIdx_value = {_RANDOM[6'h16][31:28], _RANDOM[6'h17][3:0]};
        data_uop_instrSize = _RANDOM[6'h17][6:4];
        data_uop_dirtyFs = _RANDOM[6'h17][7];
        data_uop_dirtyVs = _RANDOM[6'h17][8];
        data_uop_traceBlockInPipe_itype = _RANDOM[6'h17][12:9];
        data_uop_traceBlockInPipe_iretire = _RANDOM[6'h17][16:13];
        data_uop_traceBlockInPipe_ilastsize = _RANDOM[6'h17][17];
        data_uop_eliminatedMove = _RANDOM[6'h17][18];
        data_uop_snapshot = _RANDOM[6'h17][19];
        data_uop_debugInfo_eliminatedMove = _RANDOM[6'h17][20];
        data_uop_debugInfo_renameTime =
          {_RANDOM[6'h17][31:21], _RANDOM[6'h18], _RANDOM[6'h19][20:0]};
        data_uop_debugInfo_dispatchTime =
          {_RANDOM[6'h19][31:21], _RANDOM[6'h1A], _RANDOM[6'h1B][20:0]};
        data_uop_debugInfo_enqRsTime =
          {_RANDOM[6'h1B][31:21], _RANDOM[6'h1C], _RANDOM[6'h1D][20:0]};
        data_uop_debugInfo_selectTime =
          {_RANDOM[6'h1D][31:21], _RANDOM[6'h1E], _RANDOM[6'h1F][20:0]};
        data_uop_debugInfo_issueTime =
          {_RANDOM[6'h1F][31:21], _RANDOM[6'h20], _RANDOM[6'h21][20:0]};
        data_uop_debugInfo_writebackTime =
          {_RANDOM[6'h21][31:21], _RANDOM[6'h22], _RANDOM[6'h23][20:0]};
        data_uop_debugInfo_runahead_checkpoint_id =
          {_RANDOM[6'h23][31:21], _RANDOM[6'h24], _RANDOM[6'h25][20:0]};
        data_uop_debugInfo_tlbFirstReqTime =
          {_RANDOM[6'h25][31:21], _RANDOM[6'h26], _RANDOM[6'h27][20:0]};
        data_uop_debugInfo_tlbRespTime =
          {_RANDOM[6'h27][31:21], _RANDOM[6'h28], _RANDOM[6'h29][20:0]};
        data_uop_storeSetHit = _RANDOM[6'h29][21];
        data_uop_waitForRobIdx_flag = _RANDOM[6'h29][22];
        data_uop_waitForRobIdx_value = _RANDOM[6'h29][30:23];
        data_uop_loadWaitBit = _RANDOM[6'h29][31];
        data_uop_loadWaitStrict = _RANDOM[6'h2A][0];
        data_uop_ssid = _RANDOM[6'h2A][5:1];
        data_uop_lqIdx_flag = _RANDOM[6'h2A][6];
        data_uop_lqIdx_value = _RANDOM[6'h2A][13:7];
        data_uop_sqIdx_flag = _RANDOM[6'h2A][14];
        data_uop_sqIdx_value = _RANDOM[6'h2A][20:15];
        data_uop_singleStep = _RANDOM[6'h2A][21];
        data_uop_replayInst = _RANDOM[6'h2A][22];
        data_uop_debug_fuType = {_RANDOM[6'h2A][31:23], _RANDOM[6'h2B][25:0]};
        data_uop_numLsElem = _RANDOM[6'h2B][30:26];
        data_mBIndex = _RANDOM[6'h2C][3:0];
        data_elemIdx = _RANDOM[6'h2C][11:4];
        data_elemIdxInsideVd = _RANDOM[6'h2C][19:12];
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        valid = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = io_in_ready_0;
  assign io_out_valid = valid;
  assign io_out_bits_vaddr = data_vaddr;
  assign io_out_bits_basevaddr = data_basevaddr;
  assign io_out_bits_mask = data_mask;
  assign io_out_bits_reg_offset = data_reg_offset;
  assign io_out_bits_alignedType = data_alignedType;
  assign io_out_bits_vecActive = data_vecActive;
  assign io_out_bits_uop_instr = data_uop_instr;
  assign io_out_bits_uop_pc = data_uop_pc;
  assign io_out_bits_uop_foldpc = data_uop_foldpc;
  assign io_out_bits_uop_exceptionVec_4 = data_uop_exceptionVec_4;
  assign io_out_bits_uop_exceptionVec_6 = data_uop_exceptionVec_6;
  assign io_out_bits_uop_exceptionVec_7 = data_uop_exceptionVec_7;
  assign io_out_bits_uop_exceptionVec_15 = data_uop_exceptionVec_15;
  assign io_out_bits_uop_exceptionVec_23 = data_uop_exceptionVec_23;
  assign io_out_bits_uop_isFetchMalAddr = data_uop_isFetchMalAddr;
  assign io_out_bits_uop_hasException = data_uop_hasException;
  assign io_out_bits_uop_preDecodeInfo_valid = data_uop_preDecodeInfo_valid;
  assign io_out_bits_uop_preDecodeInfo_isRVC = data_uop_preDecodeInfo_isRVC;
  assign io_out_bits_uop_preDecodeInfo_brType = data_uop_preDecodeInfo_brType;
  assign io_out_bits_uop_preDecodeInfo_isCall = data_uop_preDecodeInfo_isCall;
  assign io_out_bits_uop_preDecodeInfo_isRet = data_uop_preDecodeInfo_isRet;
  assign io_out_bits_uop_pred_taken = data_uop_pred_taken;
  assign io_out_bits_uop_crossPageIPFFix = data_uop_crossPageIPFFix;
  assign io_out_bits_uop_ftqPtr_flag = data_uop_ftqPtr_flag;
  assign io_out_bits_uop_ftqPtr_value = data_uop_ftqPtr_value;
  assign io_out_bits_uop_ftqOffset = data_uop_ftqOffset;
  assign io_out_bits_uop_srcType_0 = data_uop_srcType_0;
  assign io_out_bits_uop_srcType_1 = data_uop_srcType_1;
  assign io_out_bits_uop_srcType_2 = data_uop_srcType_2;
  assign io_out_bits_uop_srcType_3 = data_uop_srcType_3;
  assign io_out_bits_uop_srcType_4 = data_uop_srcType_4;
  assign io_out_bits_uop_ldest = data_uop_ldest;
  assign io_out_bits_uop_fuType = data_uop_fuType;
  assign io_out_bits_uop_fuOpType = data_uop_fuOpType;
  assign io_out_bits_uop_rfWen = data_uop_rfWen;
  assign io_out_bits_uop_fpWen = data_uop_fpWen;
  assign io_out_bits_uop_vecWen = data_uop_vecWen;
  assign io_out_bits_uop_v0Wen = data_uop_v0Wen;
  assign io_out_bits_uop_vlWen = data_uop_vlWen;
  assign io_out_bits_uop_isXSTrap = data_uop_isXSTrap;
  assign io_out_bits_uop_waitForward = data_uop_waitForward;
  assign io_out_bits_uop_blockBackward = data_uop_blockBackward;
  assign io_out_bits_uop_canRobCompress = data_uop_canRobCompress;
  assign io_out_bits_uop_selImm = data_uop_selImm;
  assign io_out_bits_uop_fpu_typeTagOut = data_uop_fpu_typeTagOut;
  assign io_out_bits_uop_fpu_wflags = data_uop_fpu_wflags;
  assign io_out_bits_uop_fpu_typ = data_uop_fpu_typ;
  assign io_out_bits_uop_fpu_fmt = data_uop_fpu_fmt;
  assign io_out_bits_uop_fpu_rm = data_uop_fpu_rm;
  assign io_out_bits_uop_vpu_vill = data_uop_vpu_vill;
  assign io_out_bits_uop_vpu_vma = data_uop_vpu_vma;
  assign io_out_bits_uop_vpu_vta = data_uop_vpu_vta;
  assign io_out_bits_uop_vpu_vsew = data_uop_vpu_vsew;
  assign io_out_bits_uop_vpu_vlmul = data_uop_vpu_vlmul;
  assign io_out_bits_uop_vpu_specVill = data_uop_vpu_specVill;
  assign io_out_bits_uop_vpu_specVma = data_uop_vpu_specVma;
  assign io_out_bits_uop_vpu_specVta = data_uop_vpu_specVta;
  assign io_out_bits_uop_vpu_specVsew = data_uop_vpu_specVsew;
  assign io_out_bits_uop_vpu_specVlmul = data_uop_vpu_specVlmul;
  assign io_out_bits_uop_vpu_vm = data_uop_vpu_vm;
  assign io_out_bits_uop_vpu_vstart = data_uop_vpu_vstart;
  assign io_out_bits_uop_vpu_frm = data_uop_vpu_frm;
  assign io_out_bits_uop_vpu_fpu_isFpToVecInst = data_uop_vpu_fpu_isFpToVecInst;
  assign io_out_bits_uop_vpu_fpu_isFP32Instr = data_uop_vpu_fpu_isFP32Instr;
  assign io_out_bits_uop_vpu_fpu_isFP64Instr = data_uop_vpu_fpu_isFP64Instr;
  assign io_out_bits_uop_vpu_fpu_isReduction = data_uop_vpu_fpu_isReduction;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_2 = data_uop_vpu_fpu_isFoldTo1_2;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_4 = data_uop_vpu_fpu_isFoldTo1_4;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_8 = data_uop_vpu_fpu_isFoldTo1_8;
  assign io_out_bits_uop_vpu_vxrm = data_uop_vpu_vxrm;
  assign io_out_bits_uop_vpu_vuopIdx = data_uop_vpu_vuopIdx;
  assign io_out_bits_uop_vpu_lastUop = data_uop_vpu_lastUop;
  assign io_out_bits_uop_vpu_vmask = data_uop_vpu_vmask;
  assign io_out_bits_uop_vpu_vl = data_uop_vpu_vl;
  assign io_out_bits_uop_vpu_nf = data_uop_vpu_nf;
  assign io_out_bits_uop_vpu_veew = data_uop_vpu_veew;
  assign io_out_bits_uop_vpu_isReverse = data_uop_vpu_isReverse;
  assign io_out_bits_uop_vpu_isExt = data_uop_vpu_isExt;
  assign io_out_bits_uop_vpu_isNarrow = data_uop_vpu_isNarrow;
  assign io_out_bits_uop_vpu_isDstMask = data_uop_vpu_isDstMask;
  assign io_out_bits_uop_vpu_isOpMask = data_uop_vpu_isOpMask;
  assign io_out_bits_uop_vpu_isMove = data_uop_vpu_isMove;
  assign io_out_bits_uop_vpu_isDependOldVd = data_uop_vpu_isDependOldVd;
  assign io_out_bits_uop_vpu_isWritePartVd = data_uop_vpu_isWritePartVd;
  assign io_out_bits_uop_vpu_isVleff = data_uop_vpu_isVleff;
  assign io_out_bits_uop_vlsInstr = data_uop_vlsInstr;
  assign io_out_bits_uop_wfflags = data_uop_wfflags;
  assign io_out_bits_uop_isMove = data_uop_isMove;
  assign io_out_bits_uop_isDropAmocasSta = data_uop_isDropAmocasSta;
  assign io_out_bits_uop_uopIdx = data_uop_uopIdx;
  assign io_out_bits_uop_isVset = data_uop_isVset;
  assign io_out_bits_uop_firstUop = data_uop_firstUop;
  assign io_out_bits_uop_lastUop = data_uop_lastUop;
  assign io_out_bits_uop_numUops = data_uop_numUops;
  assign io_out_bits_uop_numWB = data_uop_numWB;
  assign io_out_bits_uop_commitType = data_uop_commitType;
  assign io_out_bits_uop_srcState_0 = data_uop_srcState_0;
  assign io_out_bits_uop_srcState_1 = data_uop_srcState_1;
  assign io_out_bits_uop_srcState_2 = data_uop_srcState_2;
  assign io_out_bits_uop_srcState_3 = data_uop_srcState_3;
  assign io_out_bits_uop_srcState_4 = data_uop_srcState_4;
  assign io_out_bits_uop_srcLoadDependency_0_0 = data_uop_srcLoadDependency_0_0;
  assign io_out_bits_uop_srcLoadDependency_0_1 = data_uop_srcLoadDependency_0_1;
  assign io_out_bits_uop_srcLoadDependency_0_2 = data_uop_srcLoadDependency_0_2;
  assign io_out_bits_uop_srcLoadDependency_1_0 = data_uop_srcLoadDependency_1_0;
  assign io_out_bits_uop_srcLoadDependency_1_1 = data_uop_srcLoadDependency_1_1;
  assign io_out_bits_uop_srcLoadDependency_1_2 = data_uop_srcLoadDependency_1_2;
  assign io_out_bits_uop_srcLoadDependency_2_0 = data_uop_srcLoadDependency_2_0;
  assign io_out_bits_uop_srcLoadDependency_2_1 = data_uop_srcLoadDependency_2_1;
  assign io_out_bits_uop_srcLoadDependency_2_2 = data_uop_srcLoadDependency_2_2;
  assign io_out_bits_uop_srcLoadDependency_3_0 = data_uop_srcLoadDependency_3_0;
  assign io_out_bits_uop_srcLoadDependency_3_1 = data_uop_srcLoadDependency_3_1;
  assign io_out_bits_uop_srcLoadDependency_3_2 = data_uop_srcLoadDependency_3_2;
  assign io_out_bits_uop_srcLoadDependency_4_0 = data_uop_srcLoadDependency_4_0;
  assign io_out_bits_uop_srcLoadDependency_4_1 = data_uop_srcLoadDependency_4_1;
  assign io_out_bits_uop_srcLoadDependency_4_2 = data_uop_srcLoadDependency_4_2;
  assign io_out_bits_uop_psrc_0 = data_uop_psrc_0;
  assign io_out_bits_uop_psrc_1 = data_uop_psrc_1;
  assign io_out_bits_uop_psrc_2 = data_uop_psrc_2;
  assign io_out_bits_uop_psrc_3 = data_uop_psrc_3;
  assign io_out_bits_uop_psrc_4 = data_uop_psrc_4;
  assign io_out_bits_uop_pdest = data_uop_pdest;
  assign io_out_bits_uop_useRegCache_0 = data_uop_useRegCache_0;
  assign io_out_bits_uop_useRegCache_1 = data_uop_useRegCache_1;
  assign io_out_bits_uop_regCacheIdx_0 = data_uop_regCacheIdx_0;
  assign io_out_bits_uop_regCacheIdx_1 = data_uop_regCacheIdx_1;
  assign io_out_bits_uop_robIdx_flag = data_uop_robIdx_flag;
  assign io_out_bits_uop_robIdx_value = data_uop_robIdx_value;
  assign io_out_bits_uop_instrSize = data_uop_instrSize;
  assign io_out_bits_uop_dirtyFs = data_uop_dirtyFs;
  assign io_out_bits_uop_dirtyVs = data_uop_dirtyVs;
  assign io_out_bits_uop_traceBlockInPipe_itype = data_uop_traceBlockInPipe_itype;
  assign io_out_bits_uop_traceBlockInPipe_iretire = data_uop_traceBlockInPipe_iretire;
  assign io_out_bits_uop_traceBlockInPipe_ilastsize = data_uop_traceBlockInPipe_ilastsize;
  assign io_out_bits_uop_eliminatedMove = data_uop_eliminatedMove;
  assign io_out_bits_uop_snapshot = data_uop_snapshot;
  assign io_out_bits_uop_debugInfo_eliminatedMove = data_uop_debugInfo_eliminatedMove;
  assign io_out_bits_uop_debugInfo_renameTime = data_uop_debugInfo_renameTime;
  assign io_out_bits_uop_debugInfo_dispatchTime = data_uop_debugInfo_dispatchTime;
  assign io_out_bits_uop_debugInfo_enqRsTime = data_uop_debugInfo_enqRsTime;
  assign io_out_bits_uop_debugInfo_selectTime = data_uop_debugInfo_selectTime;
  assign io_out_bits_uop_debugInfo_issueTime = data_uop_debugInfo_issueTime;
  assign io_out_bits_uop_debugInfo_writebackTime = data_uop_debugInfo_writebackTime;
  assign io_out_bits_uop_debugInfo_runahead_checkpoint_id =
    data_uop_debugInfo_runahead_checkpoint_id;
  assign io_out_bits_uop_debugInfo_tlbFirstReqTime = data_uop_debugInfo_tlbFirstReqTime;
  assign io_out_bits_uop_debugInfo_tlbRespTime = data_uop_debugInfo_tlbRespTime;
  assign io_out_bits_uop_storeSetHit = data_uop_storeSetHit;
  assign io_out_bits_uop_waitForRobIdx_flag = data_uop_waitForRobIdx_flag;
  assign io_out_bits_uop_waitForRobIdx_value = data_uop_waitForRobIdx_value;
  assign io_out_bits_uop_loadWaitBit = data_uop_loadWaitBit;
  assign io_out_bits_uop_loadWaitStrict = data_uop_loadWaitStrict;
  assign io_out_bits_uop_ssid = data_uop_ssid;
  assign io_out_bits_uop_lqIdx_flag = data_uop_lqIdx_flag;
  assign io_out_bits_uop_lqIdx_value = data_uop_lqIdx_value;
  assign io_out_bits_uop_sqIdx_flag = data_uop_sqIdx_flag;
  assign io_out_bits_uop_sqIdx_value = data_uop_sqIdx_value;
  assign io_out_bits_uop_singleStep = data_uop_singleStep;
  assign io_out_bits_uop_replayInst = data_uop_replayInst;
  assign io_out_bits_uop_debug_fuType = data_uop_debug_fuType;
  assign io_out_bits_uop_numLsElem = data_uop_numLsElem;
  assign io_out_bits_mBIndex = data_mBIndex;
  assign io_out_bits_elemIdx = data_elemIdx;
  assign io_out_bits_elemIdxInsideVd = data_elemIdxInsideVd;
endmodule

