// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module StoreMisalignBuffer(
  input         clock,
  input         reset,
  input         io_redirect_valid,
  input         io_redirect_bits_robIdx_flag,
  input  [7:0]  io_redirect_bits_robIdx_value,
  input         io_redirect_bits_level,
  output        io_req_0_ready,
  input         io_req_0_valid,
  input  [3:0]  io_req_0_bits_uop_trigger,
  input         io_req_0_bits_uop_ftqPtr_flag,
  input  [5:0]  io_req_0_bits_uop_ftqPtr_value,
  input  [3:0]  io_req_0_bits_uop_ftqOffset,
  input  [34:0] io_req_0_bits_uop_fuType,
  input  [8:0]  io_req_0_bits_uop_fuOpType,
  input         io_req_0_bits_uop_rfWen,
  input  [7:0]  io_req_0_bits_uop_vpu_vstart,
  input  [2:0]  io_req_0_bits_uop_vpu_nf,
  input  [1:0]  io_req_0_bits_uop_vpu_veew,
  input  [6:0]  io_req_0_bits_uop_uopIdx,
  input  [7:0]  io_req_0_bits_uop_pdest,
  input         io_req_0_bits_uop_robIdx_flag,
  input  [7:0]  io_req_0_bits_uop_robIdx_value,
  input         io_req_0_bits_uop_debugInfo_eliminatedMove,
  input  [63:0] io_req_0_bits_uop_debugInfo_renameTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_dispatchTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_selectTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_issueTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_writebackTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_runahead_checkpoint_id,
  input  [63:0] io_req_0_bits_uop_debugInfo_tlbFirstReqTime,
  input  [63:0] io_req_0_bits_uop_debugInfo_tlbRespTime,
  input         io_req_0_bits_uop_lqIdx_flag,
  input  [6:0]  io_req_0_bits_uop_lqIdx_value,
  input         io_req_0_bits_uop_sqIdx_flag,
  input  [5:0]  io_req_0_bits_uop_sqIdx_value,
  input  [49:0] io_req_0_bits_vaddr,
  input         io_req_0_bits_vaNeedExt,
  input  [47:0] io_req_0_bits_paddr,
  input  [63:0] io_req_0_bits_gpaddr,
  input         io_req_0_bits_isForVSnonLeafPTE,
  input  [15:0] io_req_0_bits_mask,
  input         io_req_0_bits_isvec,
  input  [7:0]  io_req_0_bits_elemIdx,
  input  [2:0]  io_req_0_bits_alignedType,
  input  [3:0]  io_req_0_bits_mbIndex,
  output        io_req_1_ready,
  input         io_req_1_valid,
  input  [3:0]  io_req_1_bits_uop_trigger,
  input         io_req_1_bits_uop_ftqPtr_flag,
  input  [5:0]  io_req_1_bits_uop_ftqPtr_value,
  input  [3:0]  io_req_1_bits_uop_ftqOffset,
  input  [34:0] io_req_1_bits_uop_fuType,
  input  [8:0]  io_req_1_bits_uop_fuOpType,
  input         io_req_1_bits_uop_rfWen,
  input  [7:0]  io_req_1_bits_uop_vpu_vstart,
  input  [2:0]  io_req_1_bits_uop_vpu_nf,
  input  [1:0]  io_req_1_bits_uop_vpu_veew,
  input  [6:0]  io_req_1_bits_uop_uopIdx,
  input  [7:0]  io_req_1_bits_uop_pdest,
  input         io_req_1_bits_uop_robIdx_flag,
  input  [7:0]  io_req_1_bits_uop_robIdx_value,
  input         io_req_1_bits_uop_debugInfo_eliminatedMove,
  input  [63:0] io_req_1_bits_uop_debugInfo_renameTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_dispatchTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_enqRsTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_selectTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_issueTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_writebackTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_runahead_checkpoint_id,
  input  [63:0] io_req_1_bits_uop_debugInfo_tlbFirstReqTime,
  input  [63:0] io_req_1_bits_uop_debugInfo_tlbRespTime,
  input         io_req_1_bits_uop_lqIdx_flag,
  input  [6:0]  io_req_1_bits_uop_lqIdx_value,
  input         io_req_1_bits_uop_sqIdx_flag,
  input  [5:0]  io_req_1_bits_uop_sqIdx_value,
  input  [49:0] io_req_1_bits_vaddr,
  input         io_req_1_bits_vaNeedExt,
  input  [47:0] io_req_1_bits_paddr,
  input  [63:0] io_req_1_bits_gpaddr,
  input         io_req_1_bits_isForVSnonLeafPTE,
  input  [15:0] io_req_1_bits_mask,
  input         io_req_1_bits_isvec,
  input  [7:0]  io_req_1_bits_elemIdx,
  input  [2:0]  io_req_1_bits_alignedType,
  input  [3:0]  io_req_1_bits_mbIndex,
  input         io_rob_pendingst,
  input         io_rob_pendingPtr_flag,
  input  [7:0]  io_rob_pendingPtr_value,
  input         io_splitStoreReq_ready,
  output        io_splitStoreReq_valid,
  output        io_splitStoreReq_bits_uop_ftqPtr_flag,
  output [5:0]  io_splitStoreReq_bits_uop_ftqPtr_value,
  output [3:0]  io_splitStoreReq_bits_uop_ftqOffset,
  output [34:0] io_splitStoreReq_bits_uop_fuType,
  output [8:0]  io_splitStoreReq_bits_uop_fuOpType,
  output        io_splitStoreReq_bits_uop_rfWen,
  output [7:0]  io_splitStoreReq_bits_uop_vpu_vstart,
  output [2:0]  io_splitStoreReq_bits_uop_vpu_nf,
  output [1:0]  io_splitStoreReq_bits_uop_vpu_veew,
  output [6:0]  io_splitStoreReq_bits_uop_uopIdx,
  output [7:0]  io_splitStoreReq_bits_uop_pdest,
  output        io_splitStoreReq_bits_uop_robIdx_flag,
  output [7:0]  io_splitStoreReq_bits_uop_robIdx_value,
  output        io_splitStoreReq_bits_uop_debugInfo_eliminatedMove,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_renameTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_dispatchTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_selectTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_issueTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_writebackTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_runahead_checkpoint_id,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_tlbFirstReqTime,
  output [63:0] io_splitStoreReq_bits_uop_debugInfo_tlbRespTime,
  output        io_splitStoreReq_bits_uop_lqIdx_flag,
  output [6:0]  io_splitStoreReq_bits_uop_lqIdx_value,
  output        io_splitStoreReq_bits_uop_sqIdx_flag,
  output [5:0]  io_splitStoreReq_bits_uop_sqIdx_value,
  output [49:0] io_splitStoreReq_bits_vaddr,
  output [15:0] io_splitStoreReq_bits_mask,
  output        io_splitStoreReq_bits_isvec,
  output        io_splitStoreReq_bits_is128bit,
  output        io_splitStoreReq_bits_isFinalSplit,
  input         io_splitStoreResp_valid,
  input         io_splitStoreResp_bits_uop_exceptionVec_3,
  input         io_splitStoreResp_bits_uop_exceptionVec_6,
  input         io_splitStoreResp_bits_uop_exceptionVec_7,
  input         io_splitStoreResp_bits_uop_exceptionVec_15,
  input         io_splitStoreResp_bits_uop_exceptionVec_23,
  input  [47:0] io_splitStoreResp_bits_paddr,
  input         io_splitStoreResp_bits_mmio,
  input         io_splitStoreResp_bits_need_rep,
  input         io_writeBack_ready,
  output        io_writeBack_valid,
  output        io_writeBack_bits_uop_exceptionVec_3,
  output        io_writeBack_bits_uop_exceptionVec_6,
  output        io_writeBack_bits_uop_exceptionVec_7,
  output        io_writeBack_bits_uop_exceptionVec_15,
  output        io_writeBack_bits_uop_exceptionVec_23,
  output [3:0]  io_writeBack_bits_uop_trigger,
  output        io_writeBack_bits_uop_rfWen,
  output        io_writeBack_bits_uop_flushPipe,
  output [7:0]  io_writeBack_bits_uop_pdest,
  output        io_writeBack_bits_uop_robIdx_flag,
  output [7:0]  io_writeBack_bits_uop_robIdx_value,
  output        io_writeBack_bits_uop_debugInfo_eliminatedMove,
  output [63:0] io_writeBack_bits_uop_debugInfo_renameTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_dispatchTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_enqRsTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_selectTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_issueTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_writebackTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_runahead_checkpoint_id,
  output [63:0] io_writeBack_bits_uop_debugInfo_tlbFirstReqTime,
  output [63:0] io_writeBack_bits_uop_debugInfo_tlbRespTime,
  output        io_writeBack_bits_uop_sqIdx_flag,
  output [5:0]  io_writeBack_bits_uop_sqIdx_value,
  output        io_writeBack_bits_debug_isMMIO,
  output [47:0] io_writeBack_bits_debug_paddr,
  output [49:0] io_writeBack_bits_debug_vaddr,
  output        io_vecWriteBack_0_valid,
  output [3:0]  io_vecWriteBack_0_bits_mBIndex,
  output        io_vecWriteBack_0_bits_exceptionVec_3,
  output        io_vecWriteBack_0_bits_exceptionVec_6,
  output        io_vecWriteBack_0_bits_exceptionVec_7,
  output        io_vecWriteBack_0_bits_exceptionVec_15,
  output        io_vecWriteBack_0_bits_exceptionVec_23,
  output [63:0] io_vecWriteBack_0_bits_vaddr,
  output        io_vecWriteBack_0_bits_vaNeedExt,
  output [63:0] io_vecWriteBack_0_bits_gpaddr,
  output        io_vecWriteBack_0_bits_isForVSnonLeafPTE,
  output [7:0]  io_vecWriteBack_0_bits_vstart,
  output [7:0]  io_vecWriteBack_0_bits_elemIdx,
  output [15:0] io_vecWriteBack_0_bits_mask,
  output        io_vecWriteBack_1_valid,
  output [3:0]  io_vecWriteBack_1_bits_mBIndex,
  output        io_vecWriteBack_1_bits_exceptionVec_3,
  output        io_vecWriteBack_1_bits_exceptionVec_6,
  output        io_vecWriteBack_1_bits_exceptionVec_7,
  output        io_vecWriteBack_1_bits_exceptionVec_15,
  output        io_vecWriteBack_1_bits_exceptionVec_23,
  output [63:0] io_vecWriteBack_1_bits_vaddr,
  output        io_vecWriteBack_1_bits_vaNeedExt,
  output [63:0] io_vecWriteBack_1_bits_gpaddr,
  output        io_vecWriteBack_1_bits_isForVSnonLeafPTE,
  output [7:0]  io_vecWriteBack_1_bits_vstart,
  output [7:0]  io_vecWriteBack_1_bits_elemIdx,
  output [15:0] io_vecWriteBack_1_bits_mask,
  input         io_storeOutValid,
  input         io_storeVecOutValid,
  output        io_sqControl_toStoreQueue_crossPageWithHit,
  output        io_sqControl_toStoreQueue_crossPageCanDeq,
  output [47:0] io_sqControl_toStoreQueue_paddr,
  output        io_sqControl_toStoreQueue_withSameUop,
  input         io_sqControl_toStoreMisalignBuffer_sqPtr_flag,
  input  [5:0]  io_sqControl_toStoreMisalignBuffer_sqPtr_value,
  input         io_sqControl_toStoreMisalignBuffer_doDeq,
  input  [6:0]  io_sqControl_toStoreMisalignBuffer_uop_uopIdx,
  input         io_sqControl_toStoreMisalignBuffer_uop_robIdx_flag,
  input  [7:0]  io_sqControl_toStoreMisalignBuffer_uop_robIdx_value,
  output [3:0]  io_toVecStoreMergeBuffer_0_mbIndex,
  output        io_toVecStoreMergeBuffer_0_flush,
  output [3:0]  io_toVecStoreMergeBuffer_1_mbIndex,
  output        io_toVecStoreMergeBuffer_1_flush,
  output        io_full
);

  wire             cross4KBPageBoundary;
  wire             robMatch;
  reg              req_valid;
  reg  [3:0]       req_uop_trigger;
  reg              req_uop_ftqPtr_flag;
  reg  [5:0]       req_uop_ftqPtr_value;
  reg  [3:0]       req_uop_ftqOffset;
  reg  [34:0]      req_uop_fuType;
  reg  [8:0]       req_uop_fuOpType;
  reg              req_uop_rfWen;
  reg  [7:0]       req_uop_vpu_vstart;
  reg  [2:0]       req_uop_vpu_nf;
  reg  [1:0]       req_uop_vpu_veew;
  reg  [6:0]       req_uop_uopIdx;
  reg  [7:0]       req_uop_pdest;
  reg              req_uop_robIdx_flag;
  reg  [7:0]       req_uop_robIdx_value;
  reg              req_uop_debugInfo_eliminatedMove;
  reg  [63:0]      req_uop_debugInfo_renameTime;
  reg  [63:0]      req_uop_debugInfo_dispatchTime;
  reg  [63:0]      req_uop_debugInfo_enqRsTime;
  reg  [63:0]      req_uop_debugInfo_selectTime;
  reg  [63:0]      req_uop_debugInfo_issueTime;
  reg  [63:0]      req_uop_debugInfo_writebackTime;
  reg  [63:0]      req_uop_debugInfo_runahead_checkpoint_id;
  reg  [63:0]      req_uop_debugInfo_tlbFirstReqTime;
  reg  [63:0]      req_uop_debugInfo_tlbRespTime;
  reg              req_uop_lqIdx_flag;
  reg  [6:0]       req_uop_lqIdx_value;
  reg              req_uop_sqIdx_flag;
  reg  [5:0]       req_uop_sqIdx_value;
  reg  [49:0]      req_vaddr;
  reg              req_vaNeedExt;
  reg  [47:0]      req_paddr;
  reg  [63:0]      req_gpaddr;
  reg              req_isForVSnonLeafPTE;
  reg  [15:0]      req_mask;
  reg              req_isvec;
  reg  [7:0]       req_elemIdx;
  reg  [2:0]       req_alignedType;
  reg  [3:0]       req_mbIndex;
  reg              req_portIndex;
  reg              needFlushPipe;
  reg  [2:0]       bufferState;
  wire             _reqSel_oldestIndex_T = io_req_0_valid & io_req_1_valid;
  wire             reqSel_oldest_differentFlag =
    io_req_0_bits_uop_robIdx_flag ^ io_req_1_bits_uop_robIdx_flag;
  wire             reqSel_oldest_compare =
    io_req_0_bits_uop_robIdx_value > io_req_1_bits_uop_robIdx_value;
  wire             _reqSel_oldestIndex_T_5 =
    io_req_0_bits_uop_uopIdx > io_req_1_bits_uop_uopIdx;
  wire             _reqSel_oldest_T_5 =
    reqSel_oldest_differentFlag ^ reqSel_oldest_compare
    | (reqSel_oldest_differentFlag
       ^ io_req_0_bits_uop_robIdx_value >= io_req_1_bits_uop_robIdx_value)
    & _reqSel_oldestIndex_T_5;
  wire             _reqSel_oldest_T_8 = io_req_0_valid & ~io_req_1_valid;
  wire             reqSel_oldest_valid =
    _reqSel_oldestIndex_T
      ? (_reqSel_oldest_T_5 ? io_req_1_valid : io_req_0_valid)
      : _reqSel_oldest_T_8 ? io_req_0_valid : io_req_1_valid;
  wire [6:0]       reqSel_oldest_bits_uop_uopIdx =
    _reqSel_oldestIndex_T
      ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_uopIdx : io_req_0_bits_uop_uopIdx)
      : _reqSel_oldest_T_8 ? io_req_0_bits_uop_uopIdx : io_req_1_bits_uop_uopIdx;
  wire             reqSel_oldest_bits_uop_robIdx_flag =
    _reqSel_oldestIndex_T
      ? (_reqSel_oldest_T_5
           ? io_req_1_bits_uop_robIdx_flag
           : io_req_0_bits_uop_robIdx_flag)
      : _reqSel_oldest_T_8
          ? io_req_0_bits_uop_robIdx_flag
          : io_req_1_bits_uop_robIdx_flag;
  wire [7:0]       reqSel_oldest_bits_uop_robIdx_value =
    _reqSel_oldestIndex_T
      ? (_reqSel_oldest_T_5
           ? io_req_1_bits_uop_robIdx_value
           : io_req_0_bits_uop_robIdx_value)
      : _reqSel_oldest_T_8
          ? io_req_0_bits_uop_robIdx_value
          : io_req_1_bits_uop_robIdx_value;
  wire             reqSel_3_0 =
    _reqSel_oldestIndex_T
      ? reqSel_oldest_differentFlag ^ reqSel_oldest_compare
        | {io_req_0_bits_uop_robIdx_flag,
           io_req_0_bits_uop_robIdx_value} == {io_req_1_bits_uop_robIdx_flag,
                                               io_req_1_bits_uop_robIdx_value}
        & _reqSel_oldestIndex_T_5
      : ~(io_req_0_valid & ~io_req_1_valid);
  wire [8:0]       _flush_flushItself_T_2 =
    {io_redirect_bits_robIdx_flag, io_redirect_bits_robIdx_value};
  wire             reqRedirect =
    io_redirect_valid
    & (io_redirect_bits_level
       & {reqSel_oldest_bits_uop_robIdx_flag,
          reqSel_oldest_bits_uop_robIdx_value} == _flush_flushItself_T_2
       | reqSel_oldest_bits_uop_robIdx_flag ^ io_redirect_bits_robIdx_flag
       ^ reqSel_oldest_bits_uop_robIdx_value > io_redirect_bits_robIdx_value);
  wire             canEnq = ~req_valid & ~reqRedirect & reqSel_oldest_valid;
  wire [8:0]       _flush_flushItself_T_1 = {req_uop_robIdx_flag, req_uop_robIdx_value};
  wire             _GEN = cross4KBPageBoundary & ~reqRedirect;
  wire             differentFlag =
    req_uop_robIdx_flag ^ reqSel_oldest_bits_uop_robIdx_flag;
  wire             _GEN_0 =
    reqSel_oldest_valid
    & (differentFlag ^ req_uop_robIdx_value > reqSel_oldest_bits_uop_robIdx_value
       | (differentFlag ^ req_uop_robIdx_value >= reqSel_oldest_bits_uop_robIdx_value)
       & req_uop_uopIdx > reqSel_oldest_bits_uop_uopIdx) & ~(|bufferState);
  wire             cross4KBPageEnq = _GEN & _GEN_0;
  wire             _io_req_1_ready_T_2 = cross4KBPageBoundary & cross4KBPageEnq;
  wire             _io_toVecStoreMergeBuffer_1_flush_T = req_valid & cross4KBPageBoundary;
  reg              splitStoreReqs_0_uop_ftqPtr_flag;
  reg  [5:0]       splitStoreReqs_0_uop_ftqPtr_value;
  reg  [3:0]       splitStoreReqs_0_uop_ftqOffset;
  reg  [34:0]      splitStoreReqs_0_uop_fuType;
  reg  [8:0]       splitStoreReqs_0_uop_fuOpType;
  reg              splitStoreReqs_0_uop_rfWen;
  reg  [7:0]       splitStoreReqs_0_uop_vpu_vstart;
  reg  [2:0]       splitStoreReqs_0_uop_vpu_nf;
  reg  [1:0]       splitStoreReqs_0_uop_vpu_veew;
  reg  [6:0]       splitStoreReqs_0_uop_uopIdx;
  reg  [7:0]       splitStoreReqs_0_uop_pdest;
  reg              splitStoreReqs_0_uop_robIdx_flag;
  reg  [7:0]       splitStoreReqs_0_uop_robIdx_value;
  reg              splitStoreReqs_0_uop_debugInfo_eliminatedMove;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_renameTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_dispatchTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_enqRsTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_selectTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_issueTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_writebackTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime;
  reg  [63:0]      splitStoreReqs_0_uop_debugInfo_tlbRespTime;
  reg              splitStoreReqs_0_uop_lqIdx_flag;
  reg  [6:0]       splitStoreReqs_0_uop_lqIdx_value;
  reg              splitStoreReqs_0_uop_sqIdx_flag;
  reg  [5:0]       splitStoreReqs_0_uop_sqIdx_value;
  reg  [49:0]      splitStoreReqs_0_vaddr;
  reg  [15:0]      splitStoreReqs_0_mask;
  reg              splitStoreReqs_0_is128bit;
  reg              splitStoreReqs_1_uop_ftqPtr_flag;
  reg  [5:0]       splitStoreReqs_1_uop_ftqPtr_value;
  reg  [3:0]       splitStoreReqs_1_uop_ftqOffset;
  reg  [34:0]      splitStoreReqs_1_uop_fuType;
  reg  [8:0]       splitStoreReqs_1_uop_fuOpType;
  reg              splitStoreReqs_1_uop_rfWen;
  reg  [7:0]       splitStoreReqs_1_uop_vpu_vstart;
  reg  [2:0]       splitStoreReqs_1_uop_vpu_nf;
  reg  [1:0]       splitStoreReqs_1_uop_vpu_veew;
  reg  [6:0]       splitStoreReqs_1_uop_uopIdx;
  reg  [7:0]       splitStoreReqs_1_uop_pdest;
  reg              splitStoreReqs_1_uop_robIdx_flag;
  reg  [7:0]       splitStoreReqs_1_uop_robIdx_value;
  reg              splitStoreReqs_1_uop_debugInfo_eliminatedMove;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_renameTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_dispatchTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_enqRsTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_selectTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_issueTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_writebackTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime;
  reg  [63:0]      splitStoreReqs_1_uop_debugInfo_tlbRespTime;
  reg              splitStoreReqs_1_uop_lqIdx_flag;
  reg  [6:0]       splitStoreReqs_1_uop_lqIdx_value;
  reg              splitStoreReqs_1_uop_sqIdx_flag;
  reg  [5:0]       splitStoreReqs_1_uop_sqIdx_value;
  reg  [49:0]      splitStoreReqs_1_vaddr;
  reg  [15:0]      splitStoreReqs_1_mask;
  reg              splitStoreReqs_1_is128bit;
  reg  [47:0]      splitStoreResp_1_paddr;
  reg              isCrossPage;
  reg              exceptionVec_3;
  reg              exceptionVec_6;
  reg              exceptionVec_7;
  reg              exceptionVec_15;
  reg              exceptionVec_23;
  reg  [1:0]       unSentStores;
  reg              curPtr;
  reg              globalException;
  reg              globalMMIO;
  wire             _GEN_1 =
    io_rob_pendingst
    & {io_rob_pendingPtr_flag, io_rob_pendingPtr_value} == _flush_flushItself_T_1;
  assign robMatch = _GEN_1 & req_valid;
  wire             _GEN_2 = bufferState == 3'h1;
  wire [1:0]       alignedType = req_isvec ? req_alignedType[1:0] : req_uop_fuOpType[1:0];
  wire             _highPageAddress_T_2 = alignedType == 2'h2;
  wire [1:0]       _GEN_3 = {1'h0, alignedType == 2'h1};
  wire [4:0]       _highAddress_T_12 =
    5'({2'h0, {1'h0, _GEN_3 | {2{_highPageAddress_T_2}}} | {3{&alignedType}}}
       + req_vaddr[4:0]);
  wire [12:0]      _highPageAddress_T_12 =
    13'({10'h0, {1'h0, _GEN_3 | {2{_highPageAddress_T_2}}} | {3{&alignedType}}}
        + req_vaddr[12:0]);
  wire             cross16BytesBoundary =
    req_valid & _highAddress_T_12[4] != req_vaddr[4];
  assign cross4KBPageBoundary = req_valid & _highPageAddress_T_12[12] != req_vaddr[12];
  wire [3:0][49:0] _GEN_4 = {{req_vaddr}, {req_vaddr}, {50'(req_vaddr - 50'h1)}, {50'h0}};
  wire [3:0][49:0] _GEN_5 =
    {{50'(req_vaddr + 50'h1)},
     {50'(req_vaddr + 50'h2)},
     {50'(req_vaddr + 50'h3)},
     {50'h0}};
  `ifndef SYNTHESIS
    wire _GEN_6 = _GEN_2 & cross16BytesBoundary;
    wire _GEN_7 = _GEN_6 & (|alignedType) & alignedType != 2'h1;
    wire _GEN_8 = alignedType == 2'h2;
    always @(posedge clock) begin
      if (_GEN_2 & ~cross16BytesBoundary & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: There should be no non-aligned access that does not cross 16Byte boundaries.\n    at StoreMisalignBuffer.scala:340 assert(false.B, s\"There should be no non-aligned access that does not cross 16Byte boundaries.\")\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_6 & ~(|alignedType) & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: lb should not trigger miss align\n    at StoreMisalignBuffer.scala:353 assert(false.B, \"lb should not trigger miss align\")\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_7 & _GEN_8 & req_vaddr[1:0] == 2'h0 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: should not trigger miss align\n    at StoreMisalignBuffer.scala:371 assert(false.B, \"should not trigger miss align\")\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_7 & ~_GEN_8 & (&alignedType) & req_vaddr[2:0] == 3'h0 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: should not trigger miss align\n    at StoreMisalignBuffer.scala:415 assert(false.B, \"should not trigger miss align\")\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [7:0][49:0] _GEN_9 =
    {{50'(req_vaddr - 50'h7)},
     {50'(req_vaddr - 50'h6)},
     {50'(req_vaddr - 50'h5)},
     {req_vaddr},
     {50'(req_vaddr - 50'h3)},
     {50'(req_vaddr - 50'h2)},
     {50'(req_vaddr - 50'h1)},
     {50'h0}};
  wire [3:0][49:0] _GEN_10 =
    {{_GEN_9[req_vaddr[2:0]]}, {_GEN_4[req_vaddr[1:0]]}, {req_vaddr}, {50'h0}};
  wire             _GEN_11 = ~_GEN_2 | ~cross16BytesBoundary | ~(|alignedType);
  wire [49:0]      lowAddrStore_vaddr = _GEN_11 ? 50'h0 : _GEN_10[alignedType];
  wire [7:0][49:0] _GEN_12 =
    {{50'(req_vaddr + 50'h1)},
     {50'(req_vaddr + 50'h2)},
     {50'(req_vaddr + 50'h3)},
     {50'(req_vaddr + 50'h4)},
     {50'(req_vaddr + 50'h5)},
     {50'(req_vaddr + 50'h6)},
     {50'(req_vaddr + 50'h7)},
     {50'h0}};
  wire [3:0][49:0] _GEN_13 =
    {{_GEN_12[req_vaddr[2:0]]},
     {_GEN_5[req_vaddr[1:0]]},
     {50'(req_vaddr + 50'h1)},
     {50'h0}};
  wire [49:0]      highAddrStore_vaddr = _GEN_11 ? 50'h0 : _GEN_13[alignedType];
  wire             io_splitStoreReq_valid_0 = req_valid & bufferState == 3'h2;
  wire             _io_vecWriteBack_1_valid_T = bufferState == 3'h4;
  wire             io_writeBack_valid_0 =
    req_valid & _io_vecWriteBack_1_valid_T & ~io_storeOutValid & ~req_isvec;
  wire             _io_writeBack_bits_uop_exceptionVec_3_T = globalMMIO | globalException;
  wire             io_vecWriteBack_0_valid_0 =
    req_valid & _io_vecWriteBack_1_valid_T & req_isvec & ~io_storeVecOutValid
    & ~req_portIndex;
  wire [63:0]      io_vecWriteBack_1_bits_vaddr_0 = {14'h0, req_vaddr};
  wire             io_vecWriteBack_1_valid_0 =
    req_valid & _io_vecWriteBack_1_valid_T & req_isvec & ~io_storeVecOutValid
    & req_portIndex;
  wire             flush_probe =
    req_valid & io_redirect_valid
    & (io_redirect_bits_level & _flush_flushItself_T_1 == _flush_flushItself_T_2
       | req_uop_robIdx_flag ^ io_redirect_bits_robIdx_flag
       ^ req_uop_robIdx_value > io_redirect_bits_robIdx_value);
  reg              REG;
  wire             _GEN_14 = REG & req_valid;
  wire             _GEN_15 = flush_probe & ~(|bufferState);
  wire             _GEN_16 = flush_probe & (|bufferState);
  wire             _GEN_17 = canEnq | req_valid;
  wire [1:0]       _GEN_18 = {1'h0, curPtr};
  wire [3:0][8:0]  _GEN_19 = {{9'h0}, {9'h1}, {9'h2}, {req_uop_fuOpType}};
  wire [22:0]      _lowAddrStore_mask_T_21 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [22:0]      _lowAddrStore_mask_T_19 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [22:0]      _lowAddrStore_mask_T_17 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [18:0]      _lowAddrStore_mask_T_15 = 19'hF << lowAddrStore_vaddr[3:0];
  wire [22:0]      _lowAddrStore_mask_T_13 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [22:0]      _lowAddrStore_mask_T_11 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [22:0]      _lowAddrStore_mask_T_9 = 23'hFF << lowAddrStore_vaddr[3:0];
  wire [7:0][15:0] _GEN_20 =
    {{_lowAddrStore_mask_T_21[15:0]},
     {_lowAddrStore_mask_T_19[15:0]},
     {_lowAddrStore_mask_T_17[15:0]},
     {_lowAddrStore_mask_T_15[15:0]},
     {_lowAddrStore_mask_T_13[15:0]},
     {_lowAddrStore_mask_T_11[15:0]},
     {_lowAddrStore_mask_T_9[15:0]},
     {16'h0}};
  wire [16:0]      _lowAddrStore_mask_T_5 = 17'h3 << lowAddrStore_vaddr[3:0];
  wire [18:0]      _lowAddrStore_mask_T_3 = 19'hF << lowAddrStore_vaddr[3:0];
  wire [3:0][15:0] _GEN_21 =
    {{16'h1 << lowAddrStore_vaddr[3:0]},
     {_lowAddrStore_mask_T_5[15:0]},
     {_lowAddrStore_mask_T_3[15:0]},
     {16'h0}};
  wire [3:0][15:0] _GEN_22 =
    {{_GEN_20[req_vaddr[2:0]]},
     {_GEN_21[req_vaddr[1:0]]},
     {16'h1 << lowAddrStore_vaddr[3:0]},
     {16'h0}};
  wire [3:0][8:0]  _GEN_23 = {{9'h2}, {9'h1}, {9'h0}, {req_uop_fuOpType}};
  wire [22:0]      _highAddrStore_mask_T_21 = 23'hFF << highAddrStore_vaddr[3:0];
  wire [22:0]      _highAddrStore_mask_T_19 = 23'hFF << highAddrStore_vaddr[3:0];
  wire [22:0]      _highAddrStore_mask_T_17 = 23'hFF << highAddrStore_vaddr[3:0];
  wire [18:0]      _highAddrStore_mask_T_15 = 19'hF << highAddrStore_vaddr[3:0];
  wire [18:0]      _highAddrStore_mask_T_13 = 19'hF << highAddrStore_vaddr[3:0];
  wire [16:0]      _highAddrStore_mask_T_11 = 17'h3 << highAddrStore_vaddr[3:0];
  wire [7:0][15:0] _GEN_24 =
    {{_highAddrStore_mask_T_21[15:0]},
     {_highAddrStore_mask_T_19[15:0]},
     {_highAddrStore_mask_T_17[15:0]},
     {_highAddrStore_mask_T_15[15:0]},
     {_highAddrStore_mask_T_13[15:0]},
     {_highAddrStore_mask_T_11[15:0]},
     {16'h1 << highAddrStore_vaddr[3:0]},
     {16'h0}};
  wire [18:0]      _highAddrStore_mask_T_7 = 19'hF << highAddrStore_vaddr[3:0];
  wire [16:0]      _highAddrStore_mask_T_5 = 17'h3 << highAddrStore_vaddr[3:0];
  wire [3:0][15:0] _GEN_25 =
    {{_highAddrStore_mask_T_7[15:0]},
     {_highAddrStore_mask_T_5[15:0]},
     {16'h1 << highAddrStore_vaddr[3:0]},
     {16'h0}};
  wire [3:0][15:0] _GEN_26 =
    {{_GEN_24[req_vaddr[2:0]]},
     {_GEN_25[req_vaddr[1:0]]},
     {16'h1 << highAddrStore_vaddr[3:0]},
     {16'h0}};
  wire             hasException =
    (|{io_splitStoreResp_bits_uop_exceptionVec_23,
       io_splitStoreResp_bits_uop_exceptionVec_15,
       io_splitStoreResp_bits_uop_exceptionVec_7,
       io_splitStoreResp_bits_uop_exceptionVec_6,
       io_splitStoreResp_bits_uop_exceptionVec_3}) & ~io_splitStoreResp_bits_need_rep;
  wire             isMMIO =
    io_splitStoreResp_bits_mmio & ~io_splitStoreResp_bits_need_rep;
  wire             _GEN_27 = bufferState == 3'h2;
  wire             _GEN_28 = bufferState == 3'h3;
  wire             _GEN_29 = hasException | isMMIO;
  wire             _GEN_30 = io_splitStoreResp_valid & _GEN_29;
  wire             _GEN_31 = bufferState == 3'h4;
  wire             _GEN_32 = io_writeBack_ready & io_writeBack_valid_0;
  wire             _GEN_33 = _GEN_32 & (~isCrossPage | globalMMIO | globalException);
  wire             _GEN_34 =
    _GEN_33 | req_isvec & (io_vecWriteBack_0_valid_0 | io_vecWriteBack_1_valid_0);
  wire             _GEN_35 = _GEN_2 | _GEN_27 | _GEN_28;
  wire             _GEN_36 = ~(|bufferState) | _GEN_35;
  wire             _GEN_37 =
    bufferState == 3'h5 & io_sqControl_toStoreMisalignBuffer_doDeq;
  wire             _GEN_38 = ~(|bufferState) | _GEN_2 | _GEN_27;
  wire             _GEN_39 = _GEN_2 & cross16BytesBoundary;
  wire             _GEN_40 = ~_GEN_2 | ~cross16BytesBoundary;
  wire             lowAddrStore_uop_ftqPtr_flag =
    _GEN_2 & cross16BytesBoundary & req_uop_ftqPtr_flag;
  wire [5:0]       lowAddrStore_uop_ftqPtr_value = _GEN_39 ? req_uop_ftqPtr_value : 6'h0;
  wire [3:0]       lowAddrStore_uop_ftqOffset = _GEN_39 ? req_uop_ftqOffset : 4'h0;
  wire [34:0]      lowAddrStore_uop_fuType = _GEN_39 ? req_uop_fuType : 35'h0;
  wire             lowAddrStore_uop_rfWen = _GEN_2 & cross16BytesBoundary & req_uop_rfWen;
  wire [7:0]       lowAddrStore_uop_vpu_vstart = _GEN_39 ? req_uop_vpu_vstart : 8'h0;
  wire [2:0]       lowAddrStore_uop_vpu_nf = _GEN_39 ? req_uop_vpu_nf : 3'h0;
  wire [1:0]       lowAddrStore_uop_vpu_veew = _GEN_39 ? req_uop_vpu_veew : 2'h0;
  wire [6:0]       lowAddrStore_uop_uopIdx = _GEN_39 ? req_uop_uopIdx : 7'h0;
  wire [7:0]       lowAddrStore_uop_pdest = _GEN_39 ? req_uop_pdest : 8'h0;
  wire             lowAddrStore_uop_robIdx_flag =
    _GEN_2 & cross16BytesBoundary & req_uop_robIdx_flag;
  wire [7:0]       lowAddrStore_uop_robIdx_value = _GEN_39 ? req_uop_robIdx_value : 8'h0;
  wire             lowAddrStore_uop_debugInfo_eliminatedMove =
    _GEN_2 & cross16BytesBoundary & req_uop_debugInfo_eliminatedMove;
  wire [63:0]      lowAddrStore_uop_debugInfo_renameTime =
    _GEN_39 ? req_uop_debugInfo_renameTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_dispatchTime =
    _GEN_39 ? req_uop_debugInfo_dispatchTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_enqRsTime =
    _GEN_39 ? req_uop_debugInfo_enqRsTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_selectTime =
    _GEN_39 ? req_uop_debugInfo_selectTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_issueTime =
    _GEN_39 ? req_uop_debugInfo_issueTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_writebackTime =
    _GEN_39 ? req_uop_debugInfo_writebackTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_runahead_checkpoint_id =
    _GEN_39 ? req_uop_debugInfo_runahead_checkpoint_id : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_tlbFirstReqTime =
    _GEN_39 ? req_uop_debugInfo_tlbFirstReqTime : 64'h0;
  wire [63:0]      lowAddrStore_uop_debugInfo_tlbRespTime =
    _GEN_39 ? req_uop_debugInfo_tlbRespTime : 64'h0;
  wire             lowAddrStore_uop_lqIdx_flag =
    _GEN_2 & cross16BytesBoundary & req_uop_lqIdx_flag;
  wire [6:0]       lowAddrStore_uop_lqIdx_value = _GEN_39 ? req_uop_lqIdx_value : 7'h0;
  wire             lowAddrStore_uop_sqIdx_flag =
    _GEN_2 & cross16BytesBoundary & req_uop_sqIdx_flag;
  wire [5:0]       lowAddrStore_uop_sqIdx_value = _GEN_39 ? req_uop_sqIdx_value : 6'h0;
  wire [8:0]       _GEN_41 =
    req_vaddr[2:0] == 3'h5 | req_vaddr[2:0] == 3'h6 | (&(req_vaddr[2:0]))
      ? 9'h3
      : req_uop_fuOpType;
  wire             _GEN_42 = isMMIO | hasException;
  wire             _GEN_43 = _GEN_36 | ~(_GEN_31 ? _GEN_34 : _GEN_37);
  wire [7:0][8:0]  _GEN_44 =
    {{_GEN_41}, {_GEN_41}, {_GEN_41}, {9'h2}, {9'h3}, {9'h3}, {9'h3}, {req_uop_fuOpType}};
  wire [3:0][8:0]  _GEN_45 =
    {{_GEN_44[req_vaddr[2:0]]}, {_GEN_19[req_vaddr[1:0]]}, {9'h0}, {req_uop_fuOpType}};
  wire [7:0][8:0]  _GEN_46 =
    {{_GEN_41}, {_GEN_41}, {_GEN_41}, {9'h2}, {9'h2}, {9'h1}, {9'h0}, {req_uop_fuOpType}};
  wire [3:0][8:0]  _GEN_47 =
    {{_GEN_46[req_vaddr[2:0]]}, {_GEN_23[req_vaddr[1:0]]}, {9'h0}, {req_uop_fuOpType}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      req_valid <= 1'h0;
      needFlushPipe <= 1'h0;
      bufferState <= 3'h0;
      splitStoreReqs_0_uop_ftqPtr_flag <= 1'h0;
      splitStoreReqs_0_uop_ftqPtr_value <= 6'h0;
      splitStoreReqs_0_uop_ftqOffset <= 4'h0;
      splitStoreReqs_0_uop_fuType <= 35'h0;
      splitStoreReqs_0_uop_fuOpType <= 9'h0;
      splitStoreReqs_0_uop_rfWen <= 1'h0;
      splitStoreReqs_0_uop_vpu_vstart <= 8'h0;
      splitStoreReqs_0_uop_vpu_nf <= 3'h0;
      splitStoreReqs_0_uop_vpu_veew <= 2'h0;
      splitStoreReqs_0_uop_uopIdx <= 7'h0;
      splitStoreReqs_0_uop_pdest <= 8'h0;
      splitStoreReqs_0_uop_robIdx_flag <= 1'h0;
      splitStoreReqs_0_uop_robIdx_value <= 8'h0;
      splitStoreReqs_0_uop_debugInfo_eliminatedMove <= 1'h0;
      splitStoreReqs_0_uop_debugInfo_renameTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_dispatchTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_enqRsTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_selectTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_issueTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_writebackTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime <= 64'h0;
      splitStoreReqs_0_uop_debugInfo_tlbRespTime <= 64'h0;
      splitStoreReqs_0_uop_lqIdx_flag <= 1'h0;
      splitStoreReqs_0_uop_lqIdx_value <= 7'h0;
      splitStoreReqs_0_uop_sqIdx_flag <= 1'h0;
      splitStoreReqs_0_uop_sqIdx_value <= 6'h0;
      splitStoreReqs_0_vaddr <= 50'h0;
      splitStoreReqs_0_mask <= 16'h0;
      splitStoreReqs_0_is128bit <= 1'h0;
      splitStoreReqs_1_uop_ftqPtr_flag <= 1'h0;
      splitStoreReqs_1_uop_ftqPtr_value <= 6'h0;
      splitStoreReqs_1_uop_ftqOffset <= 4'h0;
      splitStoreReqs_1_uop_fuType <= 35'h0;
      splitStoreReqs_1_uop_fuOpType <= 9'h0;
      splitStoreReqs_1_uop_rfWen <= 1'h0;
      splitStoreReqs_1_uop_vpu_vstart <= 8'h0;
      splitStoreReqs_1_uop_vpu_nf <= 3'h0;
      splitStoreReqs_1_uop_vpu_veew <= 2'h0;
      splitStoreReqs_1_uop_uopIdx <= 7'h0;
      splitStoreReqs_1_uop_pdest <= 8'h0;
      splitStoreReqs_1_uop_robIdx_flag <= 1'h0;
      splitStoreReqs_1_uop_robIdx_value <= 8'h0;
      splitStoreReqs_1_uop_debugInfo_eliminatedMove <= 1'h0;
      splitStoreReqs_1_uop_debugInfo_renameTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_dispatchTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_enqRsTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_selectTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_issueTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_writebackTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime <= 64'h0;
      splitStoreReqs_1_uop_debugInfo_tlbRespTime <= 64'h0;
      splitStoreReqs_1_uop_lqIdx_flag <= 1'h0;
      splitStoreReqs_1_uop_lqIdx_value <= 7'h0;
      splitStoreReqs_1_uop_sqIdx_flag <= 1'h0;
      splitStoreReqs_1_uop_sqIdx_value <= 6'h0;
      splitStoreReqs_1_vaddr <= 50'h0;
      splitStoreReqs_1_mask <= 16'h0;
      splitStoreReqs_1_is128bit <= 1'h0;
      splitStoreResp_1_paddr <= 48'h0;
      isCrossPage <= 1'h0;
      exceptionVec_3 <= 1'h0;
      exceptionVec_6 <= 1'h0;
      exceptionVec_7 <= 1'h0;
      exceptionVec_15 <= 1'h0;
      exceptionVec_23 <= 1'h0;
      unSentStores <= 2'h0;
      curPtr <= 1'h0;
      globalException <= 1'h0;
      globalMMIO <= 1'h0;
    end
    else begin
      if (flush_probe) begin
        req_valid <= cross4KBPageEnq & cross4KBPageBoundary & ~reqRedirect & req_valid;
        bufferState <= 3'h0;
        unSentStores <= 2'h0;
      end
      else begin
        if (_GEN_36)
          req_valid <= _GEN_17;
        else if (_GEN_31)
          req_valid <= ~_GEN_34 & _GEN_17;
        else
          req_valid <= ~_GEN_37 & _GEN_17;
        if (|bufferState) begin
          if (_GEN_2)
            bufferState <= 3'h2;
          else if (_GEN_27) begin
            if (io_splitStoreReq_ready & io_splitStoreReq_valid_0)
              bufferState <= 3'h3;
          end
          else if (_GEN_28) begin
            if (io_splitStoreResp_valid)
              bufferState <=
                _GEN_29
                | ~(io_splitStoreResp_bits_need_rep
                    | (|(unSentStores & ~(2'h1 << _GEN_18))))
                  ? 3'h4
                  : 3'h2;
          end
          else if (_GEN_31) begin
            if (_GEN_33)
              bufferState <= 3'h0;
            else
              bufferState <= {2'h2, _GEN_32 & isCrossPage};
          end
          else if (_GEN_37)
            bufferState <= 3'h0;
        end
        else if ((~cross4KBPageBoundary | _GEN_1) & req_valid)
          bufferState <= 3'h1;
        if (io_splitStoreResp_valid) begin
          if (_GEN_42)
            unSentStores <= 2'h0;
          else if (io_splitStoreResp_bits_need_rep) begin
            if (_GEN_39)
              unSentStores <= 2'h3;
            else if (_GEN_43) begin
            end
            else
              unSentStores <= 2'h0;
          end
          else
            unSentStores <= unSentStores & ~(2'h1 << _GEN_18);
        end
        else if (_GEN_39)
          unSentStores <= 2'h3;
        else if (_GEN_43) begin
        end
        else
          unSentStores <= 2'h0;
      end
      needFlushPipe <=
        ~flush_probe & (_GEN_36 | ~(_GEN_31 & _GEN_34)) & (_GEN & _GEN_0 | needFlushPipe);
      if (_GEN_39) begin
        splitStoreReqs_0_uop_ftqPtr_flag <= lowAddrStore_uop_ftqPtr_flag;
        splitStoreReqs_0_uop_ftqPtr_value <= lowAddrStore_uop_ftqPtr_value;
        splitStoreReqs_0_uop_ftqOffset <= lowAddrStore_uop_ftqOffset;
        splitStoreReqs_0_uop_fuType <= lowAddrStore_uop_fuType;
        splitStoreReqs_0_uop_fuOpType <=
          _GEN_39 ? ((|alignedType) ? _GEN_45[alignedType] : req_uop_fuOpType) : 9'h0;
        splitStoreReqs_0_uop_rfWen <= lowAddrStore_uop_rfWen;
        splitStoreReqs_0_uop_vpu_vstart <= lowAddrStore_uop_vpu_vstart;
        splitStoreReqs_0_uop_vpu_nf <= lowAddrStore_uop_vpu_nf;
        splitStoreReqs_0_uop_vpu_veew <= lowAddrStore_uop_vpu_veew;
        splitStoreReqs_0_uop_uopIdx <= lowAddrStore_uop_uopIdx;
        splitStoreReqs_0_uop_pdest <= lowAddrStore_uop_pdest;
        splitStoreReqs_0_uop_robIdx_flag <= lowAddrStore_uop_robIdx_flag;
        splitStoreReqs_0_uop_robIdx_value <= lowAddrStore_uop_robIdx_value;
        splitStoreReqs_0_uop_debugInfo_eliminatedMove <=
          lowAddrStore_uop_debugInfo_eliminatedMove;
        splitStoreReqs_0_uop_debugInfo_renameTime <=
          lowAddrStore_uop_debugInfo_renameTime;
        splitStoreReqs_0_uop_debugInfo_dispatchTime <=
          lowAddrStore_uop_debugInfo_dispatchTime;
        splitStoreReqs_0_uop_debugInfo_enqRsTime <= lowAddrStore_uop_debugInfo_enqRsTime;
        splitStoreReqs_0_uop_debugInfo_selectTime <=
          lowAddrStore_uop_debugInfo_selectTime;
        splitStoreReqs_0_uop_debugInfo_issueTime <= lowAddrStore_uop_debugInfo_issueTime;
        splitStoreReqs_0_uop_debugInfo_writebackTime <=
          lowAddrStore_uop_debugInfo_writebackTime;
        splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id <=
          lowAddrStore_uop_debugInfo_runahead_checkpoint_id;
        splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime <=
          lowAddrStore_uop_debugInfo_tlbFirstReqTime;
        splitStoreReqs_0_uop_debugInfo_tlbRespTime <=
          lowAddrStore_uop_debugInfo_tlbRespTime;
        splitStoreReqs_0_uop_lqIdx_flag <= lowAddrStore_uop_lqIdx_flag;
        splitStoreReqs_0_uop_lqIdx_value <= lowAddrStore_uop_lqIdx_value;
        splitStoreReqs_0_uop_sqIdx_flag <= lowAddrStore_uop_sqIdx_flag;
        splitStoreReqs_0_uop_sqIdx_value <= lowAddrStore_uop_sqIdx_value;
        splitStoreReqs_0_vaddr <= lowAddrStore_vaddr;
        splitStoreReqs_0_mask <= _GEN_11 ? 16'h0 : _GEN_22[alignedType];
      end
      splitStoreReqs_0_is128bit <= _GEN_40 & splitStoreReqs_0_is128bit;
      if (_GEN_39) begin
        splitStoreReqs_1_uop_ftqPtr_flag <= lowAddrStore_uop_ftqPtr_flag;
        splitStoreReqs_1_uop_ftqPtr_value <= lowAddrStore_uop_ftqPtr_value;
        splitStoreReqs_1_uop_ftqOffset <= lowAddrStore_uop_ftqOffset;
        splitStoreReqs_1_uop_fuType <= lowAddrStore_uop_fuType;
        splitStoreReqs_1_uop_fuOpType <=
          _GEN_39 ? ((|alignedType) ? _GEN_47[alignedType] : req_uop_fuOpType) : 9'h0;
        splitStoreReqs_1_uop_rfWen <= lowAddrStore_uop_rfWen;
        splitStoreReqs_1_uop_vpu_vstart <= lowAddrStore_uop_vpu_vstart;
        splitStoreReqs_1_uop_vpu_nf <= lowAddrStore_uop_vpu_nf;
        splitStoreReqs_1_uop_vpu_veew <= lowAddrStore_uop_vpu_veew;
        splitStoreReqs_1_uop_uopIdx <= lowAddrStore_uop_uopIdx;
        splitStoreReqs_1_uop_pdest <= lowAddrStore_uop_pdest;
        splitStoreReqs_1_uop_robIdx_flag <= lowAddrStore_uop_robIdx_flag;
        splitStoreReqs_1_uop_robIdx_value <= lowAddrStore_uop_robIdx_value;
        splitStoreReqs_1_uop_debugInfo_eliminatedMove <=
          lowAddrStore_uop_debugInfo_eliminatedMove;
        splitStoreReqs_1_uop_debugInfo_renameTime <=
          lowAddrStore_uop_debugInfo_renameTime;
        splitStoreReqs_1_uop_debugInfo_dispatchTime <=
          lowAddrStore_uop_debugInfo_dispatchTime;
        splitStoreReqs_1_uop_debugInfo_enqRsTime <= lowAddrStore_uop_debugInfo_enqRsTime;
        splitStoreReqs_1_uop_debugInfo_selectTime <=
          lowAddrStore_uop_debugInfo_selectTime;
        splitStoreReqs_1_uop_debugInfo_issueTime <= lowAddrStore_uop_debugInfo_issueTime;
        splitStoreReqs_1_uop_debugInfo_writebackTime <=
          lowAddrStore_uop_debugInfo_writebackTime;
        splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id <=
          lowAddrStore_uop_debugInfo_runahead_checkpoint_id;
        splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime <=
          lowAddrStore_uop_debugInfo_tlbFirstReqTime;
        splitStoreReqs_1_uop_debugInfo_tlbRespTime <=
          lowAddrStore_uop_debugInfo_tlbRespTime;
        splitStoreReqs_1_uop_lqIdx_flag <= lowAddrStore_uop_lqIdx_flag;
        splitStoreReqs_1_uop_lqIdx_value <= lowAddrStore_uop_lqIdx_value;
        splitStoreReqs_1_uop_sqIdx_flag <= lowAddrStore_uop_sqIdx_flag;
        splitStoreReqs_1_uop_sqIdx_value <= lowAddrStore_uop_sqIdx_value;
        splitStoreReqs_1_vaddr <= highAddrStore_vaddr;
        splitStoreReqs_1_mask <= _GEN_11 ? 16'h0 : _GEN_26[alignedType];
      end
      splitStoreReqs_1_is128bit <= _GEN_40 & splitStoreReqs_1_is128bit;
      if (io_splitStoreResp_valid & curPtr)
        splitStoreResp_1_paddr <= io_splitStoreResp_bits_paddr;
      isCrossPage <=
        ~flush_probe
        & ((|bufferState)
             ? (_GEN_35
                  ? isCrossPage
                  : _GEN_31 ? ~_GEN_34 & isCrossPage : ~_GEN_37 & isCrossPage)
             : cross4KBPageBoundary ? robMatch | isCrossPage : ~req_valid & isCrossPage);
      if (io_splitStoreResp_valid) begin
        exceptionVec_3 <=
          ~isMMIO
          & (hasException
               ? exceptionVec_3 | io_splitStoreResp_bits_uop_exceptionVec_3
               : io_splitStoreResp_bits_need_rep & exceptionVec_3);
        exceptionVec_6 <=
          isMMIO
          | (hasException
               ? exceptionVec_6 | io_splitStoreResp_bits_uop_exceptionVec_6
               : io_splitStoreResp_bits_need_rep & exceptionVec_6);
        exceptionVec_7 <=
          ~isMMIO
          & (hasException
               ? exceptionVec_7 | io_splitStoreResp_bits_uop_exceptionVec_7
               : io_splitStoreResp_bits_need_rep & exceptionVec_7);
        exceptionVec_15 <=
          ~isMMIO
          & (hasException
               ? exceptionVec_15 | io_splitStoreResp_bits_uop_exceptionVec_15
               : io_splitStoreResp_bits_need_rep & exceptionVec_15);
        exceptionVec_23 <=
          ~isMMIO
          & (hasException
               ? exceptionVec_23 | io_splitStoreResp_bits_uop_exceptionVec_23
               : io_splitStoreResp_bits_need_rep & exceptionVec_23);
      end
      curPtr <=
        ~flush_probe
        & (~io_splitStoreResp_valid | _GEN_42 | io_splitStoreResp_bits_need_rep
             ? _GEN_40
               & (_GEN_36 ? curPtr : _GEN_31 ? ~_GEN_34 & curPtr : ~_GEN_37 & curPtr)
             : 1'(curPtr - 1'h1));
      globalException <=
        ~flush_probe
        & (_GEN_38
             ? globalException
             : _GEN_28
                 ? (_GEN_30 ? hasException : globalException)
                 : _GEN_31 ? ~_GEN_34 & globalException : ~_GEN_37 & globalException);
      globalMMIO <=
        ~flush_probe
        & (_GEN_38
             ? globalMMIO
             : _GEN_28
                 ? (_GEN_30 ? isMMIO : globalMMIO)
                 : _GEN_31 ? ~_GEN_34 & globalMMIO : ~_GEN_37 & globalMMIO);
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (_GEN ? _GEN_0 : canEnq) begin
      req_uop_trigger <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_trigger : io_req_0_bits_uop_trigger)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_trigger : io_req_1_bits_uop_trigger;
      req_uop_ftqPtr_flag <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_ftqPtr_flag
               : io_req_0_bits_uop_ftqPtr_flag)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_ftqPtr_flag
              : io_req_1_bits_uop_ftqPtr_flag;
      req_uop_ftqPtr_value <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_ftqPtr_value
               : io_req_0_bits_uop_ftqPtr_value)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_ftqPtr_value
              : io_req_1_bits_uop_ftqPtr_value;
      req_uop_ftqOffset <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_ftqOffset
               : io_req_0_bits_uop_ftqOffset)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_ftqOffset
              : io_req_1_bits_uop_ftqOffset;
      req_uop_fuType <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_fuType : io_req_0_bits_uop_fuType)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_fuType : io_req_1_bits_uop_fuType;
      req_uop_fuOpType <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_fuOpType : io_req_0_bits_uop_fuOpType)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_fuOpType : io_req_1_bits_uop_fuOpType;
      req_uop_rfWen <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_rfWen : io_req_0_bits_uop_rfWen)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_rfWen : io_req_1_bits_uop_rfWen;
      req_uop_vpu_vstart <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_vpu_vstart
               : io_req_0_bits_uop_vpu_vstart)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_vpu_vstart
              : io_req_1_bits_uop_vpu_vstart;
      req_uop_vpu_nf <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_vpu_nf : io_req_0_bits_uop_vpu_nf)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_vpu_nf : io_req_1_bits_uop_vpu_nf;
      req_uop_vpu_veew <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_vpu_veew : io_req_0_bits_uop_vpu_veew)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_vpu_veew : io_req_1_bits_uop_vpu_veew;
      req_uop_uopIdx <= reqSel_oldest_bits_uop_uopIdx;
      req_uop_pdest <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_uop_pdest : io_req_0_bits_uop_pdest)
          : _reqSel_oldest_T_8 ? io_req_0_bits_uop_pdest : io_req_1_bits_uop_pdest;
      req_uop_robIdx_flag <= reqSel_oldest_bits_uop_robIdx_flag;
      req_uop_robIdx_value <= reqSel_oldest_bits_uop_robIdx_value;
      req_uop_debugInfo_eliminatedMove <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_eliminatedMove
               : io_req_0_bits_uop_debugInfo_eliminatedMove)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_eliminatedMove
              : io_req_1_bits_uop_debugInfo_eliminatedMove;
      req_uop_debugInfo_renameTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_renameTime
               : io_req_0_bits_uop_debugInfo_renameTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_renameTime
              : io_req_1_bits_uop_debugInfo_renameTime;
      req_uop_debugInfo_dispatchTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_dispatchTime
               : io_req_0_bits_uop_debugInfo_dispatchTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_dispatchTime
              : io_req_1_bits_uop_debugInfo_dispatchTime;
      req_uop_debugInfo_enqRsTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_enqRsTime
               : io_req_0_bits_uop_debugInfo_enqRsTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_enqRsTime
              : io_req_1_bits_uop_debugInfo_enqRsTime;
      req_uop_debugInfo_selectTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_selectTime
               : io_req_0_bits_uop_debugInfo_selectTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_selectTime
              : io_req_1_bits_uop_debugInfo_selectTime;
      req_uop_debugInfo_issueTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_issueTime
               : io_req_0_bits_uop_debugInfo_issueTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_issueTime
              : io_req_1_bits_uop_debugInfo_issueTime;
      req_uop_debugInfo_writebackTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_writebackTime
               : io_req_0_bits_uop_debugInfo_writebackTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_writebackTime
              : io_req_1_bits_uop_debugInfo_writebackTime;
      req_uop_debugInfo_runahead_checkpoint_id <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_runahead_checkpoint_id
               : io_req_0_bits_uop_debugInfo_runahead_checkpoint_id)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_runahead_checkpoint_id
              : io_req_1_bits_uop_debugInfo_runahead_checkpoint_id;
      req_uop_debugInfo_tlbFirstReqTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_tlbFirstReqTime
               : io_req_0_bits_uop_debugInfo_tlbFirstReqTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_tlbFirstReqTime
              : io_req_1_bits_uop_debugInfo_tlbFirstReqTime;
      req_uop_debugInfo_tlbRespTime <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_debugInfo_tlbRespTime
               : io_req_0_bits_uop_debugInfo_tlbRespTime)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_debugInfo_tlbRespTime
              : io_req_1_bits_uop_debugInfo_tlbRespTime;
      req_uop_lqIdx_flag <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_lqIdx_flag
               : io_req_0_bits_uop_lqIdx_flag)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_lqIdx_flag
              : io_req_1_bits_uop_lqIdx_flag;
      req_uop_lqIdx_value <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_lqIdx_value
               : io_req_0_bits_uop_lqIdx_value)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_lqIdx_value
              : io_req_1_bits_uop_lqIdx_value;
      req_uop_sqIdx_flag <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_sqIdx_flag
               : io_req_0_bits_uop_sqIdx_flag)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_sqIdx_flag
              : io_req_1_bits_uop_sqIdx_flag;
      req_uop_sqIdx_value <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_uop_sqIdx_value
               : io_req_0_bits_uop_sqIdx_value)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_uop_sqIdx_value
              : io_req_1_bits_uop_sqIdx_value;
      req_vaddr <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_vaddr : io_req_0_bits_vaddr)
          : _reqSel_oldest_T_8 ? io_req_0_bits_vaddr : io_req_1_bits_vaddr;
      req_vaNeedExt <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_vaNeedExt : io_req_0_bits_vaNeedExt)
          : _reqSel_oldest_T_8 ? io_req_0_bits_vaNeedExt : io_req_1_bits_vaNeedExt;
      req_paddr <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_paddr : io_req_0_bits_paddr)
          : _reqSel_oldest_T_8 ? io_req_0_bits_paddr : io_req_1_bits_paddr;
      req_gpaddr <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_gpaddr : io_req_0_bits_gpaddr)
          : _reqSel_oldest_T_8 ? io_req_0_bits_gpaddr : io_req_1_bits_gpaddr;
      req_isForVSnonLeafPTE <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5
               ? io_req_1_bits_isForVSnonLeafPTE
               : io_req_0_bits_isForVSnonLeafPTE)
          : _reqSel_oldest_T_8
              ? io_req_0_bits_isForVSnonLeafPTE
              : io_req_1_bits_isForVSnonLeafPTE;
      req_mask <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_mask : io_req_0_bits_mask)
          : _reqSel_oldest_T_8 ? io_req_0_bits_mask : io_req_1_bits_mask;
      req_isvec <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_isvec : io_req_0_bits_isvec)
          : _reqSel_oldest_T_8 ? io_req_0_bits_isvec : io_req_1_bits_isvec;
      req_elemIdx <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_elemIdx : io_req_0_bits_elemIdx)
          : _reqSel_oldest_T_8 ? io_req_0_bits_elemIdx : io_req_1_bits_elemIdx;
      req_alignedType <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_alignedType : io_req_0_bits_alignedType)
          : _reqSel_oldest_T_8 ? io_req_0_bits_alignedType : io_req_1_bits_alignedType;
      req_mbIndex <=
        _reqSel_oldestIndex_T
          ? (_reqSel_oldest_T_5 ? io_req_1_bits_mbIndex : io_req_0_bits_mbIndex)
          : _reqSel_oldest_T_8 ? io_req_0_bits_mbIndex : io_req_1_bits_mbIndex;
      req_portIndex <= reqSel_3_0;
    end
    REG <= ~req_valid;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:323];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [8:0] i = 9'h0; i < 9'h144; i += 9'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        req_valid = _RANDOM[9'h0][0];
        req_uop_trigger = _RANDOM[9'h3][26:23];
        req_uop_ftqPtr_flag = _RANDOM[9'h4][3];
        req_uop_ftqPtr_value = _RANDOM[9'h4][9:4];
        req_uop_ftqOffset = _RANDOM[9'h4][13:10];
        req_uop_fuType = {_RANDOM[9'h5][31:8], _RANDOM[9'h6][10:0]};
        req_uop_fuOpType = _RANDOM[9'h6][19:11];
        req_uop_rfWen = _RANDOM[9'h6][20];
        req_uop_vpu_vstart = {_RANDOM[9'h8][31:29], _RANDOM[9'h9][4:0]};
        req_uop_vpu_nf = _RANDOM[9'hE][3:1];
        req_uop_vpu_veew = _RANDOM[9'hE][5:4];
        req_uop_uopIdx = _RANDOM[9'hE][25:19];
        req_uop_pdest = {_RANDOM[9'h11][31:25], _RANDOM[9'h12][0]};
        req_uop_robIdx_flag = _RANDOM[9'h12][13];
        req_uop_robIdx_value = _RANDOM[9'h12][21:14];
        req_uop_debugInfo_eliminatedMove = _RANDOM[9'h13][6];
        req_uop_debugInfo_renameTime =
          {_RANDOM[9'h13][31:7], _RANDOM[9'h14], _RANDOM[9'h15][6:0]};
        req_uop_debugInfo_dispatchTime =
          {_RANDOM[9'h15][31:7], _RANDOM[9'h16], _RANDOM[9'h17][6:0]};
        req_uop_debugInfo_enqRsTime =
          {_RANDOM[9'h17][31:7], _RANDOM[9'h18], _RANDOM[9'h19][6:0]};
        req_uop_debugInfo_selectTime =
          {_RANDOM[9'h19][31:7], _RANDOM[9'h1A], _RANDOM[9'h1B][6:0]};
        req_uop_debugInfo_issueTime =
          {_RANDOM[9'h1B][31:7], _RANDOM[9'h1C], _RANDOM[9'h1D][6:0]};
        req_uop_debugInfo_writebackTime =
          {_RANDOM[9'h1D][31:7], _RANDOM[9'h1E], _RANDOM[9'h1F][6:0]};
        req_uop_debugInfo_runahead_checkpoint_id =
          {_RANDOM[9'h1F][31:7], _RANDOM[9'h20], _RANDOM[9'h21][6:0]};
        req_uop_debugInfo_tlbFirstReqTime =
          {_RANDOM[9'h21][31:7], _RANDOM[9'h22], _RANDOM[9'h23][6:0]};
        req_uop_debugInfo_tlbRespTime =
          {_RANDOM[9'h23][31:7], _RANDOM[9'h24], _RANDOM[9'h25][6:0]};
        req_uop_lqIdx_flag = _RANDOM[9'h25][24];
        req_uop_lqIdx_value = _RANDOM[9'h25][31:25];
        req_uop_sqIdx_flag = _RANDOM[9'h26][0];
        req_uop_sqIdx_value = _RANDOM[9'h26][6:1];
        req_vaddr = {_RANDOM[9'h27][31:17], _RANDOM[9'h28], _RANDOM[9'h29][2:0]};
        req_vaNeedExt = _RANDOM[9'h2B][3];
        req_paddr = {_RANDOM[9'h2B][31:5], _RANDOM[9'h2C][20:0]};
        req_gpaddr = {_RANDOM[9'h2C][31:21], _RANDOM[9'h2D], _RANDOM[9'h2E][20:0]};
        req_isForVSnonLeafPTE = _RANDOM[9'h2E][21];
        req_mask = {_RANDOM[9'h2E][31:22], _RANDOM[9'h2F][5:0]};
        req_isvec = _RANDOM[9'h38][4];
        req_elemIdx = _RANDOM[9'h38][16:9];
        req_alignedType = _RANDOM[9'h38][19:17];
        req_mbIndex = _RANDOM[9'h38][23:20];
        req_portIndex = _RANDOM[9'h3E][0];
        needFlushPipe = _RANDOM[9'h3E][1];
        bufferState = _RANDOM[9'h3E][4:2];
        splitStoreReqs_0_uop_ftqPtr_flag = _RANDOM[9'h42][7];
        splitStoreReqs_0_uop_ftqPtr_value = _RANDOM[9'h42][13:8];
        splitStoreReqs_0_uop_ftqOffset = _RANDOM[9'h42][17:14];
        splitStoreReqs_0_uop_fuType = {_RANDOM[9'h43][31:12], _RANDOM[9'h44][14:0]};
        splitStoreReqs_0_uop_fuOpType = _RANDOM[9'h44][23:15];
        splitStoreReqs_0_uop_rfWen = _RANDOM[9'h44][24];
        splitStoreReqs_0_uop_vpu_vstart = _RANDOM[9'h47][8:1];
        splitStoreReqs_0_uop_vpu_nf = _RANDOM[9'h4C][7:5];
        splitStoreReqs_0_uop_vpu_veew = _RANDOM[9'h4C][9:8];
        splitStoreReqs_0_uop_uopIdx = _RANDOM[9'h4C][29:23];
        splitStoreReqs_0_uop_pdest = {_RANDOM[9'h4F][31:29], _RANDOM[9'h50][4:0]};
        splitStoreReqs_0_uop_robIdx_flag = _RANDOM[9'h50][17];
        splitStoreReqs_0_uop_robIdx_value = _RANDOM[9'h50][25:18];
        splitStoreReqs_0_uop_debugInfo_eliminatedMove = _RANDOM[9'h51][10];
        splitStoreReqs_0_uop_debugInfo_renameTime =
          {_RANDOM[9'h51][31:11], _RANDOM[9'h52], _RANDOM[9'h53][10:0]};
        splitStoreReqs_0_uop_debugInfo_dispatchTime =
          {_RANDOM[9'h53][31:11], _RANDOM[9'h54], _RANDOM[9'h55][10:0]};
        splitStoreReqs_0_uop_debugInfo_enqRsTime =
          {_RANDOM[9'h55][31:11], _RANDOM[9'h56], _RANDOM[9'h57][10:0]};
        splitStoreReqs_0_uop_debugInfo_selectTime =
          {_RANDOM[9'h57][31:11], _RANDOM[9'h58], _RANDOM[9'h59][10:0]};
        splitStoreReqs_0_uop_debugInfo_issueTime =
          {_RANDOM[9'h59][31:11], _RANDOM[9'h5A], _RANDOM[9'h5B][10:0]};
        splitStoreReqs_0_uop_debugInfo_writebackTime =
          {_RANDOM[9'h5B][31:11], _RANDOM[9'h5C], _RANDOM[9'h5D][10:0]};
        splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id =
          {_RANDOM[9'h5D][31:11], _RANDOM[9'h5E], _RANDOM[9'h5F][10:0]};
        splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime =
          {_RANDOM[9'h5F][31:11], _RANDOM[9'h60], _RANDOM[9'h61][10:0]};
        splitStoreReqs_0_uop_debugInfo_tlbRespTime =
          {_RANDOM[9'h61][31:11], _RANDOM[9'h62], _RANDOM[9'h63][10:0]};
        splitStoreReqs_0_uop_lqIdx_flag = _RANDOM[9'h63][28];
        splitStoreReqs_0_uop_lqIdx_value = {_RANDOM[9'h63][31:29], _RANDOM[9'h64][3:0]};
        splitStoreReqs_0_uop_sqIdx_flag = _RANDOM[9'h64][4];
        splitStoreReqs_0_uop_sqIdx_value = _RANDOM[9'h64][10:5];
        splitStoreReqs_0_vaddr =
          {_RANDOM[9'h65][31:21], _RANDOM[9'h66], _RANDOM[9'h67][6:0]};
        splitStoreReqs_0_mask = {_RANDOM[9'h6C][31:26], _RANDOM[9'h6D][9:0]};
        splitStoreReqs_0_is128bit = _RANDOM[9'h76][10];
        splitStoreReqs_1_uop_ftqPtr_flag = _RANDOM[9'h80][6];
        splitStoreReqs_1_uop_ftqPtr_value = _RANDOM[9'h80][12:7];
        splitStoreReqs_1_uop_ftqOffset = _RANDOM[9'h80][16:13];
        splitStoreReqs_1_uop_fuType = {_RANDOM[9'h81][31:11], _RANDOM[9'h82][13:0]};
        splitStoreReqs_1_uop_fuOpType = _RANDOM[9'h82][22:14];
        splitStoreReqs_1_uop_rfWen = _RANDOM[9'h82][23];
        splitStoreReqs_1_uop_vpu_vstart = _RANDOM[9'h85][7:0];
        splitStoreReqs_1_uop_vpu_nf = _RANDOM[9'h8A][6:4];
        splitStoreReqs_1_uop_vpu_veew = _RANDOM[9'h8A][8:7];
        splitStoreReqs_1_uop_uopIdx = _RANDOM[9'h8A][28:22];
        splitStoreReqs_1_uop_pdest = {_RANDOM[9'h8D][31:28], _RANDOM[9'h8E][3:0]};
        splitStoreReqs_1_uop_robIdx_flag = _RANDOM[9'h8E][16];
        splitStoreReqs_1_uop_robIdx_value = _RANDOM[9'h8E][24:17];
        splitStoreReqs_1_uop_debugInfo_eliminatedMove = _RANDOM[9'h8F][9];
        splitStoreReqs_1_uop_debugInfo_renameTime =
          {_RANDOM[9'h8F][31:10], _RANDOM[9'h90], _RANDOM[9'h91][9:0]};
        splitStoreReqs_1_uop_debugInfo_dispatchTime =
          {_RANDOM[9'h91][31:10], _RANDOM[9'h92], _RANDOM[9'h93][9:0]};
        splitStoreReqs_1_uop_debugInfo_enqRsTime =
          {_RANDOM[9'h93][31:10], _RANDOM[9'h94], _RANDOM[9'h95][9:0]};
        splitStoreReqs_1_uop_debugInfo_selectTime =
          {_RANDOM[9'h95][31:10], _RANDOM[9'h96], _RANDOM[9'h97][9:0]};
        splitStoreReqs_1_uop_debugInfo_issueTime =
          {_RANDOM[9'h97][31:10], _RANDOM[9'h98], _RANDOM[9'h99][9:0]};
        splitStoreReqs_1_uop_debugInfo_writebackTime =
          {_RANDOM[9'h99][31:10], _RANDOM[9'h9A], _RANDOM[9'h9B][9:0]};
        splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id =
          {_RANDOM[9'h9B][31:10], _RANDOM[9'h9C], _RANDOM[9'h9D][9:0]};
        splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime =
          {_RANDOM[9'h9D][31:10], _RANDOM[9'h9E], _RANDOM[9'h9F][9:0]};
        splitStoreReqs_1_uop_debugInfo_tlbRespTime =
          {_RANDOM[9'h9F][31:10], _RANDOM[9'hA0], _RANDOM[9'hA1][9:0]};
        splitStoreReqs_1_uop_lqIdx_flag = _RANDOM[9'hA1][27];
        splitStoreReqs_1_uop_lqIdx_value = {_RANDOM[9'hA1][31:28], _RANDOM[9'hA2][2:0]};
        splitStoreReqs_1_uop_sqIdx_flag = _RANDOM[9'hA2][3];
        splitStoreReqs_1_uop_sqIdx_value = _RANDOM[9'hA2][9:4];
        splitStoreReqs_1_vaddr =
          {_RANDOM[9'hA3][31:20], _RANDOM[9'hA4], _RANDOM[9'hA5][5:0]};
        splitStoreReqs_1_mask = {_RANDOM[9'hAA][31:25], _RANDOM[9'hAB][8:0]};
        splitStoreReqs_1_is128bit = _RANDOM[9'hB4][9];
        splitStoreResp_1_paddr = {_RANDOM[9'h123][31:7], _RANDOM[9'h124][22:0]};
        isCrossPage = _RANDOM[9'h136][3];
        exceptionVec_3 = _RANDOM[9'h136][7];
        exceptionVec_6 = _RANDOM[9'h136][10];
        exceptionVec_7 = _RANDOM[9'h136][11];
        exceptionVec_15 = _RANDOM[9'h136][19];
        exceptionVec_23 = _RANDOM[9'h136][27];
        unSentStores = _RANDOM[9'h136][29:28];
        curPtr = _RANDOM[9'h137][0];
        globalException = _RANDOM[9'h137][1];
        globalMMIO = _RANDOM[9'h137][2];
        REG = _RANDOM[9'h143][30];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        req_valid = 1'h0;
        needFlushPipe = 1'h0;
        bufferState = 3'h0;
        splitStoreReqs_0_uop_ftqPtr_flag = 1'h0;
        splitStoreReqs_0_uop_ftqPtr_value = 6'h0;
        splitStoreReqs_0_uop_ftqOffset = 4'h0;
        splitStoreReqs_0_uop_fuType = 35'h0;
        splitStoreReqs_0_uop_fuOpType = 9'h0;
        splitStoreReqs_0_uop_rfWen = 1'h0;
        splitStoreReqs_0_uop_vpu_vstart = 8'h0;
        splitStoreReqs_0_uop_vpu_nf = 3'h0;
        splitStoreReqs_0_uop_vpu_veew = 2'h0;
        splitStoreReqs_0_uop_uopIdx = 7'h0;
        splitStoreReqs_0_uop_pdest = 8'h0;
        splitStoreReqs_0_uop_robIdx_flag = 1'h0;
        splitStoreReqs_0_uop_robIdx_value = 8'h0;
        splitStoreReqs_0_uop_debugInfo_eliminatedMove = 1'h0;
        splitStoreReqs_0_uop_debugInfo_renameTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_dispatchTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_enqRsTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_selectTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_issueTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_writebackTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id = 64'h0;
        splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime = 64'h0;
        splitStoreReqs_0_uop_debugInfo_tlbRespTime = 64'h0;
        splitStoreReqs_0_uop_lqIdx_flag = 1'h0;
        splitStoreReqs_0_uop_lqIdx_value = 7'h0;
        splitStoreReqs_0_uop_sqIdx_flag = 1'h0;
        splitStoreReqs_0_uop_sqIdx_value = 6'h0;
        splitStoreReqs_0_vaddr = 50'h0;
        splitStoreReqs_0_mask = 16'h0;
        splitStoreReqs_0_is128bit = 1'h0;
        splitStoreReqs_1_uop_ftqPtr_flag = 1'h0;
        splitStoreReqs_1_uop_ftqPtr_value = 6'h0;
        splitStoreReqs_1_uop_ftqOffset = 4'h0;
        splitStoreReqs_1_uop_fuType = 35'h0;
        splitStoreReqs_1_uop_fuOpType = 9'h0;
        splitStoreReqs_1_uop_rfWen = 1'h0;
        splitStoreReqs_1_uop_vpu_vstart = 8'h0;
        splitStoreReqs_1_uop_vpu_nf = 3'h0;
        splitStoreReqs_1_uop_vpu_veew = 2'h0;
        splitStoreReqs_1_uop_uopIdx = 7'h0;
        splitStoreReqs_1_uop_pdest = 8'h0;
        splitStoreReqs_1_uop_robIdx_flag = 1'h0;
        splitStoreReqs_1_uop_robIdx_value = 8'h0;
        splitStoreReqs_1_uop_debugInfo_eliminatedMove = 1'h0;
        splitStoreReqs_1_uop_debugInfo_renameTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_dispatchTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_enqRsTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_selectTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_issueTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_writebackTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id = 64'h0;
        splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime = 64'h0;
        splitStoreReqs_1_uop_debugInfo_tlbRespTime = 64'h0;
        splitStoreReqs_1_uop_lqIdx_flag = 1'h0;
        splitStoreReqs_1_uop_lqIdx_value = 7'h0;
        splitStoreReqs_1_uop_sqIdx_flag = 1'h0;
        splitStoreReqs_1_uop_sqIdx_value = 6'h0;
        splitStoreReqs_1_vaddr = 50'h0;
        splitStoreReqs_1_mask = 16'h0;
        splitStoreReqs_1_is128bit = 1'h0;
        splitStoreResp_1_paddr = 48'h0;
        isCrossPage = 1'h0;
        exceptionVec_3 = 1'h0;
        exceptionVec_6 = 1'h0;
        exceptionVec_7 = 1'h0;
        exceptionVec_15 = 1'h0;
        exceptionVec_23 = 1'h0;
        unSentStores = 2'h0;
        curPtr = 1'h0;
        globalException = 1'h0;
        globalMMIO = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_0_ready = ~reqSel_3_0 & (~req_valid | _io_req_1_ready_T_2);
  assign io_req_1_ready = reqSel_3_0 & (~req_valid | _io_req_1_ready_T_2);
  assign io_splitStoreReq_valid = io_splitStoreReq_valid_0;
  assign io_splitStoreReq_bits_uop_ftqPtr_flag =
    curPtr ? splitStoreReqs_1_uop_ftqPtr_flag : splitStoreReqs_0_uop_ftqPtr_flag;
  assign io_splitStoreReq_bits_uop_ftqPtr_value =
    curPtr ? splitStoreReqs_1_uop_ftqPtr_value : splitStoreReqs_0_uop_ftqPtr_value;
  assign io_splitStoreReq_bits_uop_ftqOffset =
    curPtr ? splitStoreReqs_1_uop_ftqOffset : splitStoreReqs_0_uop_ftqOffset;
  assign io_splitStoreReq_bits_uop_fuType =
    curPtr ? splitStoreReqs_1_uop_fuType : splitStoreReqs_0_uop_fuType;
  assign io_splitStoreReq_bits_uop_fuOpType =
    req_isvec
      ? req_uop_fuOpType
      : {4'h0,
         req_uop_fuOpType[4] & ~(req_uop_fuOpType[5]) & req_uop_fuOpType[8:7] == 2'h0,
         2'h0,
         curPtr
           ? splitStoreReqs_1_uop_fuOpType[1:0]
           : splitStoreReqs_0_uop_fuOpType[1:0]};
  assign io_splitStoreReq_bits_uop_rfWen =
    curPtr ? splitStoreReqs_1_uop_rfWen : splitStoreReqs_0_uop_rfWen;
  assign io_splitStoreReq_bits_uop_vpu_vstart =
    curPtr ? splitStoreReqs_1_uop_vpu_vstart : splitStoreReqs_0_uop_vpu_vstart;
  assign io_splitStoreReq_bits_uop_vpu_nf =
    curPtr ? splitStoreReqs_1_uop_vpu_nf : splitStoreReqs_0_uop_vpu_nf;
  assign io_splitStoreReq_bits_uop_vpu_veew =
    curPtr ? splitStoreReqs_1_uop_vpu_veew : splitStoreReqs_0_uop_vpu_veew;
  assign io_splitStoreReq_bits_uop_uopIdx =
    curPtr ? splitStoreReqs_1_uop_uopIdx : splitStoreReqs_0_uop_uopIdx;
  assign io_splitStoreReq_bits_uop_pdest =
    curPtr ? splitStoreReqs_1_uop_pdest : splitStoreReqs_0_uop_pdest;
  assign io_splitStoreReq_bits_uop_robIdx_flag =
    curPtr ? splitStoreReqs_1_uop_robIdx_flag : splitStoreReqs_0_uop_robIdx_flag;
  assign io_splitStoreReq_bits_uop_robIdx_value =
    curPtr ? splitStoreReqs_1_uop_robIdx_value : splitStoreReqs_0_uop_robIdx_value;
  assign io_splitStoreReq_bits_uop_debugInfo_eliminatedMove =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_eliminatedMove
      : splitStoreReqs_0_uop_debugInfo_eliminatedMove;
  assign io_splitStoreReq_bits_uop_debugInfo_renameTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_renameTime
      : splitStoreReqs_0_uop_debugInfo_renameTime;
  assign io_splitStoreReq_bits_uop_debugInfo_dispatchTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_dispatchTime
      : splitStoreReqs_0_uop_debugInfo_dispatchTime;
  assign io_splitStoreReq_bits_uop_debugInfo_enqRsTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_enqRsTime
      : splitStoreReqs_0_uop_debugInfo_enqRsTime;
  assign io_splitStoreReq_bits_uop_debugInfo_selectTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_selectTime
      : splitStoreReqs_0_uop_debugInfo_selectTime;
  assign io_splitStoreReq_bits_uop_debugInfo_issueTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_issueTime
      : splitStoreReqs_0_uop_debugInfo_issueTime;
  assign io_splitStoreReq_bits_uop_debugInfo_writebackTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_writebackTime
      : splitStoreReqs_0_uop_debugInfo_writebackTime;
  assign io_splitStoreReq_bits_uop_debugInfo_runahead_checkpoint_id =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_runahead_checkpoint_id
      : splitStoreReqs_0_uop_debugInfo_runahead_checkpoint_id;
  assign io_splitStoreReq_bits_uop_debugInfo_tlbFirstReqTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_tlbFirstReqTime
      : splitStoreReqs_0_uop_debugInfo_tlbFirstReqTime;
  assign io_splitStoreReq_bits_uop_debugInfo_tlbRespTime =
    curPtr
      ? splitStoreReqs_1_uop_debugInfo_tlbRespTime
      : splitStoreReqs_0_uop_debugInfo_tlbRespTime;
  assign io_splitStoreReq_bits_uop_lqIdx_flag =
    curPtr ? splitStoreReqs_1_uop_lqIdx_flag : splitStoreReqs_0_uop_lqIdx_flag;
  assign io_splitStoreReq_bits_uop_lqIdx_value =
    curPtr ? splitStoreReqs_1_uop_lqIdx_value : splitStoreReqs_0_uop_lqIdx_value;
  assign io_splitStoreReq_bits_uop_sqIdx_flag =
    curPtr ? splitStoreReqs_1_uop_sqIdx_flag : splitStoreReqs_0_uop_sqIdx_flag;
  assign io_splitStoreReq_bits_uop_sqIdx_value =
    curPtr ? splitStoreReqs_1_uop_sqIdx_value : splitStoreReqs_0_uop_sqIdx_value;
  assign io_splitStoreReq_bits_vaddr =
    curPtr ? splitStoreReqs_1_vaddr : splitStoreReqs_0_vaddr;
  assign io_splitStoreReq_bits_mask =
    curPtr ? splitStoreReqs_1_mask : splitStoreReqs_0_mask;
  assign io_splitStoreReq_bits_isvec = req_isvec;
  assign io_splitStoreReq_bits_is128bit =
    curPtr ? splitStoreReqs_1_is128bit : splitStoreReqs_0_is128bit;
  assign io_splitStoreReq_bits_isFinalSplit = curPtr;
  assign io_writeBack_valid = io_writeBack_valid_0;
  assign io_writeBack_bits_uop_exceptionVec_3 =
    _io_writeBack_bits_uop_exceptionVec_3_T & exceptionVec_3;
  assign io_writeBack_bits_uop_exceptionVec_6 =
    _io_writeBack_bits_uop_exceptionVec_3_T & exceptionVec_6;
  assign io_writeBack_bits_uop_exceptionVec_7 =
    _io_writeBack_bits_uop_exceptionVec_3_T & exceptionVec_7;
  assign io_writeBack_bits_uop_exceptionVec_15 =
    _io_writeBack_bits_uop_exceptionVec_3_T & exceptionVec_15;
  assign io_writeBack_bits_uop_exceptionVec_23 =
    _io_writeBack_bits_uop_exceptionVec_3_T & exceptionVec_23;
  assign io_writeBack_bits_uop_trigger = req_uop_trigger;
  assign io_writeBack_bits_uop_rfWen = req_uop_rfWen;
  assign io_writeBack_bits_uop_flushPipe = needFlushPipe;
  assign io_writeBack_bits_uop_pdest = req_uop_pdest;
  assign io_writeBack_bits_uop_robIdx_flag = req_uop_robIdx_flag;
  assign io_writeBack_bits_uop_robIdx_value = req_uop_robIdx_value;
  assign io_writeBack_bits_uop_debugInfo_eliminatedMove =
    req_uop_debugInfo_eliminatedMove;
  assign io_writeBack_bits_uop_debugInfo_renameTime = req_uop_debugInfo_renameTime;
  assign io_writeBack_bits_uop_debugInfo_dispatchTime = req_uop_debugInfo_dispatchTime;
  assign io_writeBack_bits_uop_debugInfo_enqRsTime = req_uop_debugInfo_enqRsTime;
  assign io_writeBack_bits_uop_debugInfo_selectTime = req_uop_debugInfo_selectTime;
  assign io_writeBack_bits_uop_debugInfo_issueTime = req_uop_debugInfo_issueTime;
  assign io_writeBack_bits_uop_debugInfo_writebackTime = req_uop_debugInfo_writebackTime;
  assign io_writeBack_bits_uop_debugInfo_runahead_checkpoint_id =
    req_uop_debugInfo_runahead_checkpoint_id;
  assign io_writeBack_bits_uop_debugInfo_tlbFirstReqTime =
    req_uop_debugInfo_tlbFirstReqTime;
  assign io_writeBack_bits_uop_debugInfo_tlbRespTime = req_uop_debugInfo_tlbRespTime;
  assign io_writeBack_bits_uop_sqIdx_flag = req_uop_sqIdx_flag;
  assign io_writeBack_bits_uop_sqIdx_value = req_uop_sqIdx_value;
  assign io_writeBack_bits_debug_isMMIO = globalMMIO;
  assign io_writeBack_bits_debug_paddr = req_paddr;
  assign io_writeBack_bits_debug_vaddr = req_vaddr;
  assign io_vecWriteBack_0_valid = io_vecWriteBack_0_valid_0;
  assign io_vecWriteBack_0_bits_mBIndex = req_mbIndex;
  assign io_vecWriteBack_0_bits_exceptionVec_3 = exceptionVec_3;
  assign io_vecWriteBack_0_bits_exceptionVec_6 = exceptionVec_6;
  assign io_vecWriteBack_0_bits_exceptionVec_7 = exceptionVec_7;
  assign io_vecWriteBack_0_bits_exceptionVec_15 = exceptionVec_15;
  assign io_vecWriteBack_0_bits_exceptionVec_23 = exceptionVec_23;
  assign io_vecWriteBack_0_bits_vaddr = io_vecWriteBack_1_bits_vaddr_0;
  assign io_vecWriteBack_0_bits_vaNeedExt = req_vaNeedExt;
  assign io_vecWriteBack_0_bits_gpaddr = req_gpaddr;
  assign io_vecWriteBack_0_bits_isForVSnonLeafPTE = req_isForVSnonLeafPTE;
  assign io_vecWriteBack_0_bits_vstart = req_uop_vpu_vstart;
  assign io_vecWriteBack_0_bits_elemIdx = req_elemIdx;
  assign io_vecWriteBack_0_bits_mask = req_mask;
  assign io_vecWriteBack_1_valid = io_vecWriteBack_1_valid_0;
  assign io_vecWriteBack_1_bits_mBIndex = req_mbIndex;
  assign io_vecWriteBack_1_bits_exceptionVec_3 = exceptionVec_3;
  assign io_vecWriteBack_1_bits_exceptionVec_6 = exceptionVec_6;
  assign io_vecWriteBack_1_bits_exceptionVec_7 = exceptionVec_7;
  assign io_vecWriteBack_1_bits_exceptionVec_15 = exceptionVec_15;
  assign io_vecWriteBack_1_bits_exceptionVec_23 = exceptionVec_23;
  assign io_vecWriteBack_1_bits_vaddr = io_vecWriteBack_1_bits_vaddr_0;
  assign io_vecWriteBack_1_bits_vaNeedExt = req_vaNeedExt;
  assign io_vecWriteBack_1_bits_gpaddr = req_gpaddr;
  assign io_vecWriteBack_1_bits_isForVSnonLeafPTE = req_isForVSnonLeafPTE;
  assign io_vecWriteBack_1_bits_vstart = req_uop_vpu_vstart;
  assign io_vecWriteBack_1_bits_elemIdx = req_elemIdx;
  assign io_vecWriteBack_1_bits_mask = req_mask;
  assign io_sqControl_toStoreQueue_crossPageWithHit =
    {io_sqControl_toStoreMisalignBuffer_sqPtr_flag,
     io_sqControl_toStoreMisalignBuffer_sqPtr_value} == {req_uop_sqIdx_flag,
                                                         req_uop_sqIdx_value}
    & isCrossPage;
  assign io_sqControl_toStoreQueue_crossPageCanDeq = ~isCrossPage | bufferState == 3'h5;
  assign io_sqControl_toStoreQueue_paddr = {splitStoreResp_1_paddr[47:3], 3'h0};
  assign io_sqControl_toStoreQueue_withSameUop =
    {io_sqControl_toStoreMisalignBuffer_uop_robIdx_flag,
     io_sqControl_toStoreMisalignBuffer_uop_robIdx_value} == _flush_flushItself_T_1
    & io_sqControl_toStoreMisalignBuffer_uop_uopIdx == req_uop_uopIdx & req_isvec
    & robMatch & isCrossPage;
  assign io_toVecStoreMergeBuffer_0_mbIndex = req_mbIndex;
  assign io_toVecStoreMergeBuffer_0_flush =
    _io_toVecStoreMergeBuffer_1_flush_T & cross4KBPageEnq & ~req_portIndex;
  assign io_toVecStoreMergeBuffer_1_mbIndex = req_mbIndex;
  assign io_toVecStoreMergeBuffer_1_flush =
    _io_toVecStoreMergeBuffer_1_flush_T & cross4KBPageEnq & req_portIndex;
  assign io_full = req_valid;
endmodule

