// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module NewPipelineConnectPipe_23(
  input          clock,
  input          reset,
  output         io_in_ready,
  input          io_in_valid,
  input  [34:0]  io_in_bits_fuType,
  input  [8:0]   io_in_bits_fuOpType,
  input  [127:0] io_in_bits_src_0,
  input  [127:0] io_in_bits_src_1,
  input  [127:0] io_in_bits_src_2,
  input  [127:0] io_in_bits_src_3,
  input  [127:0] io_in_bits_src_4,
  input          io_in_bits_robIdx_flag,
  input  [7:0]   io_in_bits_robIdx_value,
  input  [6:0]   io_in_bits_pdest,
  input          io_in_bits_vecWen,
  input          io_in_bits_v0Wen,
  input          io_in_bits_vlWen,
  input          io_in_bits_vpu_vill,
  input          io_in_bits_vpu_vma,
  input          io_in_bits_vpu_vta,
  input  [1:0]   io_in_bits_vpu_vsew,
  input  [2:0]   io_in_bits_vpu_vlmul,
  input          io_in_bits_vpu_specVill,
  input          io_in_bits_vpu_specVma,
  input          io_in_bits_vpu_specVta,
  input  [1:0]   io_in_bits_vpu_specVsew,
  input  [2:0]   io_in_bits_vpu_specVlmul,
  input          io_in_bits_vpu_vm,
  input  [7:0]   io_in_bits_vpu_vstart,
  input  [2:0]   io_in_bits_vpu_frm,
  input          io_in_bits_vpu_fpu_isFpToVecInst,
  input          io_in_bits_vpu_fpu_isFP32Instr,
  input          io_in_bits_vpu_fpu_isFP64Instr,
  input          io_in_bits_vpu_fpu_isReduction,
  input          io_in_bits_vpu_fpu_isFoldTo1_2,
  input          io_in_bits_vpu_fpu_isFoldTo1_4,
  input          io_in_bits_vpu_fpu_isFoldTo1_8,
  input  [1:0]   io_in_bits_vpu_vxrm,
  input  [6:0]   io_in_bits_vpu_vuopIdx,
  input          io_in_bits_vpu_lastUop,
  input  [127:0] io_in_bits_vpu_vmask,
  input  [2:0]   io_in_bits_vpu_nf,
  input  [1:0]   io_in_bits_vpu_veew,
  input          io_in_bits_vpu_isReverse,
  input          io_in_bits_vpu_isExt,
  input          io_in_bits_vpu_isNarrow,
  input          io_in_bits_vpu_isDstMask,
  input          io_in_bits_vpu_isOpMask,
  input          io_in_bits_vpu_isMove,
  input          io_in_bits_vpu_isDependOldVd,
  input          io_in_bits_vpu_isWritePartVd,
  input          io_in_bits_vpu_isVleff,
  input          io_in_bits_ftqIdx_flag,
  input  [5:0]   io_in_bits_ftqIdx_value,
  input  [3:0]   io_in_bits_ftqOffset,
  input  [4:0]   io_in_bits_numLsElem,
  input          io_in_bits_sqIdx_flag,
  input  [5:0]   io_in_bits_sqIdx_value,
  input          io_in_bits_lqIdx_flag,
  input  [6:0]   io_in_bits_lqIdx_value,
  input          io_in_bits_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_bits_perfDebugInfo_renameTime,
  input  [63:0]  io_in_bits_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_bits_perfDebugInfo_selectTime,
  input  [63:0]  io_in_bits_perfDebugInfo_issueTime,
  input  [63:0]  io_in_bits_perfDebugInfo_writebackTime,
  input  [63:0]  io_in_bits_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbRespTime,
  input          io_out_ready,
  output         io_out_valid,
  output [34:0]  io_out_bits_fuType,
  output [8:0]   io_out_bits_fuOpType,
  output [127:0] io_out_bits_src_0,
  output [127:0] io_out_bits_src_1,
  output [127:0] io_out_bits_src_2,
  output [127:0] io_out_bits_src_3,
  output [127:0] io_out_bits_src_4,
  output         io_out_bits_robIdx_flag,
  output [7:0]   io_out_bits_robIdx_value,
  output [6:0]   io_out_bits_pdest,
  output         io_out_bits_vecWen,
  output         io_out_bits_v0Wen,
  output         io_out_bits_vlWen,
  output         io_out_bits_vpu_vill,
  output         io_out_bits_vpu_vma,
  output         io_out_bits_vpu_vta,
  output [1:0]   io_out_bits_vpu_vsew,
  output [2:0]   io_out_bits_vpu_vlmul,
  output         io_out_bits_vpu_specVill,
  output         io_out_bits_vpu_specVma,
  output         io_out_bits_vpu_specVta,
  output [1:0]   io_out_bits_vpu_specVsew,
  output [2:0]   io_out_bits_vpu_specVlmul,
  output         io_out_bits_vpu_vm,
  output [7:0]   io_out_bits_vpu_vstart,
  output [2:0]   io_out_bits_vpu_frm,
  output         io_out_bits_vpu_fpu_isFpToVecInst,
  output         io_out_bits_vpu_fpu_isFP32Instr,
  output         io_out_bits_vpu_fpu_isFP64Instr,
  output         io_out_bits_vpu_fpu_isReduction,
  output         io_out_bits_vpu_fpu_isFoldTo1_2,
  output         io_out_bits_vpu_fpu_isFoldTo1_4,
  output         io_out_bits_vpu_fpu_isFoldTo1_8,
  output [1:0]   io_out_bits_vpu_vxrm,
  output [6:0]   io_out_bits_vpu_vuopIdx,
  output         io_out_bits_vpu_lastUop,
  output [127:0] io_out_bits_vpu_vmask,
  output [2:0]   io_out_bits_vpu_nf,
  output [1:0]   io_out_bits_vpu_veew,
  output         io_out_bits_vpu_isReverse,
  output         io_out_bits_vpu_isExt,
  output         io_out_bits_vpu_isNarrow,
  output         io_out_bits_vpu_isDstMask,
  output         io_out_bits_vpu_isOpMask,
  output         io_out_bits_vpu_isMove,
  output         io_out_bits_vpu_isDependOldVd,
  output         io_out_bits_vpu_isWritePartVd,
  output         io_out_bits_vpu_isVleff,
  output         io_out_bits_ftqIdx_flag,
  output [5:0]   io_out_bits_ftqIdx_value,
  output [3:0]   io_out_bits_ftqOffset,
  output [4:0]   io_out_bits_numLsElem,
  output         io_out_bits_sqIdx_flag,
  output [5:0]   io_out_bits_sqIdx_value,
  output         io_out_bits_lqIdx_flag,
  output [6:0]   io_out_bits_lqIdx_value,
  output         io_out_bits_perfDebugInfo_eliminatedMove,
  output [63:0]  io_out_bits_perfDebugInfo_renameTime,
  output [63:0]  io_out_bits_perfDebugInfo_dispatchTime,
  output [63:0]  io_out_bits_perfDebugInfo_enqRsTime,
  output [63:0]  io_out_bits_perfDebugInfo_selectTime,
  output [63:0]  io_out_bits_perfDebugInfo_issueTime,
  output [63:0]  io_out_bits_perfDebugInfo_writebackTime,
  output [63:0]  io_out_bits_perfDebugInfo_runahead_checkpoint_id,
  output [63:0]  io_out_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_perfDebugInfo_tlbRespTime,
  input          io_rightOutFire,
  input          io_isFlush
);

  reg          valid;
  wire         io_in_ready_0 = io_out_ready | ~valid;
  wire         _data_T = io_in_ready_0 & io_in_valid;
  reg  [34:0]  data_fuType;
  reg  [8:0]   data_fuOpType;
  reg  [127:0] data_src_0;
  reg  [127:0] data_src_1;
  reg  [127:0] data_src_2;
  reg  [127:0] data_src_3;
  reg  [127:0] data_src_4;
  reg          data_robIdx_flag;
  reg  [7:0]   data_robIdx_value;
  reg  [6:0]   data_pdest;
  reg          data_vecWen;
  reg          data_v0Wen;
  reg          data_vlWen;
  reg          data_vpu_vill;
  reg          data_vpu_vma;
  reg          data_vpu_vta;
  reg  [1:0]   data_vpu_vsew;
  reg  [2:0]   data_vpu_vlmul;
  reg          data_vpu_specVill;
  reg          data_vpu_specVma;
  reg          data_vpu_specVta;
  reg  [1:0]   data_vpu_specVsew;
  reg  [2:0]   data_vpu_specVlmul;
  reg          data_vpu_vm;
  reg  [7:0]   data_vpu_vstart;
  reg  [2:0]   data_vpu_frm;
  reg          data_vpu_fpu_isFpToVecInst;
  reg          data_vpu_fpu_isFP32Instr;
  reg          data_vpu_fpu_isFP64Instr;
  reg          data_vpu_fpu_isReduction;
  reg          data_vpu_fpu_isFoldTo1_2;
  reg          data_vpu_fpu_isFoldTo1_4;
  reg          data_vpu_fpu_isFoldTo1_8;
  reg  [1:0]   data_vpu_vxrm;
  reg  [6:0]   data_vpu_vuopIdx;
  reg          data_vpu_lastUop;
  reg  [127:0] data_vpu_vmask;
  reg  [2:0]   data_vpu_nf;
  reg  [1:0]   data_vpu_veew;
  reg          data_vpu_isReverse;
  reg          data_vpu_isExt;
  reg          data_vpu_isNarrow;
  reg          data_vpu_isDstMask;
  reg          data_vpu_isOpMask;
  reg          data_vpu_isMove;
  reg          data_vpu_isDependOldVd;
  reg          data_vpu_isWritePartVd;
  reg          data_vpu_isVleff;
  reg          data_ftqIdx_flag;
  reg  [5:0]   data_ftqIdx_value;
  reg  [3:0]   data_ftqOffset;
  reg  [4:0]   data_numLsElem;
  reg          data_sqIdx_flag;
  reg  [5:0]   data_sqIdx_value;
  reg          data_lqIdx_flag;
  reg  [6:0]   data_lqIdx_value;
  reg          data_perfDebugInfo_eliminatedMove;
  reg  [63:0]  data_perfDebugInfo_renameTime;
  reg  [63:0]  data_perfDebugInfo_dispatchTime;
  reg  [63:0]  data_perfDebugInfo_enqRsTime;
  reg  [63:0]  data_perfDebugInfo_selectTime;
  reg  [63:0]  data_perfDebugInfo_issueTime;
  reg  [63:0]  data_perfDebugInfo_writebackTime;
  reg  [63:0]  data_perfDebugInfo_runahead_checkpoint_id;
  reg  [63:0]  data_perfDebugInfo_tlbFirstReqTime;
  reg  [63:0]  data_perfDebugInfo_tlbRespTime;
  always @(posedge clock or posedge reset) begin
    if (reset)
      valid <= 1'h0;
    else
      valid <= ~io_isFlush & (_data_T | ~io_rightOutFire & valid);
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (_data_T) begin
      data_fuType <= io_in_bits_fuType;
      data_fuOpType <= io_in_bits_fuOpType;
      data_src_0 <= io_in_bits_src_0;
      data_src_1 <= io_in_bits_src_1;
      data_src_2 <= io_in_bits_src_2;
      data_src_3 <= io_in_bits_src_3;
      data_src_4 <= io_in_bits_src_4;
      data_robIdx_flag <= io_in_bits_robIdx_flag;
      data_robIdx_value <= io_in_bits_robIdx_value;
      data_pdest <= io_in_bits_pdest;
      data_vecWen <= io_in_bits_vecWen;
      data_v0Wen <= io_in_bits_v0Wen;
      data_vlWen <= io_in_bits_vlWen;
      data_vpu_vill <= io_in_bits_vpu_vill;
      data_vpu_vma <= io_in_bits_vpu_vma;
      data_vpu_vta <= io_in_bits_vpu_vta;
      data_vpu_vsew <= io_in_bits_vpu_vsew;
      data_vpu_vlmul <= io_in_bits_vpu_vlmul;
      data_vpu_specVill <= io_in_bits_vpu_specVill;
      data_vpu_specVma <= io_in_bits_vpu_specVma;
      data_vpu_specVta <= io_in_bits_vpu_specVta;
      data_vpu_specVsew <= io_in_bits_vpu_specVsew;
      data_vpu_specVlmul <= io_in_bits_vpu_specVlmul;
      data_vpu_vm <= io_in_bits_vpu_vm;
      data_vpu_vstart <= io_in_bits_vpu_vstart;
      data_vpu_frm <= io_in_bits_vpu_frm;
      data_vpu_fpu_isFpToVecInst <= io_in_bits_vpu_fpu_isFpToVecInst;
      data_vpu_fpu_isFP32Instr <= io_in_bits_vpu_fpu_isFP32Instr;
      data_vpu_fpu_isFP64Instr <= io_in_bits_vpu_fpu_isFP64Instr;
      data_vpu_fpu_isReduction <= io_in_bits_vpu_fpu_isReduction;
      data_vpu_fpu_isFoldTo1_2 <= io_in_bits_vpu_fpu_isFoldTo1_2;
      data_vpu_fpu_isFoldTo1_4 <= io_in_bits_vpu_fpu_isFoldTo1_4;
      data_vpu_fpu_isFoldTo1_8 <= io_in_bits_vpu_fpu_isFoldTo1_8;
      data_vpu_vxrm <= io_in_bits_vpu_vxrm;
      data_vpu_vuopIdx <= io_in_bits_vpu_vuopIdx;
      data_vpu_lastUop <= io_in_bits_vpu_lastUop;
      data_vpu_vmask <= io_in_bits_vpu_vmask;
      data_vpu_nf <= io_in_bits_vpu_nf;
      data_vpu_veew <= io_in_bits_vpu_veew;
      data_vpu_isReverse <= io_in_bits_vpu_isReverse;
      data_vpu_isExt <= io_in_bits_vpu_isExt;
      data_vpu_isNarrow <= io_in_bits_vpu_isNarrow;
      data_vpu_isDstMask <= io_in_bits_vpu_isDstMask;
      data_vpu_isOpMask <= io_in_bits_vpu_isOpMask;
      data_vpu_isMove <= io_in_bits_vpu_isMove;
      data_vpu_isDependOldVd <= io_in_bits_vpu_isDependOldVd;
      data_vpu_isWritePartVd <= io_in_bits_vpu_isWritePartVd;
      data_vpu_isVleff <= io_in_bits_vpu_isVleff;
      data_ftqIdx_flag <= io_in_bits_ftqIdx_flag;
      data_ftqIdx_value <= io_in_bits_ftqIdx_value;
      data_ftqOffset <= io_in_bits_ftqOffset;
      data_numLsElem <= io_in_bits_numLsElem;
      data_sqIdx_flag <= io_in_bits_sqIdx_flag;
      data_sqIdx_value <= io_in_bits_sqIdx_value;
      data_lqIdx_flag <= io_in_bits_lqIdx_flag;
      data_lqIdx_value <= io_in_bits_lqIdx_value;
      data_perfDebugInfo_eliminatedMove <= io_in_bits_perfDebugInfo_eliminatedMove;
      data_perfDebugInfo_renameTime <= io_in_bits_perfDebugInfo_renameTime;
      data_perfDebugInfo_dispatchTime <= io_in_bits_perfDebugInfo_dispatchTime;
      data_perfDebugInfo_enqRsTime <= io_in_bits_perfDebugInfo_enqRsTime;
      data_perfDebugInfo_selectTime <= io_in_bits_perfDebugInfo_selectTime;
      data_perfDebugInfo_issueTime <= io_in_bits_perfDebugInfo_issueTime;
      data_perfDebugInfo_writebackTime <= io_in_bits_perfDebugInfo_writebackTime;
      data_perfDebugInfo_runahead_checkpoint_id <=
        io_in_bits_perfDebugInfo_runahead_checkpoint_id;
      data_perfDebugInfo_tlbFirstReqTime <= io_in_bits_perfDebugInfo_tlbFirstReqTime;
      data_perfDebugInfo_tlbRespTime <= io_in_bits_perfDebugInfo_tlbRespTime;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:49];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h32; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid = _RANDOM[6'h0][0];
        data_fuType = {_RANDOM[6'h0][31:1], _RANDOM[6'h1][3:0]};
        data_fuOpType = _RANDOM[6'h1][12:4];
        data_src_0 =
          {_RANDOM[6'h1][31:13],
           _RANDOM[6'h2],
           _RANDOM[6'h3],
           _RANDOM[6'h4],
           _RANDOM[6'h5][12:0]};
        data_src_1 =
          {_RANDOM[6'h5][31:13],
           _RANDOM[6'h6],
           _RANDOM[6'h7],
           _RANDOM[6'h8],
           _RANDOM[6'h9][12:0]};
        data_src_2 =
          {_RANDOM[6'h9][31:13],
           _RANDOM[6'hA],
           _RANDOM[6'hB],
           _RANDOM[6'hC],
           _RANDOM[6'hD][12:0]};
        data_src_3 =
          {_RANDOM[6'hD][31:13],
           _RANDOM[6'hE],
           _RANDOM[6'hF],
           _RANDOM[6'h10],
           _RANDOM[6'h11][12:0]};
        data_src_4 =
          {_RANDOM[6'h11][31:13],
           _RANDOM[6'h12],
           _RANDOM[6'h13],
           _RANDOM[6'h14],
           _RANDOM[6'h15][12:0]};
        data_robIdx_flag = _RANDOM[6'h17][13];
        data_robIdx_value = _RANDOM[6'h17][21:14];
        data_pdest = {_RANDOM[6'h17][31:27], _RANDOM[6'h18][1:0]};
        data_vecWen = _RANDOM[6'h18][2];
        data_v0Wen = _RANDOM[6'h18][3];
        data_vlWen = _RANDOM[6'h18][4];
        data_vpu_vill = _RANDOM[6'h18][5];
        data_vpu_vma = _RANDOM[6'h18][6];
        data_vpu_vta = _RANDOM[6'h18][7];
        data_vpu_vsew = _RANDOM[6'h18][9:8];
        data_vpu_vlmul = _RANDOM[6'h18][12:10];
        data_vpu_specVill = _RANDOM[6'h18][13];
        data_vpu_specVma = _RANDOM[6'h18][14];
        data_vpu_specVta = _RANDOM[6'h18][15];
        data_vpu_specVsew = _RANDOM[6'h18][17:16];
        data_vpu_specVlmul = _RANDOM[6'h18][20:18];
        data_vpu_vm = _RANDOM[6'h18][21];
        data_vpu_vstart = _RANDOM[6'h18][29:22];
        data_vpu_frm = {_RANDOM[6'h18][31:30], _RANDOM[6'h19][0]};
        data_vpu_fpu_isFpToVecInst = _RANDOM[6'h19][1];
        data_vpu_fpu_isFP32Instr = _RANDOM[6'h19][2];
        data_vpu_fpu_isFP64Instr = _RANDOM[6'h19][3];
        data_vpu_fpu_isReduction = _RANDOM[6'h19][4];
        data_vpu_fpu_isFoldTo1_2 = _RANDOM[6'h19][5];
        data_vpu_fpu_isFoldTo1_4 = _RANDOM[6'h19][6];
        data_vpu_fpu_isFoldTo1_8 = _RANDOM[6'h19][7];
        data_vpu_vxrm = _RANDOM[6'h19][9:8];
        data_vpu_vuopIdx = _RANDOM[6'h19][16:10];
        data_vpu_lastUop = _RANDOM[6'h19][17];
        data_vpu_vmask =
          {_RANDOM[6'h19][31:18],
           _RANDOM[6'h1A],
           _RANDOM[6'h1B],
           _RANDOM[6'h1C],
           _RANDOM[6'h1D][17:0]};
        data_vpu_nf = _RANDOM[6'h1D][28:26];
        data_vpu_veew = _RANDOM[6'h1D][30:29];
        data_vpu_isReverse = _RANDOM[6'h1D][31];
        data_vpu_isExt = _RANDOM[6'h1E][0];
        data_vpu_isNarrow = _RANDOM[6'h1E][1];
        data_vpu_isDstMask = _RANDOM[6'h1E][2];
        data_vpu_isOpMask = _RANDOM[6'h1E][3];
        data_vpu_isMove = _RANDOM[6'h1E][4];
        data_vpu_isDependOldVd = _RANDOM[6'h1E][5];
        data_vpu_isWritePartVd = _RANDOM[6'h1E][6];
        data_vpu_isVleff = _RANDOM[6'h1E][7];
        data_ftqIdx_flag = _RANDOM[6'h1E][9];
        data_ftqIdx_value = _RANDOM[6'h1E][15:10];
        data_ftqOffset = _RANDOM[6'h1E][19:16];
        data_numLsElem = _RANDOM[6'h1E][24:20];
        data_sqIdx_flag = _RANDOM[6'h1E][25];
        data_sqIdx_value = _RANDOM[6'h1E][31:26];
        data_lqIdx_flag = _RANDOM[6'h1F][0];
        data_lqIdx_value = _RANDOM[6'h1F][7:1];
        data_perfDebugInfo_eliminatedMove = _RANDOM[6'h1F][28];
        data_perfDebugInfo_renameTime =
          {_RANDOM[6'h1F][31:29], _RANDOM[6'h20], _RANDOM[6'h21][28:0]};
        data_perfDebugInfo_dispatchTime =
          {_RANDOM[6'h21][31:29], _RANDOM[6'h22], _RANDOM[6'h23][28:0]};
        data_perfDebugInfo_enqRsTime =
          {_RANDOM[6'h23][31:29], _RANDOM[6'h24], _RANDOM[6'h25][28:0]};
        data_perfDebugInfo_selectTime =
          {_RANDOM[6'h25][31:29], _RANDOM[6'h26], _RANDOM[6'h27][28:0]};
        data_perfDebugInfo_issueTime =
          {_RANDOM[6'h27][31:29], _RANDOM[6'h28], _RANDOM[6'h29][28:0]};
        data_perfDebugInfo_writebackTime =
          {_RANDOM[6'h29][31:29], _RANDOM[6'h2A], _RANDOM[6'h2B][28:0]};
        data_perfDebugInfo_runahead_checkpoint_id =
          {_RANDOM[6'h2B][31:29], _RANDOM[6'h2C], _RANDOM[6'h2D][28:0]};
        data_perfDebugInfo_tlbFirstReqTime =
          {_RANDOM[6'h2D][31:29], _RANDOM[6'h2E], _RANDOM[6'h2F][28:0]};
        data_perfDebugInfo_tlbRespTime =
          {_RANDOM[6'h2F][31:29], _RANDOM[6'h30], _RANDOM[6'h31][28:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        valid = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = io_in_ready_0;
  assign io_out_valid = valid;
  assign io_out_bits_fuType = data_fuType;
  assign io_out_bits_fuOpType = data_fuOpType;
  assign io_out_bits_src_0 = data_src_0;
  assign io_out_bits_src_1 = data_src_1;
  assign io_out_bits_src_2 = data_src_2;
  assign io_out_bits_src_3 = data_src_3;
  assign io_out_bits_src_4 = data_src_4;
  assign io_out_bits_robIdx_flag = data_robIdx_flag;
  assign io_out_bits_robIdx_value = data_robIdx_value;
  assign io_out_bits_pdest = data_pdest;
  assign io_out_bits_vecWen = data_vecWen;
  assign io_out_bits_v0Wen = data_v0Wen;
  assign io_out_bits_vlWen = data_vlWen;
  assign io_out_bits_vpu_vill = data_vpu_vill;
  assign io_out_bits_vpu_vma = data_vpu_vma;
  assign io_out_bits_vpu_vta = data_vpu_vta;
  assign io_out_bits_vpu_vsew = data_vpu_vsew;
  assign io_out_bits_vpu_vlmul = data_vpu_vlmul;
  assign io_out_bits_vpu_specVill = data_vpu_specVill;
  assign io_out_bits_vpu_specVma = data_vpu_specVma;
  assign io_out_bits_vpu_specVta = data_vpu_specVta;
  assign io_out_bits_vpu_specVsew = data_vpu_specVsew;
  assign io_out_bits_vpu_specVlmul = data_vpu_specVlmul;
  assign io_out_bits_vpu_vm = data_vpu_vm;
  assign io_out_bits_vpu_vstart = data_vpu_vstart;
  assign io_out_bits_vpu_frm = data_vpu_frm;
  assign io_out_bits_vpu_fpu_isFpToVecInst = data_vpu_fpu_isFpToVecInst;
  assign io_out_bits_vpu_fpu_isFP32Instr = data_vpu_fpu_isFP32Instr;
  assign io_out_bits_vpu_fpu_isFP64Instr = data_vpu_fpu_isFP64Instr;
  assign io_out_bits_vpu_fpu_isReduction = data_vpu_fpu_isReduction;
  assign io_out_bits_vpu_fpu_isFoldTo1_2 = data_vpu_fpu_isFoldTo1_2;
  assign io_out_bits_vpu_fpu_isFoldTo1_4 = data_vpu_fpu_isFoldTo1_4;
  assign io_out_bits_vpu_fpu_isFoldTo1_8 = data_vpu_fpu_isFoldTo1_8;
  assign io_out_bits_vpu_vxrm = data_vpu_vxrm;
  assign io_out_bits_vpu_vuopIdx = data_vpu_vuopIdx;
  assign io_out_bits_vpu_lastUop = data_vpu_lastUop;
  assign io_out_bits_vpu_vmask = data_vpu_vmask;
  assign io_out_bits_vpu_nf = data_vpu_nf;
  assign io_out_bits_vpu_veew = data_vpu_veew;
  assign io_out_bits_vpu_isReverse = data_vpu_isReverse;
  assign io_out_bits_vpu_isExt = data_vpu_isExt;
  assign io_out_bits_vpu_isNarrow = data_vpu_isNarrow;
  assign io_out_bits_vpu_isDstMask = data_vpu_isDstMask;
  assign io_out_bits_vpu_isOpMask = data_vpu_isOpMask;
  assign io_out_bits_vpu_isMove = data_vpu_isMove;
  assign io_out_bits_vpu_isDependOldVd = data_vpu_isDependOldVd;
  assign io_out_bits_vpu_isWritePartVd = data_vpu_isWritePartVd;
  assign io_out_bits_vpu_isVleff = data_vpu_isVleff;
  assign io_out_bits_ftqIdx_flag = data_ftqIdx_flag;
  assign io_out_bits_ftqIdx_value = data_ftqIdx_value;
  assign io_out_bits_ftqOffset = data_ftqOffset;
  assign io_out_bits_numLsElem = data_numLsElem;
  assign io_out_bits_sqIdx_flag = data_sqIdx_flag;
  assign io_out_bits_sqIdx_value = data_sqIdx_value;
  assign io_out_bits_lqIdx_flag = data_lqIdx_flag;
  assign io_out_bits_lqIdx_value = data_lqIdx_value;
  assign io_out_bits_perfDebugInfo_eliminatedMove = data_perfDebugInfo_eliminatedMove;
  assign io_out_bits_perfDebugInfo_renameTime = data_perfDebugInfo_renameTime;
  assign io_out_bits_perfDebugInfo_dispatchTime = data_perfDebugInfo_dispatchTime;
  assign io_out_bits_perfDebugInfo_enqRsTime = data_perfDebugInfo_enqRsTime;
  assign io_out_bits_perfDebugInfo_selectTime = data_perfDebugInfo_selectTime;
  assign io_out_bits_perfDebugInfo_issueTime = data_perfDebugInfo_issueTime;
  assign io_out_bits_perfDebugInfo_writebackTime = data_perfDebugInfo_writebackTime;
  assign io_out_bits_perfDebugInfo_runahead_checkpoint_id =
    data_perfDebugInfo_runahead_checkpoint_id;
  assign io_out_bits_perfDebugInfo_tlbFirstReqTime = data_perfDebugInfo_tlbFirstReqTime;
  assign io_out_bits_perfDebugInfo_tlbRespTime = data_perfDebugInfo_tlbRespTime;
endmodule

